### ISSUE TITLE
[Aurascan][Contracts][ContractDetails] View All Transaction, Address To không hiển thị textlink

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#1000]
**Describe the bug**

- [ ] ISSUE: View All Transaction, Address To không hiển thị format textlink

**To Reproduce**
1. Go to Contract Details
2. Click on View all button in Transactions tab
3. See error

**Screenshots**
Link: https://serenity.aurascan.io/contracts/transactions/aura160nrpx8kvd72kctmvlraeumv9du5qetkqd79w96gya449ke2a2ds2lf6ag
![image](https://user-images.githubusercontent.com/72438169/190295778-80bbd7fd-bdd5-4b39-be17-aef6f9eba8f6.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/72438169/190295872-2d32f0a4-cea6-477f-b5ec-b3da73631673.png)

**Comment by mtamkg** [comment]
chỗ link này sẽ link tới contract hiện tại
=> không cần link

![image](https://user-images.githubusercontent.com/99626599/190296419-4624adcf-0317-4884-abd3-da1bab22e5fd.png)

**Comment by Dpthao245** [comment]
PASS in Serenity 20/09/2022
![image](https://user-images.githubusercontent.com/72438169/191206826-d41d69ad-6a43-4e3e-8b1f-36d638b0e89c.png)
![image](https://user-images.githubusercontent.com/72438169/191207223-7b72b65a-5614-4127-a592-e1f2de004665.png)
![image](https://user-images.githubusercontent.com/72438169/191207338-89bac5f2-3d8c-4b93-8792-b0ecb77faec8.png)
![image](https://user-images.githubusercontent.com/72438169/191207543-924dfb62-f2de-4449-937b-6fdb76448572.png)

**Comment by Dpthao245** [comment]
PASS in Euphoria 07/10/2022
![image](https://user-images.githubusercontent.com/72438169/194506698-76631b93-9ac3-474c-8164-4b82eb8ef88f.png)
![image](https://user-images.githubusercontent.com/72438169/194506761-b2427f95-3173-4c1f-b51c-deef65c24179.png)
