### ISSUE TITLE
[Contract] Search for Address/ Creator address/ Code ID in Contracts list

### ISSUE THREAD

**Issue by NgocAnh7278** [aura-nw/aurascan#1009]
![image](https://user-images.githubusercontent.com/40628286/190579956-cf2ffc4b-face-48af-81f6-e5d45d37aba1.png)
Hint: "Search for Contract Name/ Address/ Creator address/ Code ID"
- Search like và = cho các trường Contract name, contract address, creator address, code id
- Nếu input search là number -> ưu tiên search theo code id
- Nếu input search là aura... -> ưu tiên search theo contract address, creator address
- Nếu input search khác các trường hợp trên -> search theo contract name

Với màn hình Đăng ký deploy contract lên mainnet, chọn requester address/ code id thì hiển thị chính xác danh sách contract thuộc creator address hoặc code id
- Search = cho requester address/ code id
![image](https://user-images.githubusercontent.com/40628286/191162901-6d2cf79d-7dd2-43ae-a4c8-485987e40a96.png)

**Comment by ntatfff** [comment]
Verified PASS on serenity - View Request popup  (23/09/2022)
Link  - https://approve.dev.aura.network/received-request
- Click on a Code ID
![image](https://user-images.githubusercontent.com/24869170/191936125-c1db4d1b-a64a-46b4-a4a5-90042c7c0359.png)
![image](https://user-images.githubusercontent.com/24869170/191936001-09331737-f06d-4d4b-9ef6-de7ce1063087.png)
- Click on a "Requester Address"
![image](https://user-images.githubusercontent.com/24869170/191936247-14bfd3ce-822f-4484-b6ce-787be9d014d0.png)
![image](https://user-images.githubusercontent.com/24869170/191936305-ac59814f-9783-4a12-ad36-a572086e1225.png)

**Comment by Dpthao245** [comment]
PASS in Euphoria 07/10/2022
Contracts List
![image](https://user-images.githubusercontent.com/72438169/194508930-3df002f3-661f-4f22-89c0-0d91a36dba74.png)

Search for Code ID
![image](https://user-images.githubusercontent.com/72438169/194509337-87abbb1f-cda2-49ed-b3d5-1468b24379ee.png)

Search for Creator Address
![image](https://user-images.githubusercontent.com/72438169/194509519-ce0bb5d6-a3a8-4d04-8e29-c88295954a2b.png)

Search for Contract Address
![image](https://user-images.githubusercontent.com/72438169/194509686-b556c6e0-2d34-4198-bf96-e6c83eda225d.png)

Search for Contract Name
![image](https://user-images.githubusercontent.com/72438169/194509808-8f38a021-a338-46cf-b01b-b9be2009e379.png)
