### ISSUE TITLE
[Transaction_Details] Show message of Multisend txn from Pyxis Safe

### ISSUE THREAD

**Issue by NgocAnh7278** [aura-nw/aurascan#1012]
Transaction: https://explorer.dev.aura.network/transaction/97009C90F119D7C73AF7737743E462F02605E0FCD62CF638C5472F43920BFF39?_ga=2.14644663.1096597076.1663127164-926174388.1654240002

- [x] Show all txns Send from body/messages
- [x] How to display many messages in a transaction like get reward txn:
![image](https://user-images.githubusercontent.com/40628286/190974762-49d87161-6730-4a2f-bd64-c203cfc9ffeb.png)

- [x] Show data if have so much messages: 10 records first, scroll -> load more data (10 records) -> scroll -> load more data

**Comment by ntatfff** [comment]
Verified FAIL on serenity (03/10/2022)
- [ ] Thiếu transaction Send, khi From Address giống To Address
- [ ] Received address hiển thị sai Type (Send -> Receive)

**Comment by ntatfff** [comment]
> Verified FAIL on serenity (05/10/2022)
> 
> * [ ]  Thiếu transaction Send, khi From Address giống To Address
=> FAIL 
![image](https://user-images.githubusercontent.com/24869170/194033580-148d2a6a-0135-441b-88bc-8c10b8b1e591.png)
> * [x]  Received address hiển thị sai Type (Send -> Receive)
=> PASS 
![image](https://user-images.githubusercontent.com/24869170/194033125-97a24036-910e-45e5-a978-664f49aa7ab8.png)

**Comment by ntatfff** [comment]
Bỏ qua trường hợp user tự send cho chính mình
![image](https://user-images.githubusercontent.com/24869170/194201270-bc185148-a120-4225-b016-b55f37004fb8.png)

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (07/10/2022)
![image](https://user-images.githubusercontent.com/24869170/194521704-5d9f9cd8-3e2b-407c-9f20-2f5f048ef629.png)
![image](https://user-images.githubusercontent.com/24869170/194521739-d812d644-f456-4586-b3d7-250df0cd428d.png)
![image](https://user-images.githubusercontent.com/24869170/194521852-2f7420b8-7187-4e81-ae01-461473c25d8f.png)
![image](https://user-images.githubusercontent.com/24869170/194521881-5bfd01e1-10e9-4cb6-825a-bb2e081494f6.png)
![image](https://user-images.githubusercontent.com/24869170/194521948-921dd30b-8e75-414a-a953-516f0026ec18.png)
![image](https://user-images.githubusercontent.com/24869170/194521993-f65bbff6-4567-484d-ba18-6a5d99754656.png)
