### ISSUE TITLE
[Aurascan][AccountDetails][IBCTransactions] Display Amount at Received address

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1017]
**Description**
Màn hình account details, received address: Amount được thực hiện từ IBC transfer (từ chain khác)

**Expected behavior**
- [x] Hiện dòng data của chain khác ở dưới dòng Aura
- [x] Sort giảm dần theo Value

**Screenshots**
![image](https://user-images.githubusercontent.com/24869170/191160261-87b6864a-1829-4d9a-9666-475c174088a2.png)
![image](https://user-images.githubusercontent.com/24869170/191160421-d2b0c56f-253c-4443-b5a7-b5261e284534.png)

**Comment by thub1310577** [comment]
![image](https://user-images.githubusercontent.com/26767562/191165054-26dceb82-e394-4379-994a-71a58276a820.png)

**Comment by ntatfff** [comment]
Verified FAIL on serenity (23/09/2022)
- [ ] Logo của token chưa được bo tròn 
- [ ] Hiển thị thiếu Price, Change (24H), Value ở dòng Aura
![image](https://user-images.githubusercontent.com/24869170/191915013-62a213ca-b3bd-4d3f-aeff-968a99ff49d5.png)

**Comment by ntatfff** [comment]
Verified PASS on serenity (26/09/2022)
![image](https://user-images.githubusercontent.com/24869170/192223391-b48deaac-3f84-450a-81de-4d24ad37175c.png)
![image](https://user-images.githubusercontent.com/24869170/192223440-3337c922-aafa-4639-ad3f-8853c77e803b.png)
![image](https://user-images.githubusercontent.com/24869170/192223778-43ed2786-5fe7-4267-b90a-2dc86f550f92.png)
![image](https://user-images.githubusercontent.com/24869170/192223852-7fa2d626-5463-4b00-acca-995a42890a1c.png)

**Comment by ntatfff** [comment]
Chờ anh Kiên add configuration
