### ISSUE TITLE
[Aurascan][AccountDetails] Not display all NFTs when number of NFTs >100

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1018]
**Describe the bug**
Address has over 100 NFTs, but display only 100 NFTs

**To Reproduce**
1. Go to Account details has >100 NFTs https://serenity.aurascan.io/account/aura1572sv0qcm9fzy8glqj6dy7jm8zayw7g9e3ss3m
2. Check NFT Assets information
3. See error

**Expected behavior**
Display all NFTs of address when number of NFTs >100

**Screenshots**
![image](https://user-images.githubusercontent.com/24869170/191161604-716f7d4b-4120-4922-9a5c-7bfd5910897c.png)

**Comment by fibonacci998** [comment]
Currently Indexer will not count all asset, it will count approximately for pagination, not count all to avoid overload database. Frontend should be displayed as "100 NFT and more"

**Comment by nhphuc2411** [comment]
Apply to show text "and more" if received nextkey from indexer

**Comment by ntatfff** [comment]
Verified PASS on serenity (07/10/2022)
- Click next page
![image](https://user-images.githubusercontent.com/24869170/194481312-8c3cdabb-b543-4734-aa2b-308d8b80c657.png)
![image](https://user-images.githubusercontent.com/24869170/194481577-e7b3cf6b-e439-46dd-a140-2d73b5a89c08.png)
- Switch account 
![image](https://user-images.githubusercontent.com/24869170/194481843-080256be-cc2c-4a1e-baae-5f2b0ac316f8.png)
