### ISSUE TITLE
[UI] Improve UI for messages of txns and button

### ISSUE THREAD

**Issue by NgocAnh7278** [aura-nw/aurascan#1030]
- [x] Update all buttons and textboxes from circle -> square
![image](https://user-images.githubusercontent.com/40628286/191646024-eb23f290-eaac-42d6-b6a3-b3e8ee51bfe2.png)
**Update**:
![image](https://user-images.githubusercontent.com/40628286/191645909-aa67fada-06a5-49d4-88aa-ddb81c60c2f4.png)

- [x] Improve UI for messages of txns
https://www.figma.com/file/xiW41QvCutlazTw9PSQC01/%5BAura%5D-Scan?node-id=2847%3A126404

- [x] Update colors of voting options
![image](https://user-images.githubusercontent.com/40628286/191646303-ff99cb6d-a9a1-46c8-b47e-8fd173832044.png)
https://www.figma.com/file/xiW41QvCutlazTw9PSQC01/%5BAura%5D-Scan?node-id=2857%3A127890

**Comment by Dpthao245** [comment]
PASS in Serenity 28/09/2022
ISSUE 01:
![image](https://user-images.githubusercontent.com/72438169/192712121-93e9242f-95c5-47a4-99e0-715726d67593.png)
![image](https://user-images.githubusercontent.com/72438169/192712162-afd4495d-6be3-4708-b413-8593cbf806a7.png)

ISSUE 03:
![image](https://user-images.githubusercontent.com/72438169/192712003-c86384d9-7379-4b90-9ae2-41dabd5d0dc5.png)

**Comment by Dpthao245** [comment]
PASS in Euphoria 10/10/2022
ISSUE 01:
![image](https://user-images.githubusercontent.com/72438169/194791000-340b90b4-820c-42ce-9548-0a7806977e96.png)

ISSUE 03:
![image](https://user-images.githubusercontent.com/72438169/194791031-af961cd4-4bd3-40f7-819a-f35596e3e7ff.png)
