### ISSUE TITLE
[Aurascan][Southbound] Add new Southbound layout

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1047]
**Expected behavior**
Add new Southbound layout on screen:

- [ ] Validator details
+ Number NFT = 0: not display southbound
+ Number NFT >= 1: display southbound
![image](https://user-images.githubusercontent.com/24869170/191917812-5ff10f17-b9ec-47fe-95fa-a1bb70026027.png)

- [ ] Account details
+ Number NFT = 0: not display southbound
+ Number NFT >= 1: display southbound
![image](https://user-images.githubusercontent.com/24869170/191918208-f5b847c6-bb6e-476a-8563-27bc4868382b.png)

**Comment by Dpthao245** [comment]
Account Details: có 1 SBT unclaim
![image](https://user-images.githubusercontent.com/72438169/211452423-ee1ea6fa-2501-40b5-ad76-9b7b2c2db32e.png)

Validator Details: không hiển thị SBT
![image](https://user-images.githubusercontent.com/72438169/211454276-2cb5fdb2-8947-4a4b-8942-c76ecc0a6bc3.png)
