### ISSUE TITLE
[Aurascan][RegisterContract] List Code ID: không hiển thị Code ID của Contract chưa đăng ký Type

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#1074]
**Describe the bug**

- [ ] ISSUE: List Code ID: không hiển thị Code ID của Contract chưa đăng ký Type

**Screenshots**

Contracts List: Contract có Code ID 436 và Type Contract "-"
![image](https://user-images.githubusercontent.com/72438169/192496940-8a08283c-82b5-44b6-9cd3-aaa6f7a57495.png)

Smart Contracts List: Contract có Code ID 436 và Type Contract "-"
![image](https://user-images.githubusercontent.com/72438169/192497950-bfd0e736-98a6-4d58-a349-b94a2120785d.png)

Register Contracts to Deploy on Mainnet: List Code ID không hiển thị 436
![image](https://user-images.githubusercontent.com/72438169/192497774-6462e980-d8ab-40d2-97fe-4345bf667a55.png)

**Comment by thub1310577** [comment]
khi verify con này, @Dpthao245 check qua 1 vòng cái màn hình sau nha:
1. contracts list
2. smart contracts list
3. register type contract
4. update type contract

**Comment by Dpthao245** [comment]
PASS in Serenity 28/09/2022

**Trường hợp 01: Khởi tạo contract, chưa đăng ký type contract** 

Contracts List: Contract có Code ID = "449" và Type Contract = "-"
![image](https://user-images.githubusercontent.com/72438169/192728825-48a9956e-8ad2-42d2-a801-83db63b2cf6e.png)

Type Smart Contract: Contract có Code ID = "449" chưa đăng ký Type Contract
![image](https://user-images.githubusercontent.com/72438169/192728986-7221c819-4d33-494f-9b5f-82755b7dbbe3.png)

Smart contracts list: Contract có Code ID = "449" và Type Contract = "-"
![image](https://user-images.githubusercontent.com/72438169/192729463-afe39f29-2cc3-419c-b5eb-443cd8402943.png)

Register Contracts to Deploy on Mainnet: List Code ID hiển thị Code ID "449"
![image](https://user-images.githubusercontent.com/72438169/192729777-04a7068b-6114-45aa-98c4-e952c35b1567.png)

**Trường hợp 02: Đăng ký type contract = "Incorrect"**

Type Smart Contract: Contract có Code ID = "449" đăng ký Type Contract = "Incorrect"
![image](https://user-images.githubusercontent.com/72438169/192730424-f3227da8-0888-4354-831a-344f5058170b.png)

Contracts List: Contract có Code ID = "449" và Type Contract = "-"
![image](https://user-images.githubusercontent.com/72438169/192730625-02674902-5aaf-4043-a3e8-3f5ed1ae4360.png)

Smart contracts list: Contract có Code ID = "449" và Type Contract = "-"
![image](https://user-images.githubusercontent.com/72438169/192730738-79e09b99-c833-406c-98e2-5c90a441696b.png)

Register Contracts to Deploy on Mainnet: List Code ID hiển thị Code ID "449"
![image](https://user-images.githubusercontent.com/72438169/192730986-ab87962f-b6c1-42c9-9f5e-eab3aeb61bfb.png)

**Trường hợp 03: Đăng ký type contract = "TBD"**

Type Smart Contract: Contract có Code ID = "449" đăng ký Type Contract = "TBD"
![image](https://user-images.githubusercontent.com/72438169/192731173-977be4ad-cf35-492e-9789-c49a3d6afdfc.png)

Contracts List: Contract có Code ID = "449" và Type Contract = "TBD"
![image](https://user-images.githubusercontent.com/72438169/192731349-f301fc2f-5950-461f-8af4-5473ed227c2c.png)

Smart contracts list: Contract có Code ID = "449" và Type Contract = "TBD"
![image](https://user-images.githubusercontent.com/72438169/192731677-083897c3-3ff3-4fca-bb60-90d0c97205fd.png)

Register Contracts to Deploy on Mainnet: List Code ID hiển thị Code ID "449"
![image](https://user-images.githubusercontent.com/72438169/192731773-fec3b942-d7f2-40fd-988c-3bc55a613467.png)

**Trường hợp 04: Đăng ký type contract = "Correct"**

Type Smart Contract: Contract có Code ID = "449" update Type Contract = "Correct"
![image](https://user-images.githubusercontent.com/72438169/192732270-8fe8f5cc-384c-4920-851f-b3bf2fb280cc.png)

Contracts List: Contract có Code ID = "449" và Type Contract = "CW-721"
![image](https://user-images.githubusercontent.com/72438169/192733201-3d1480c4-557e-42a0-93c2-094c0c3e2ab2.png)

Smart contracts list: Contract có Code ID = "449" và Type Contract = "CW-721"
![image](https://user-images.githubusercontent.com/72438169/192733367-e24310b0-71f9-4724-87ef-5b3ed3319eac.png)

Register Contracts to Deploy on Mainnet: List Code ID hiển thị Code ID "449"
![image](https://user-images.githubusercontent.com/72438169/192733457-6cc34ea2-7077-43a9-9abb-c7c8e890864b.png)
