### ISSUE TITLE
[Aurascan][FE][Statistics] Dựng front - end

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#1098]
- [x] ISSUE: Dựng Front- end chức năng Statistics

Link Figma: https://www.figma.com/file/xiW41QvCutlazTw9PSQC01/%5BAura%5D-Scan?node-id=2660%3A94749

**Comment by letrieuthien** [comment]
đã hoàn thành tất cả giao diện UI

**Comment by nhphuc2411** [comment]
https://taiga.aura.network/project/aurascan-2/us/10?milestone=13
