### ISSUE TITLE
[Aurascan][BlockDetail] Không hiển thị data transaction khi có Number of Tx = 1 

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#1099]
**Describe the bug**

- [ ] ISSUE: Block Details, không hiển thị data transaction khi có Number of Tx = 1 

Link: https://serenity.aurascan.io/blocks/4637332

**Screenshots**
![image](https://user-images.githubusercontent.com/72438169/193727761-674adeb9-027e-4f75-87c9-d4c1a4037583.png)

**Comment by fibonacci998** [comment]
There is a problem with seed node, so Horoscope cannot crawl this transaction
