### ISSUE TITLE
[Aurascan][TokenDetails][AccountDetails][NFTDetails] Not display image/video NFT with Token_uri has special characters

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1106]
**Describe the bug**
- [ ] Not display image/video NFT with link has special characters

**Precondition:**
- Mint NFTs with token_uri has special characters
- Token details link: 
https://serenity.aurascan.io/tokens/token-nft/aura15ydv0hjccrazv65cgdxu8dt7hcftmnk35s8f3erktrhflsu5lh9q2datge/ID03-Cat-30Sep2022-449%20Token%20CW721-atge
https://serenity.aurascan.io/tokens/token-nft/aura1qp5ef2ekj64spglqk9j29t7am9q3ew847n7qlanlrvxt4s587ctsv65lmx/MP4-filesamples.com-04Oct2022-466%20Token%20CW721
 
- MP4 link: https://filesamples.com/samples/video/mp4/sample_1280x720_surfing_with_audio.mp4
- Image link: https://www.freepnglogos.com/uploads/cat-png/brown-cat-download-image-12.png

**To Reproduce**
1. Check NFTs after minted at screens: Token Details, Account Details, NFT Details
2. Token Details (Inventory): https://serenity.aurascan.io/tokens/token-nft/aura1qp5ef2ekj64spglqk9j29t7am9q3ew847n7qlanlrvxt4s587ctsv65lmx 
3. Account Details: https://serenity.aurascan.io/account/aura1trqfuz89vxe745lmn2yfedt7d4xnpcpvltc86e
4. NFT Details: https://serenity.aurascan.io/tokens/token-nft/aura1qp5ef2ekj64spglqk9j29t7am9q3ew847n7qlanlrvxt4s587ctsv65lmx/MP4-filesamples.com-04Oct2022-466%20Token%20CW721
5. See error

**Expected behavior**
Display image/video NFT with Token_uri has special characters

**Screenshots**
![image](https://user-images.githubusercontent.com/24869170/193780796-1a87f6f7-9100-423d-b9d0-68842d86c101.png)
![image](https://user-images.githubusercontent.com/24869170/193781479-89032425-8034-44b4-bbd8-ffa8ec280ce4.png)
![image](https://user-images.githubusercontent.com/24869170/193782773-00879b25-1525-4208-bf51-f6852e6cb86d.png)

**Comment by ntatfff** [comment]
Verified FAIL on serenity (17/10/2022)
Not display image/video when upload image with special name via web3 UIR
Token details: 
- https://serenity.aurascan.io/tokens/token-nft/aura1n82lwhcxsjydm0j8du4ns72c2n9563ntvh4dfst0skdsc942qfhq5xt4y8/%23_logo-first-pic.svg%20-14Oct2022
![image](https://user-images.githubusercontent.com/24869170/196072844-0a58e313-d4eb-4c31-8b6b-a9a5d59218bb.png)

- https://serenity.aurascan.io/tokens/token-nft/aura1n82lwhcxsjydm0j8du4ns72c2n9563ntvh4dfst0skdsc942qfhq5xt4y8/giph%23%20y.gif-14Oct2022
![image](https://user-images.githubusercontent.com/24869170/196072944-677c233e-5869-4ea6-99fc-edb12dff00ac.png)

**Comment by nhphuc2411** [comment]
hiện tại token_uri không thể chứa ký tự đặc biệt
