### ISSUE TITLE
[Enhancement] Add pop up when do activities in Aura scan

### ISSUE THREAD

**Issue by Thaonguyen541** [aura-nw/aurascan#1108]
Need to add pop up after doing execute contract, when system is loading before response that transaction is success or fail.
Content of popup: 
"Transaction is in progress
 [Check your transaction on the explorer](https://euphoria.aurascan.io/transaction/)"

Activities need to be affected by this ehancement: 
+ Delegate/Undelegate/Redelegate/Undelegate
+ Claim Reward
+ Vote

Template for pop-up as an delegate example in keplr
![image](https://user-images.githubusercontent.com/79354422/193980272-ff3b2187-a0f8-49dc-9211-fda9194392d7.png)

**Comment by Dpthao245** [comment]
PASS in Serenitt 10/10/2022

Deletage

![Image](https://user-images.githubusercontent.com/72438169/194834236-da89e220-66e1-41e2-82a1-749e5d28fd19.png)

Undelegate

![Image](https://user-images.githubusercontent.com/72438169/194834483-3b5fd586-bbb3-4f5d-9807-c11eee3546f8.png)


Redelegate

![Image](https://user-images.githubusercontent.com/72438169/194834724-842a405a-d44c-49da-b6fd-76c94eec6a13.png)

**Comment by ntatfff** [comment]
Verified on Serenity (10/10/2022)
- Vote - list
![image](https://user-images.githubusercontent.com/24869170/194835039-24660ac5-01c6-416d-b17c-23618d6d612c.png)
- Vote - details
![image](https://user-images.githubusercontent.com/24869170/194835149-6c4824aa-6e81-4419-97f7-bb365a7e2005.png)

**Comment by Dpthao245** [comment]
PASS in Euphorua 11/10/2022
Delegate
![image](https://user-images.githubusercontent.com/72438169/195009557-3df8438c-68e1-4557-9370-eb8a0c2fd677.png)

Undelegate
![image](https://user-images.githubusercontent.com/72438169/195009638-0a041649-9805-43e7-bd49-22ec4fde4e36.png)

Redelegate
![image](https://user-images.githubusercontent.com/72438169/195009788-88e3ffca-e5d5-497d-b480-8c24ab67bac6.png)

Claim Reward
![image](https://user-images.githubusercontent.com/72438169/195009872-5a995492-b042-48d4-b6db-7cfa05b7341b.png)

Execute contract
![image](https://user-images.githubusercontent.com/72438169/195010498-027b5b03-42fd-42a4-8354-4b0b5c0245eb.png)
![image](https://user-images.githubusercontent.com/72438169/195010604-3cada155-dce8-4c60-8736-a6e198687eed.png)
