### ISSUE TITLE
[Aurascan][Transactions] Not display information of Unjail transaction

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1110]
**Describe the bug**
- [x] Not display information of Unjail transaction

**To Reproduce**
1. Go to Unjail transaction https://serenity.aurascan.io/transaction/FA59250ED54B4B6B559E3FE2ABC9E5912C98996F09B7D44A728308E4A4485FCD
2. See error

**Expected behavior**
Display information of Unjail transaction correctly
- Successs: https://www.mintscan.io/cosmos/txs/508A072C720FC2142F394E33D22D5531BB375F57F0BC92DDEDDC6DB8BA574466
- Fail: https://www.mintscan.io/cosmos/txs/0302352964492B7576000A7C9311378D2EB3C428BBA615154E6929CF124E134C
![image](https://user-images.githubusercontent.com/24869170/193999584-aa7c3740-cd77-42b9-a8d1-f02ed42e9ff6.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/24869170/193999130-5cc3a31f-abf4-4690-bdcc-faf672ebcd46.png)

**Comment by letrieuthien** [comment]
đã merge vào dev

**Comment by ntatfff** [comment]
Verified FAIL on serenity (07/10/2022)
Click on validator link: not navigate to validator details => wrong URL
![image](https://user-images.githubusercontent.com/24869170/194469538-21fda9a4-c191-495e-8432-cdbab4bfeb17.png)

**Comment by ntatfff** [comment]
Verified PASS on serenity (07/10/2022)
![image](https://user-images.githubusercontent.com/24869170/194495355-3c397998-9684-4fbe-b5fb-a9a9512e8ed1.png)
![image](https://user-images.githubusercontent.com/24869170/194495381-aecb9d1d-4670-4384-b586-edbf274bfe46.png)
