### ISSUE TITLE
[Aurascan] Support search with contract address in the general search field

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1127]
**Description an issue**
Input a contract address in the search field (general search) => navigate to account details page

**To Reproduce**
1. Go to https://euphoria.aurascan.io/
2. Input an address value at search field "aura1vuyynwewauj6usl0lpx5t6ps67mqfzsmtrepxphg4a0w3clzzxnquyul3q"
3. Enter

**Expected behavior**
- [ ] Input a contract address in the search field (general search) => navigate to contract details screen
- [ ] Search priority:  contract address > block height > tx hash > account address

**Screenshots**
![image](https://user-images.githubusercontent.com/24869170/194535938-ed043a7a-546d-4fd8-92ff-cab5f3d12d8a.png)
issue
![image](https://user-images.githubusercontent.com/24869170/194536050-5dfd7588-1fdb-4a9f-bf95-541c6c72146a.png)

**Comment by letrieuthien** [comment]
done trên dev

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (11/10/2022)
Contract 
![image](https://user-images.githubusercontent.com/24869170/195073451-6474915d-cb95-4d9a-8e10-7b356c32ad84.png)
![image](https://user-images.githubusercontent.com/24869170/195073491-8408566d-ef31-4ea9-bcb9-a5aa92f9c3bc.png)

Address
![image](https://user-images.githubusercontent.com/24869170/195073558-8c0dd616-4e98-4846-bb9a-656e4e5f01ea.png)
![image](https://user-images.githubusercontent.com/24869170/195073600-76381b43-7d0c-48e8-b242-66af58848b7a.png)

Height
![image](https://user-images.githubusercontent.com/24869170/195073699-22550505-7cb3-4ad6-aeee-29c0b170cc8f.png)
![image](https://user-images.githubusercontent.com/24869170/195073734-d825dedd-6a7d-43ec-8cd1-191e937fdc00.png)
