### ISSUE TITLE
[Aurascan][AccountDetails] Cannot open link of Token ID has special characters

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1130]
**Describe the bug**
- [x] Cannot open link of Token ID has special characters

**Precondition:** Mint an NFT that Token ID has special characters (name: 5-MP4-Mirror#2-4Stars-109)

**To Reproduce**
1. Go to Account details https://euphoria.aurascan.io/account/aura1trqfuz89vxe745lmn2yfedt7d4xnpcpvltc86e
2. Click on an NFT under test (name: 5-MP4-Mirror#2-4Stars-109)
3. See error

**Expected behavior**
Can open link of Token ID has special characters, navigate to Token details screen

**Screenshots**
![image](https://user-images.githubusercontent.com/24869170/194795945-5a2db1df-4de6-4789-b551-85e56abb4ef3.png)

**Comment by ntatfff** [comment]
Verified PASS on serenity (10/10/2022)
Name list:
- !@GIF-Mirror#2-4Stars109$%
- !@MP4-Mirror#2-4Stars109$%
- 5-MP4-Mirror#2-4Stars-109#
- 5-MP4-Mirror#2-4Stars-109
- 5-MP4-Mirror#2
![image](https://user-images.githubusercontent.com/24869170/194845577-d527fe14-48d8-40f9-9b14-934d60e4518e.png)
![image](https://user-images.githubusercontent.com/24869170/194845165-8cf760e6-5b7a-480f-a0d6-9eef72ff2be5.png)
![image](https://user-images.githubusercontent.com/24869170/194845299-c41b50b1-ceba-4df3-82a7-891962771dcb.png)

**Comment by Dpthao245** [comment]
PASS in Euphoria 19/10/2022
![image](https://user-images.githubusercontent.com/72438169/196625529-6f0c12df-ef80-49ac-aac4-06571e99f98e.png)
![image](https://user-images.githubusercontent.com/72438169/196625612-60ceeb02-bf55-4653-9461-e72f5d0ad13a.png)
![image](https://user-images.githubusercontent.com/72438169/196626060-2503743c-550c-44ad-92b9-a7157ecabe2b.png)
![image](https://user-images.githubusercontent.com/72438169/196626628-97f940e5-4820-4fc9-8bef-6d3f94d3c306.png)
![image](https://user-images.githubusercontent.com/72438169/196627570-1fb1c14e-837e-4c57-8e59-d1c0d78aacb2.png)
