### ISSUE TITLE
[Aurascan][TokenDetails] Fix api support uri encode + special character

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#1146]
**Describe the bug**

- [ ] ISSUE: Fix api support uri encode + special character

Link: https://explorer.dev.aura.network/tokens/token-nft/aura1206t3say4u6p5dnwpagzjz77qmt0uyx2dsew4sncm9j7w7lxjjxs4xheh9
Click View NFT -> Màn hình NFT Detail không hiển thị dữ liệu

**Screenshots**
![image](https://user-images.githubusercontent.com/72438169/194989682-24f0c3f5-f69a-445f-b8b7-8dbff900b238.png)
![image](https://user-images.githubusercontent.com/72438169/194989744-07b6248c-f24a-4a33-a676-d28e7c55b6c3.png)

**Comment by tamvb2391** [comment]
Hi @fibonacci998 , Please help me take a look this issue, 
It has no data when call api "/api/v1/cw721-tokens/aura1206t3say4u6p5dnwpagzjz77qmt0uyx2dsew4sncm9j7w7lxjjxs4xheh9/nft/%E2%95%B0%E2%80%BF%E2%95%AF"
It seem missing data in cw721_asset table

**Comment by fibonacci998** [comment]
> aura1206t3say4u6p5dnwpagzjz77qmt0uyx2dsew4sncm9j7w7lxjjxs4xheh9

Hi @Dpthao245, plus symbol in url is special
[stackoverflow](https://stackoverflow.com/questions/5450190/how-to-encode-the-plus-symbol-in-a-url#:~:text=If%20you%20want%20a%20plus,to%20encode%20it%20as%202B%20.&text=Literally%20as%20%2B%20%3F&text=Yes%2C%20%2B%20is%20what%20you%20want!)
So that url must be encode before call indexer

**Comment by Dpthao245** [comment]
PASS in Serenity 11/11/2022


![Image](https://user-images.githubusercontent.com/72438169/201286364-8a20f3ae-e689-43f7-853b-f358bdd78293.png)

![Image](https://user-images.githubusercontent.com/72438169/201286630-e4ccad2a-ba3e-4150-b31b-32d4f4e195c5.png)
