### ISSUE TITLE
[MenuHeader] Update new header

### ISSUE THREAD

**Issue by NgocAnh7278** [aura-nw/aurascan#1147]
Document:https://www.notion.so/aura-network/MenuHeader-Update-menu-header-032612be6e8d4bddb48f689dae624712
Figma: https://www.figma.com/file/xiW41QvCutlazTw9PSQC01/%5BAura%5D-Scan?node-id=3326%3A131536

**Comment by Dpthao245** [comment]
FAIL: Serenity 14/10/2022

- [ ] ISSUE: Sai font size 16px -> 14px


![Image](https://user-images.githubusercontent.com/72438169/195761645-d77ea017-9e58-4150-8c39-7d6febd1ea46.png)

![Image](https://user-images.githubusercontent.com/72438169/195761738-0bc9f5dc-420a-49bd-ab5e-b7e4579a8156.png)

**Comment by hangpham23** [comment]
- [ ] Menu căn lề trái

![Screen Shot 2022-10-14 at 15 34 14](https://user-images.githubusercontent.com/102220123/195805838-eda50164-b053-4904-9929-c663edac48ee.png)
![Screen Shot 2022-10-14 at 15 52 21](https://user-images.githubusercontent.com/102220123/195805848-c17fca77-861d-4d92-b63a-4b7b92eccc7a.png)

**Comment by Dpthao245** [comment]
PASS in Serrenity 17/10/2022

![Image](https://user-images.githubusercontent.com/72438169/196069258-25e42a4a-027c-482c-9e7c-73f9cccdbf57.png)

![Image](https://user-images.githubusercontent.com/72438169/196069281-5e81ff06-38d8-40d9-aeed-109bafc7190b.png)

![Image](https://user-images.githubusercontent.com/72438169/196069312-fc91c300-92ee-4fb0-a80f-2156f1feee4d.png)

**Comment by Dpthao245** [comment]
PASS in Serenity 17/10/2022
Desktop
![image](https://user-images.githubusercontent.com/72438169/196102728-6e0945a7-2801-4123-a26d-954439b25d16.png)
![image](https://user-images.githubusercontent.com/72438169/196102758-9a58a4b7-d9df-47ff-816b-78882e713151.png)
![image](https://user-images.githubusercontent.com/72438169/196102784-44709483-7443-4bd3-9458-154b034fd6bf.png)

Mobile
![image](https://user-images.githubusercontent.com/72438169/196103201-e81f06e9-ff15-4d70-b4e4-4960d8179a45.png)
![image](https://user-images.githubusercontent.com/72438169/196103272-65913c28-7363-461f-94ab-ffff0403224b.png)
![image](https://user-images.githubusercontent.com/72438169/196103322-e62d457d-cc63-44a6-9256-eecfc454d338.png)
![image](https://user-images.githubusercontent.com/72438169/196103356-a0c49f5b-0001-42f2-b487-27371105e7dc.png)

**Comment by Dpthao245** [comment]
PASS in Euphoria 19/10/2022
Desktop
![image](https://user-images.githubusercontent.com/72438169/196595577-538dc61a-12ab-4361-acd1-bfbfba224e15.png)
![image](https://user-images.githubusercontent.com/72438169/196595669-ba256669-912c-497e-825e-daff05508d5b.png)
![image](https://user-images.githubusercontent.com/72438169/196595686-8c55194a-6c95-4ae7-936b-278cbea6cbf4.png)

Mobile
![image](https://user-images.githubusercontent.com/72438169/196595754-040f8bae-87b9-489f-8bc3-e337f83a3cd1.png)
![image](https://user-images.githubusercontent.com/72438169/196595787-153c8307-8350-46cf-923d-dffbdb780a03.png)
![image](https://user-images.githubusercontent.com/72438169/196595827-628b12e0-9c85-4753-b65f-c83164aec12e.png)
