### ISSUE TITLE
[Aurascan][AccountDetails][Redelegation] Not display Redelegations data at stake tab

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1149]
**Describe the bug**
- [ ] Not display Redelegations data at stake tab

Precondition:
Do a Redelegate transaction

**To Reproduce**
1. Go to https://euphoria.aurascan.io/account/aura1trqfuz89vxe745lmn2yfedt7d4xnpcpvltc86e
2. Click on STAKE tab
3. Click on REDELEGATIONS tab

**Expected behavior**
Display Redelegations data at stake tab correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/24869170/194992805-c05e97f5-e9d3-4eb0-8f2c-d832258e82fd.png)

**Comment by ntatfff** [comment]
Verified PASS on serenity (12/10/2022)
![Image](https://user-images.githubusercontent.com/24869170/195247898-577755f2-f9b4-4cb0-b2a5-c54033a25a9f.png)

**Comment by Dpthao245** [comment]
PASS in Euphoria 19/10/2022


![Image](https://user-images.githubusercontent.com/72438169/196596491-117c0a3c-9969-4e02-a024-96c6ad661782.png)

![Image](https://user-images.githubusercontent.com/72438169/196596522-2e3103ab-c640-41f2-b6cd-fdb80bce4865.png)

![Image](https://user-images.githubusercontent.com/72438169/196596580-3ddafc44-11eb-427d-9d7e-6ff817419ee6.png)
