### ISSUE TITLE
[Aurascan][AccountDetails] Cannot open NFT details after clicking Token ID link

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1151]
**Describe the bug**
- [x] Cannot open NFT details after clicking Token ID link

**To Reproduce**
1. Go to https://euphoria.aurascan.io/account/aura1trqfuz89vxe745lmn2yfedt7d4xnpcpvltc86e
2. Click on Token ID link of NFT "`MP4 11-Oct-2022"
3. See error

**Expected behavior**
Can open NFT details page

**Screenshots**
![image](https://user-images.githubusercontent.com/24869170/195017607-884b2eab-f2a5-403e-b136-d3d043bbbecb.png)
![image](https://user-images.githubusercontent.com/24869170/195017632-6dad154a-00c8-4d8c-ad86-64f3a273197c.png)

**Comment by letrieuthien** [comment]
done ở dev

**Comment by ntatfff** [comment]
Verified PASS on serenity (12/10/2022)
![image](https://user-images.githubusercontent.com/24869170/195305870-1dd31efb-1d2d-4575-8588-02752c37e545.png)
![image](https://user-images.githubusercontent.com/24869170/195305902-81d1949e-9899-44dc-b3dc-5dd520cf6063.png)

**Comment by Dpthao245** [comment]
PASS in Euphoria 19/10/2022
![image](https://user-images.githubusercontent.com/72438169/196596852-f621e078-6fca-41fa-bca2-f3d936668ac0.png)
![image](https://user-images.githubusercontent.com/72438169/196596882-d3f7df42-e2e7-454e-b3b5-98bde2556b7b.png)
