### ISSUE TITLE
[Aurascan][AccountDetails] Not display Token name of NFTs from 6th page

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1155]
**Describe the bug**
- [x] Not display Token name of NFTs from 6th page

**To Reproduce**
1. Go to https://euphoria.aurascan.io/account/aura1trqfuz89vxe745lmn2yfedt7d4xnpcpvltc86e
2. At NFT assets, click on the 6th page
3. Check displaying Token name of NFTs

**Expected behavior**
Display Token name of NFTs correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/24869170/195055830-03404db1-4f38-42f7-9e21-30da59e9b6d5.png)

**Comment by ntatfff** [comment]
Verified PASS on serenity (12/10/2022)
![image](https://user-images.githubusercontent.com/24869170/195272749-558c57e6-6b9e-4bb0-ba5b-b6ee6c7eb0c6.png)

**Comment by Dpthao245** [comment]
PASS in Euphoria 19/10/2022


![Image](https://user-images.githubusercontent.com/72438169/196597266-64c1b889-27f2-4f1c-a747-222aa0a864b9.png)

![Image](https://user-images.githubusercontent.com/72438169/196597291-3301b474-ea80-49c0-bc36-559fd245bd8b.png)

![Image](https://user-images.githubusercontent.com/72438169/196597337-19bf7cf4-852e-482d-bad7-025d8929e2e3.png)
