### ISSUE TITLE
[Aurascan][ContractOnMainnet] Project details

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1162]
https://github.com/aura-nw/aurascan/issues/1118
- [x] Add an API to support view Project details

**Comment by thanhhao1986** [comment]
@letrieuthien  BE đã sửa api xong, em ráp cho FE nhé

**Comment by letrieuthien** [comment]
FE đã xong trên dev

**Comment by Dpthao245** [comment]
PASS in Serenity 19/10/2022


![Image](https://user-images.githubusercontent.com/72438169/196650876-d4dfd9ed-e0a1-410f-88df-e516ac10184e.png)

![Image](https://user-images.githubusercontent.com/72438169/196651059-c6a8a0f3-819a-4cee-b4db-1a9aa32e086d.png)

![Image](https://user-images.githubusercontent.com/72438169/196651194-45c41689-bb69-459b-9d56-0dc0476a790a.png)

![Image](https://user-images.githubusercontent.com/72438169/196651251-8f6a6c7e-6c38-4778-80b7-168dda22b848.png)

![Image](https://user-images.githubusercontent.com/72438169/196651336-74465787-baa2-47e5-932f-264b93fb2337.png)

![Image](https://user-images.githubusercontent.com/72438169/196651477-d665d649-2767-40ae-ad5a-16b740900fa9.png)

![Image](https://user-images.githubusercontent.com/72438169/196651625-9a377efb-dcf6-4c25-9c76-e7baa13b4020.png)
