### ISSUE TITLE
[Aurascan][Coin98][Mobile] Issue connect Coin98

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#1163]
Describe the bug

- [x] ISSUE 01: Hiển thị lỗi khi thực hiện các giao dịch ở menu Validators, Voting
![image](https://user-images.githubusercontent.com/72438169/195269661-38865a90-773f-4b5f-ae18-6ec2b5d2aeef.png)

- [x] ISSUE 02: Update text connect ví
Content "Connect with one wallet provider or create a new one"

**Screenshots**
![image](https://user-images.githubusercontent.com/72438169/195269277-c4976507-f1f1-414e-9a7c-e0817403bd3b.png)

- [x] ISSUE 03: Hiển thị message khi click nút Hủy connect ví C98 từ App C98

Mobile: IOS -Safari, Android - Chorme

**Screenshots**
![image](https://user-images.githubusercontent.com/72438169/195268246-db389659-a826-43dc-8ccb-0b2b5ed83182.png)
![image](https://user-images.githubusercontent.com/72438169/195267851-3cdcc0b5-77fb-47a9-8f82-322ca3d6fa9b.png)

- [ ] ISSUE 04: Hiển thị message lỗi khi đã click nút Hủy connect C98
Mobile: IOS - Safari

![image](https://user-images.githubusercontent.com/72438169/195268469-649963d7-f384-48b8-a9a2-bd5c6fc7c9f5.png)
![image](https://user-images.githubusercontent.com/72438169/195268789-e1901fc6-4a35-4967-b8c1-5ce8db4b34ef.png)

**Comment by nttnguyen136** [comment]
ISSUE 02: Update text connect ví -> Đã confirm với BA chưa?
ISSUE 04: Thao tác sai

**Comment by Dpthao245** [comment]
**_ISSUE 02: Update text connect ví -> Đã confirm với BA chưa?_**
**Đã confirm với BA nên mới log issue**
![image](https://user-images.githubusercontent.com/72438169/195485675-f62ad9da-aca8-45d8-b0c8-f8ba1fe5329f.png)

**Comment by Dpthao245** [comment]
- [ ] ISSUE 05: Mobile không hiển thị message lỗi khi thực hiện Redelegate
![image](https://user-images.githubusercontent.com/72438169/195486924-77a92801-993c-4c5a-88eb-61da12387a1c.png)

**Comment by hangpham23** [comment]
ISSUE 06: Hiển thị timeout _ Verified: PASS
