### ISSUE TITLE
[Aurascan] My account loading process UX enhancement

### ISSUE THREAD

**Issue by Thaonguyen541** [aura-nw/aurascan#1165]
Trên trang "my account", thêm icon loading cạnh những data cần truy vấn dữ liệu từ db để hiển thị lên 
- Case 1: Dữ liệu account đã có trong db indexer -> khi này thì indexer sẽ trả về aurascan và FE sẽ hiển thị ra --> chỉ cần hiển thị icon loading bình thường
- Case 2: Dữ liệu account chưa có trong db indexer -> khi này indexer sẽ bắt đầu crawl data từ network và trả cho aurascan --> Cạnh icon loading thêm dòng text "Fetching data, might take longer than usual. Please wait or refresh the page"
*)Note: Chỉ hiển thị text với những biểu tượng loading to ở vị trí có list view, còn những vị trí loading nhỏ cạnh data số thì không cần hiển thị text

1. In "Assets" tab:
![Loading processing in my account-Assets drawio (5)](https://user-images.githubusercontent.com/79354422/195315336-c48766da-bf40-4011-8536-6630a6e3773c.png)

2. In "Transactions" tab:
![Loading processing in my account-Transactions drawio (4)](https://user-images.githubusercontent.com/79354422/195315472-555431a9-ccdc-46a5-ba12-4f3f17ebefde.png)

3. In "Stake" tab
![Loading processing in my account-Stake drawio (5)](https://user-images.githubusercontent.com/79354422/195315583-e794967d-e426-4cdf-bcc6-1e6de72eeace.png)

**Comment by ntatfff** [comment]
Verified PASS on local dev (24/10/2022)
![image](https://user-images.githubusercontent.com/24869170/197467281-7b9e0733-328e-47d8-a523-676f8bc86757.png)
![image](https://user-images.githubusercontent.com/24869170/197467330-a65160f7-8a38-49b5-93d9-6313b5ef5602.png)
![image](https://user-images.githubusercontent.com/24869170/197467362-d4c069e5-8309-42b1-a03c-f673e881ada4.png)

**Comment by ntatfff** [comment]
Verified PASS on local dev (25/10/2022)
![image](https://user-images.githubusercontent.com/24869170/197703306-4404ea1d-e740-49bf-82a3-40e9f8fff782.png)
![image](https://user-images.githubusercontent.com/24869170/197703339-e0ea291a-0ed7-4f36-b2a1-7b5ea97d57f8.png)
![image](https://user-images.githubusercontent.com/24869170/197703377-60a3f28b-969d-4a77-b337-39220aa70cae.png)
