### ISSUE TITLE
[Aurascan][ContractDetails][TokenDetails] Display incorrect data when record number > 100

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1166]
**Bug description**
Display incorrect data when record number > 100
1/ Contract Details: 
dev link: https://explorer.dev.aura.network/contracts/aura1206t3say4u6p5dnwpagzjz77qmt0uyx2dsew4sncm9j7w7lxjjxs4xheh9
serenity link: https://serenity.aurascan.io/tokens/token-nft/aura1d32dfs4m6l8y75l2yqnxwlz7xnnnx6xnss2mvzgexaq8snhsx0js7w8wq4
euphoria link: https://euphoria.aurascan.io/tokens/token-nft/aura1cqrvv2a58s2hyd2ktuhl3exwygtf8xmncmtpj2n42gna4mr5euvspfez0j
- [x] Transfers tab: Display wrong counting number
- [x] Transfers tab > View All/View Outgoing/View Ingoing > Click page 6: Display wrong information, display only 1 record

2/ Token Details:
- [x] Transactions tab: display wrong paging after clicking from page 5th
- [x] Transactions tab: display wrong counting number after clicking on other pages
- [x] Transactions tab: not display data after clicking from page 4th

**Comment by ntatfff** [comment]
Verified PASS on serenity (13/10/2022)
1/ Contract details
- Transfer tab:
![image](https://user-images.githubusercontent.com/24869170/195544597-2568bf93-50be-453a-ae8a-6be09bfad08c.png)

- Transfer tab: view all
![image](https://user-images.githubusercontent.com/24869170/195544757-2f78d1b9-293f-46ef-b824-de7c8279eacd.png)
Page 5th
![image](https://user-images.githubusercontent.com/24869170/195544918-edafa454-6d50-4a88-9388-f7931ccad61c.png)
Page 10th
![image](https://user-images.githubusercontent.com/24869170/195545012-42e6da2b-03d1-4acc-9801-c190239cb326.png)
Last page
![image](https://user-images.githubusercontent.com/24869170/195545121-8223f204-c879-463d-90f8-04348994280e.png)

- Transfer tab: view Ingoing all
![image](https://user-images.githubusercontent.com/24869170/195547272-f41e942d-791f-407f-8a46-a2506d9b76fe.png)
![image](https://user-images.githubusercontent.com/24869170/195547322-c172b970-d3b0-4ae3-aa98-57f7a1dd1aca.png)

2/ Token Details:
- Transactions tab: page 5th
![image](https://user-images.githubusercontent.com/24869170/195547594-d26d7ca2-b8a2-4577-9851-5136749960be.png)
![image](https://user-images.githubusercontent.com/24869170/195547647-0404b7a2-9f9c-4be7-93cf-599d905afd4a.png)
- Transactions tab: counting number
![image](https://user-images.githubusercontent.com/24869170/195547845-161e11e4-929f-4b7a-b54e-c3a445626c01.png)
- Transactions tab: Display data all pages
![image](https://user-images.githubusercontent.com/24869170/195548088-b9cfa326-5e52-4830-9174-c16c75a933fe.png)

**Comment by Dpthao245** [comment]
**PASS in Euphoria 19/10/2022**
**1/ Contract details**

**Transaction tab**

![Image](https://user-images.githubusercontent.com/72438169/196613171-e4fa4ee8-ffdc-4241-b63c-63c5b9652127.png)

**View all Transactions**

![Image](https://user-images.githubusercontent.com/72438169/196613331-2429e1af-bb86-4505-8cde-790bb26d7626.png)

**Page 5th**

![Image](https://user-images.githubusercontent.com/72438169/196613502-a3fa1424-ebee-4021-b776-dbb09d8f1e5d.png)

![Image](https://user-images.githubusercontent.com/72438169/196613540-f6b708ed-0327-4729-9008-9333dc78937f.png)

**Last page**

![Image](https://user-images.githubusercontent.com/72438169/196613638-d245be4f-9240-4a96-a1f5-7af86ebd4bba.png)

![Image](https://user-images.githubusercontent.com/72438169/196613697-0763c3d7-bd4f-4e76-af3c-5de0e5b9b29c.png)

**2/ Token details**

**Transfer tab**

![Image](https://user-images.githubusercontent.com/72438169/196613938-82dc01b0-aa78-4c45-a8d5-6f11a02dbb53.png)

![Image](https://user-images.githubusercontent.com/72438169/196613968-33b8f91c-6a20-4b4c-95fd-667d4e7653c5.png)

**Page 5th**

![Image](https://user-images.githubusercontent.com/72438169/196614025-218f59f2-a83f-4cf0-9c74-e4560b1b1b12.png)

![Image](https://user-images.githubusercontent.com/72438169/196614086-063e1863-42f3-4e9c-b5d3-7dad99fb8b1b.png)

**Last page**

![Image](https://user-images.githubusercontent.com/72438169/196614154-01cf5108-9f20-4e36-93b4-55d823cd0570.png)

![Image](https://user-images.githubusercontent.com/72438169/196614195-5c18cb3a-e0b6-4d8b-9b1b-b06496a7c2c5.png)
