### ISSUE TITLE
[Aurascan][TokenDetails] Display incorrect Transfers number when > 100

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1168]
**Bug description**
- [x] Display incorrect Transfers number when > 100

Token details link: https://serenity.aurascan.io/tokens/token-nft/aura1d32dfs4m6l8y75l2yqnxwlz7xnnnx6xnss2mvzgexaq8snhsx0js7w8wq4

**Expected result:** Display total transfer number after opening token details screen
**Actual result:** Display transfer number = 100, after clicking on page 6th, transfer number is updated
![image](https://user-images.githubusercontent.com/24869170/195509362-9ff5229f-7e0e-4576-ba56-1f6536221da1.png)

**Comment by fibonacci998** [comment]
currently horoscope api cannot count exactly number of transactions, the count value return is a number that support for pagination only

**Comment by ntatfff** [comment]
Verified PASS on serenity (15/11/2022)
![image](https://user-images.githubusercontent.com/24869170/201839370-2c129117-df5a-469b-b2e2-1ed0bd7744ea.png)

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (26/12/2022)
![image](https://user-images.githubusercontent.com/24869170/209535341-31fba566-bdb9-47b6-9dba-3bdb648f85a2.png)
