### ISSUE TITLE
[Aurascan][Dashboard][Transaction] Get exported transaction numbers with local timezone

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1172]
**Describe the bug**
Exported transaction numbers incorrectly
- Last 24h: get with local time
- Last month: get with UTC timezone
- Last year: get with UTC timezone

**To Reproduce**
1. Go to Dashboard https://serenity.aurascan.io/dashboard
2. Download CSV file of Transactions: 24h, 30d, 12M
3. Compare number transaction of last day, last month

**Expected behavior**
Exported transaction numbers correctly - get with local timezone

**Comment by ntatfff** [comment]
chờ sync data xong để check

**Comment by ntatfff** [comment]
Verified on serenity (18/10/2022)
- FAIL: Số lượng transactions (12 tháng) - UTC+7: chưa cộng vào ngày hiện tại
![image](https://user-images.githubusercontent.com/24869170/196331923-7d58df20-006b-4613-834c-450887954577.png)

- Note: Số lượng transactions (12 tháng) - UTC+0: đã cộng vào ngày hiện tại
![image](https://user-images.githubusercontent.com/24869170/196332098-b0dbdc54-1bba-4806-97b6-c482ae95399c.png)

**Comment by sonhv** [comment]
fixed

**Comment by ntatfff** [comment]
Verified PASS on serenity (21/10/2022)
- UTC+7
![image](https://user-images.githubusercontent.com/24869170/197111822-ae15090f-0c29-4303-ad6e-58a3e04095c3.png)
- UTC+0
![image](https://user-images.githubusercontent.com/24869170/197112168-2e9ed955-cae3-496a-8979-a359b9d8a710.png)
- UTC-2
![image](https://user-images.githubusercontent.com/24869170/197112323-c1e8bc5b-bce7-450e-94d4-73060f4f49d9.png)
- UTC-5
![image](https://user-images.githubusercontent.com/24869170/197112513-c75d78b8-2465-40b5-a507-1eaabe143038.png)

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (27/10/2022)
UTC+0
![image](https://user-images.githubusercontent.com/24869170/198255716-b2077f6b-016b-4ed7-b1d9-4d7d43a83dd0.png)
UTC+7
![image](https://user-images.githubusercontent.com/24869170/198255764-f2a86a6e-da4b-4785-bdfd-f640e7be2247.png)
