### ISSUE TITLE
[Aurascan][Validators] Count Participation number incorrectly

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1173]
**Bug description**
- [ ] Count Participation number incorrectly

**Precondition**
Current total proposal number = 40
Number of proposal that Validator has voted = 8

Steps
1. Go to https://serenity.aurascan.io/validators
2. Check Participation number
3. See error

**Expected result:** Participation number is 8 / 40
**Actual result:** Participation number is 8 / 33
![image](https://user-images.githubusercontent.com/24869170/195762510-c3adc7e8-f957-453f-bdf0-ae7ebad42246.png)
![image](https://user-images.githubusercontent.com/24869170/195762543-9855b034-8e8d-448f-8a8f-fa6e9df715ae.png)

**Comment by ntatfff** [comment]
Verified PASS on serenity (14/10/2022)
![image](https://user-images.githubusercontent.com/24869170/195814160-3dc7d777-c56a-4f1b-9ea5-acaf6ff7e409.png)
![image](https://user-images.githubusercontent.com/24869170/195814352-24c8ed68-79df-412a-a69c-f161a66c2253.png)

**Comment by Dpthao245** [comment]
PASS in Euphoria 19/10/2022


![Image](https://user-images.githubusercontent.com/72438169/196611192-1125b0ac-abd1-48b7-a9ab-87b3b1f7e8f0.png)


![Image](https://user-images.githubusercontent.com/72438169/196611259-1f3b3773-4858-451c-94f1-a27cb296dd2e.png)



![Image](https://user-images.githubusercontent.com/72438169/196611378-09433008-b662-404e-a42b-e33db5c72d21.png)



![Image](https://user-images.githubusercontent.com/72438169/196611543-0dabd1b7-8800-481d-9002-5aaafa689fe8.png)



![Image](https://user-images.githubusercontent.com/72438169/196611575-6ea69dfb-9a72-425f-863f-67acd54a66e2.png)
