### ISSUE TITLE
[Aurascan][Transactions][ExecuteContract] Missing "Transaction is in processing" popup after executing contract

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1175]
**Bug description**
- [x] Not display "Transaction is in processing" popup after executing contract

**Step:**
1. Connected wallet
2. Go to Contract details/ Token details
3. Write contract

**Expected result:** Display "Transaction is in processing" popup after executing contract
![image](https://user-images.githubusercontent.com/24869170/195799437-932ac4ee-498d-4fed-847c-a9bd2cb99c7f.png)

**Comment by ntatfff** [comment]
Verified PASS on serenity (17/10/2022)
![image](https://user-images.githubusercontent.com/24869170/196113323-c4a43977-e6f5-448b-b5ee-5aab4152e202.png)
![image](https://user-images.githubusercontent.com/24869170/196114999-8dc823fa-0ee4-404e-9080-f782da221ec6.png)

**Comment by Dpthao245** [comment]
PASS in Euphoria 19/10/2022
![image](https://user-images.githubusercontent.com/72438169/196626188-431dc509-8771-4b98-8e3b-0454cf088af6.png)
![image](https://user-images.githubusercontent.com/72438169/196629441-49cca96a-e81f-4199-899e-871bd72da09d.png)
