### ISSUE TITLE
[NFTDetails] Update nft name when nfts have name

### ISSUE THREAD

**Issue by NgocAnh7278** [aura-nw/aurascan#1193]
- If NFTs have a name: update token name + token ID => NFT name (twilight nfts always have a name, check them)

![image](https://user-images.githubusercontent.com/40628286/196632646-74571e8a-d8e9-4d60-be5f-dd53e8be893a.png)

- If NFTs do not have a name: token name + token ID

**Comment by Dpthao245** [comment]
Hiện tại Twilight chưa có môi trường Euphoria để check ticket này.
