### ISSUE TITLE
[Aurascan] Update API token CW20

### ISSUE THREAD

**Issue by nhphuc2411** [aura-nw/aurascan#1194]

**Comment by nhphuc2411** [comment]
Meeting note 02/11/2022:
+ Account detail: Tuấn cập nhật api trên indexer cho phép search theo name và address(Không search like).
+ List token CW20:
    - Holder: Tuấn bổ sung thêm api trên Indexer để tính gía trị holder thay đổi trong 24h.
    - Sẽ lưu thông tin price, volume, holder... vào db MySql. Dùng Queue để sync data từ coingecko.

**Comment by ntatfff** [comment]
Testing on serenity (18/11/2022)
Created issue: https://github.com/aura-nw/aurascan/issues/1283

**Comment by ntatfff** [comment]
Tested on serenity (28/11/2022)
Created issues:
https://github.com/aura-nw/aurascan/issues/1304
https://github.com/aura-nw/aurascan/issues/1300
https://github.com/aura-nw/aurascan/issues/1284
https://github.com/aura-nw/aurascan/issues/1300
https://github.com/aura-nw/aurascan/issues/1301
https://github.com/aura-nw/aurascan/issues/1303
