### ISSUE TITLE
[Aurascan][Validators][Euphoria] Hiển thị sai số  PARTICIPATION

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#1200]
- [ ] ISSUE: Validator SerGo hiển thị PARTICIPATION là 391/9

**Steps**

1. Go to https://euphoria.aurascan.io/validators
2. Check Participation number
3. See error

**Actual result:** Participation number is 391/9
**Expected result:** Participation number is 0/9

![image](https://user-images.githubusercontent.com/72438169/196852145-964252c9-8308-4572-be45-c9986eb85d81.png)

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (25/10/2022)
![image](https://user-images.githubusercontent.com/24869170/197717195-36b88330-09e8-4b10-9888-324b1ce50878.png)
![image](https://user-images.githubusercontent.com/24869170/197717254-93b83adf-d94b-4798-99cf-bf1bf9e89244.png)
![image](https://user-images.githubusercontent.com/24869170/197717295-a5963e6f-7b58-442e-a2be-2503fd42c994.png)
