### ISSUE TITLE
[Aurascan][Coin98][Mobile] Không hiển thị message lỗi khi thực hiện Redelegate

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#1208]
- [ ] ISSUE: Không hiển thị message lỗi khi thực hiện Redelegate

Expected behavior

![image](https://user-images.githubusercontent.com/72438169/197448553-f7781759-5810-4851-957e-7f2ccfd2459d.png)

**Comment by Dpthao245** [comment]
PASS in Serenity 24/10/2022

Desktop

Message lỗi khi thực hiện Redelegate

![Image](https://user-images.githubusercontent.com/72438169/197501504-3ed28e03-d409-4117-934c-9c97c4573993.png)


Message lỗi khi không đủ fee gas


![Image](https://user-images.githubusercontent.com/72438169/197501591-5d3d5db6-0504-418d-ac11-1ccdf4a80fdb.png)

**Comment by Dpthao245** [comment]
FAIL in Serenity 24/10/2022
Mobile: khi thực hiện các giao dịch ở màn hình Validator


![Image](https://user-images.githubusercontent.com/72438169/197503577-d76fe0ac-aec8-4a9c-aaed-5f92665b5d60.png)

**Comment by Dpthao245** [comment]
**PASS in Serenity 04/11/2022**

**App Coin 98 Ver 12.6.2**
![694CA0BF-B167-474A-9E7F-42FF0C3D1E74](https://user-images.githubusercontent.com/72438169/199928833-2b22b09d-ee8f-4569-95f3-89c3a2057951.png)

**Serenity.aurascan.io**
Vote
![A1BFE2C6-5646-4741-801C-9363BB57C4DB](https://user-images.githubusercontent.com/72438169/199928995-a2d7058a-62cf-46a8-ac52-d2f04155b036.png)
![DFD05817-3EA5-4F62-A604-3E2C1262BACB](https://user-images.githubusercontent.com/72438169/199929033-b61028f8-33d2-4675-9a49-6039182669c8.png)

Cliam Reward
![811CC2E5-42EB-4501-AE37-E22EFDEDD4D5](https://user-images.githubusercontent.com/72438169/199929094-2c8d954a-3681-45fa-a35a-991839eb1bfd.png)
![269C35B1-8C24-4C36-9085-4C0C8921288B](https://user-images.githubusercontent.com/72438169/199929109-d4c19fea-38c7-4f13-8969-f6207e39474e.png)

Delegate
Undelegate

**Comment by ntatfff** [comment]
App C98 đang update version, check lại sau khi có version mới

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (15/02/2023)

C98 app version Android 12.9.1 (update at 13 Feb 2023)
![image](https://user-images.githubusercontent.com/24869170/218984755-c0fc550e-864e-4b49-bea1-7cf6d8ad7cb4.png)

C98 app version IOS 12.9.1
![image](https://user-images.githubusercontent.com/24869170/218988716-797a0107-5e02-4aa2-b36c-a2f899761e67.png)
