### ISSUE TITLE
[Aurascan] Feegrant

### ISSUE THREAD

**Issue by Thaonguyen541** [aura-nw/aurascan#1214]
Link notion: https://www.notion.so/aura-network/5edc1a7dbc5d4e45b5b5c4aad5a7d844?v=1dd35b8b4ddc400892977b28e527833e&p=dce0c90863e147ae93cb15afbe51d837&pm=s

Link figma: https://www.figma.com/file/xiW41QvCutlazTw9PSQC01/%5BAura%5D-Scan?node-id=2660%3A94749

**Comment by Dpthao245** [comment]
Link figma Feegrant: https://www.figma.com/file/xiW41QvCutlazTw9PSQC01/%5BAura%5D-Scan?node-id=4064%3A179595&t=qoLaCun9wafQPp5n-0

**Comment by Dpthao245** [comment]
Update Docs sau khi confirm BA
1/ My Grantees / Granter:

- Search box: Search hint: “Search for Tx Hash or Address” -> bỏ search Status
- SPEND LIMIT, EXPIRATION, SPENDABLE: hiển thị "-" nếu không có data
- Phân trang 20 dòng/ page

2/ Add New Grant

- Grantee's address: check format địa chỉ aura,
- > Message "This is not aura's externally owned account"

- Nhập Period Spend Limit Amount < Spend Limit Amount
-> Message "Period Spend Limit Amount must less than Spend Limit Amount"

- Không nhập Spend Limit Amount thì vẫn cho nhập Period Spend Limit Amount

- Execute contract vẫn có type là Basic hoặc Periodic (phụ thuộc Yes hay No ở field Periodically granted)

- Message data của grant allowance với type periodic cần hiện thêm thông tin 'Period spend limit' và 'period'
Period textbox: nhập số nguyên (Transaction Detail hiển thị s theo Raw data)

- Period: (thời điểm hiện tại + period) phải nhỏ hơn Expiration time
-> Message "The first period end time need to be sooner than Expiration Time"
