### ISSUE TITLE
[Aurascan][ViewNFT] Indexer bổ sung data địa chỉ From - To của transaction Buy

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#1227]
- [ ] ISSUE: Indexer bổ sung data địa chỉ From - To của transaction Buy

**Screenshot**
![image](https://user-images.githubusercontent.com/72438169/198518504-a8e644fd-1386-45b3-8be4-5aec7cd2a039.png)

**Expected result**
![image](https://user-images.githubusercontent.com/72438169/198518540-f9de3e6c-4463-4f04-968b-717ef719a2c4.png)

**Comment by fibonacci998** [comment]
indexer tx api has option needFullLog to view full log tx

**Comment by Dpthao245** [comment]
PASS in Serenity 11/11/2022
Link: https://serenity.aurascan.io/tokens/token-nft/aura1efku8djz8sfatakek8pw2zc5rdp6f7ca6h5pghruxmgz7ytynppqh9y4q4/1668139048463

![image](https://user-images.githubusercontent.com/72438169/201281945-707b8526-f8ff-4a4f-a9e0-a22af54d842a.png)

![image](https://user-images.githubusercontent.com/72438169/201281866-0f4c8640-be90-489e-8517-dff0d2fc3525.png)

**Comment by Dpthao245** [comment]
Close ticket này vì Twilight chưa có môi trường tương ứng Euphoria - Aurascan để check
