### ISSUE TITLE
[Aurascan] Improve dashboard

### ISSUE THREAD

**Issue by Thaonguyen541** [aura-nw/aurascan#1233]
- Design:
(https://www.figma.com/file/xiW41QvCutlazTw9PSQC01/%5BAura%5D-Scan?node-id=4064%3A179595&t=NnmoPpa4KhkRHJ1x-0)
- Mockup aurascan new dashboard
https://app.diagrams.net/#G1SV6QK87Jp90IzhjKo7Whv9lL3Bt4cQFZ

**Comment by Dpthao245** [comment]
- [ ] ISSUE 01: List Voting Period không hiển thị đc danh sách khi scroll màn hình lên trên

![Image](https://user-images.githubusercontent.com/72438169/203692220-e81864a3-9aa8-41a3-be71-dea7cf80df39.png)

- [ ] ISSUE 02: Price hiển thị + - 3%
- [ ] ISSUE 03: Khoảng cách icon và text Aura đang xa nhau

![Image](https://user-images.githubusercontent.com/72438169/203694934-85c8904c-5af2-4ace-842a-ed99d1620dcf.png)

- [ ] ISSUE 04: Weight 600 -> 700

![Image](https://user-images.githubusercontent.com/72438169/203710241-9f10260f-04e9-4f7e-87a0-5add9826fee7.png)

- [ ] ISSUE 05: Size 16px -> 14px

![Image](https://user-images.githubusercontent.com/72438169/203710923-587b3493-4b61-4563-ba10-910bdcfc8942.png)

- [ ] ISSUE 06: Size, màu 16px / FFFFFF -> 14px / F2F3F5

![Image](https://user-images.githubusercontent.com/72438169/203711657-3692c409-1cde-458d-bf70-e34054f953a7.png)

- [ ] ISSUE 07: Size 16px -> 14px

![Image](https://user-images.githubusercontent.com/72438169/203712805-410fb981-aa40-4cf7-b80e-057d9f508fa9.png)

- [ ] ISSUE 08: Size, màu -> 14px / #E5E7EA

![Image](https://user-images.githubusercontent.com/72438169/203713127-398536e6-c96e-438d-a012-d7f618ca9aef.png)

- [ ] ISSUE 09: Size màu -> FFFFFF

![Image](https://user-images.githubusercontent.com/72438169/203713372-ab9dd7c5-6d8d-4378-8346-4d10f852fdc6.png)


- [ ] ISSUE 10: Size -> 16px

![Image](https://user-images.githubusercontent.com/72438169/203713792-784f3fc2-386a-43ff-be9a-512e82435223.png)

- [ ] ISSUE 11: Size -> 14px

![Image](https://user-images.githubusercontent.com/72438169/203714012-e2113ed6-5a28-4942-9fe5-d8dd3d77ad0e.png)

**Comment by Dpthao245** [comment]
**Mobile**
- [ ] ISSUE 01: Mobile hiển thị data không đúng Des
![image](https://user-images.githubusercontent.com/72438169/203716981-73bb97d1-0581-43bb-8e68-527765611c95.png)
![image](https://user-images.githubusercontent.com/72438169/203717111-7d50ae00-8d1a-4d1d-aa2d-c1b13b2652c9.png)

**Comment by Dpthao245** [comment]
Test 28/11/2022

- [ ] ISSUE 01: Size 20px -> 22px

![Image](https://user-images.githubusercontent.com/72438169/204226220-9adf3600-b670-4590-b088-6f06af610310.png)

- [ ] ISSUE 02: Size 22px -> 16px

![Image](https://user-images.githubusercontent.com/72438169/204227904-37fe02a2-5605-400d-89b8-665d89fe6913.png)


- [ ] ISSUE 03: Kích thước icon Download -> 40 x 40 px

![Image](https://user-images.githubusercontent.com/72438169/204227813-e0c44e3d-7b6e-40a5-9b1d-b9489f5928d1.png)

**Comment by Dpthao245** [comment]
Tested in Serenity 29/11/2022

- Check hiển thị số liệu: Price, Market Cap, 24h Vol Trading

> Sau 3s cập nhật 1 lần

> Price: 0.075 -> Hiển thị 4 số thập phân (đã confirm BA)

![Image](https://user-images.githubusercontent.com/72438169/204435027-3d8bd656-2ec5-4a6f-a930-079652ecb1eb.png)

> Link API: https://www.coingecko.com/en/api/documentation

![Image](https://user-images.githubusercontent.com/72438169/204434082-ac2c8397-f2cf-4cd2-be8a-e073494e10d8.png)

![Image](https://user-images.githubusercontent.com/72438169/204435416-7a0d738b-3b86-4cce-ad12-1bfc2455441b.png)

- Check hiển thị số liệu: Height, Community Pool, Transactions, Bonded Token, Inflation rate, Staking APR

> Height, Community Pool, Transactions, Bonded Token, Inflation rate: Không thay đổi cách lấy số liệu

> Staking APR: tính theo công thức => Staking APR = 12% / (2.4M / 22.9M) = 1.14%

> Tài liệu công thức tính Staking APR: https://www.notion.so/aura-network/5edc1a7dbc5d4e45b5b5c4aad5a7d844?v=1dd35b8b4ddc400892977b28e527833e&p=69a349e667764d7aababc85fa08413ee&pm=s

![Image](https://user-images.githubusercontent.com/72438169/204439144-216c5dad-d94d-4db0-8a96-5919705f734d.png)
![Image](https://user-images.githubusercontent.com/72438169/204438521-220f91f1-ea24-470d-8e07-e0a3eadb05c8.png)

**Comment by Dpthao245** [comment]
PASS Euphoria 26/12/2022

- Check hiển thị số liệu: Price, Market Cap, 24h Vol Trading

![image](https://user-images.githubusercontent.com/72438169/209523802-0812035e-bf76-4972-b0a6-8bf6aa9e1e61.png)
![image](https://user-images.githubusercontent.com/72438169/209523885-ffc2ca07-2f9c-4e86-aee0-a9f8e45a3b5d.png)

- Check hiển thị số liệu: Height, Community Pool, Transactions, Bonded Token, Inflation rate, Staking APR
Staking APR: tính theo công thức => Staking APR = 12.22% / (17.3M / 472.6M) = 3.34%

![image](https://user-images.githubusercontent.com/72438169/209524876-36c7a721-8cf1-4559-9aa0-5076b6e77055.png)

- Chart: hiển thị mặc định 60M và Price
![image](https://user-images.githubusercontent.com/72438169/209525358-79ca0f44-3528-4a21-89d1-1b80842c037d.png)

Price - 60M
![image](https://user-images.githubusercontent.com/72438169/209525251-c4c2a575-e3da-4448-b3c6-6124e789a94e.png)

Price - 24H
![image](https://user-images.githubusercontent.com/72438169/209525668-bff901ba-7800-4433-8a7f-f6947adac1db.png)

Price - 30D
![image](https://user-images.githubusercontent.com/72438169/209525853-274dffc1-bf15-4f47-a03e-583babc5aa4d.png)

Price - 12M
![image](https://user-images.githubusercontent.com/72438169/209526033-6b3c5c2f-60cc-4a25-b680-067731d17107.png)

Volumn - 60M
![image](https://user-images.githubusercontent.com/72438169/209526431-b6c28575-f0fd-422a-a7fc-7146cb1f4389.png)

Volumn - 24H
![image](https://user-images.githubusercontent.com/72438169/209526825-8dc5de4a-1c60-4a52-9e44-a8f19e58e583.png)

Volumn - 30D
![image](https://user-images.githubusercontent.com/72438169/209526931-ce495edd-4b88-4890-8ee5-002a9d953c17.png)

Volumn - 12M
![image](https://user-images.githubusercontent.com/72438169/209527080-220b9b9f-0da5-4a4a-bfc2-7e71f190cb74.png)

- Social Medical
![image](https://user-images.githubusercontent.com/72438169/209527226-110a1deb-5737-4f7f-89d2-ec46b5e42286.png)

> Discord: https://discord.com/invite/bzm3dyxJxR
![image](https://user-images.githubusercontent.com/72438169/209527316-23ce19b1-3d93-4746-8f85-1cf9001fe661.png)

> Telegram: https://t.me/AuraNetworkOfficial
![image](https://user-images.githubusercontent.com/72438169/209527383-8bc212a9-6a8f-4cba-9da7-1af79a247014.png)

> https://aura.network/?_ga=2.168646884.455483412.1669600407-1692044011.1666163551
![image](https://user-images.githubusercontent.com/72438169/209527518-9e53b9a8-647a-4600-8700-709ef55f8ded.png)

> Aura Docs: https://docs.aura.network/?_ga=2.228955993.455483412.1669600407-1692044011.1666163551
![image](https://user-images.githubusercontent.com/72438169/209527698-490fb05f-9ddb-4637-ae50-7f7c74eef84a.png)

> Github: https://github.com/aura-nw
![image](https://user-images.githubusercontent.com/72438169/209527607-4a96a5ef-200d-4dc3-a647-f5699a80608f.png)

- Voting Period

> Không có Proposal đang trong giai đoạn voting
![image](https://user-images.githubusercontent.com/72438169/209527993-060bd6ac-5ce9-4d4e-ba3c-43450f64831e.png)

![image](https://user-images.githubusercontent.com/72438169/209527958-1a19ad5c-47f3-40bf-8bb8-725bbba8339d.png)
