### ISSUE TITLE
[Aurascan] Graph is displayed incorrect time

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1235]
Issue happens on Euphoria and Serenity
**Bug description:**
- Current date is 01/11/2022
- Issue: Graph is displayed with time is 01/12/2022

**Expected result:**
- [ ] Graph is displayed with current date & time

**Screenshot:**
![image](https://user-images.githubusercontent.com/24869170/199149919-33302150-351a-450b-ae91-20202860defd.png)
![image](https://user-images.githubusercontent.com/24869170/199149969-940b7986-3ca2-4426-86ec-58c823936dbd.png)
![image](https://user-images.githubusercontent.com/24869170/199149989-8e9767ea-dcd2-4b93-8f72-b7c93571451d.png)
![image](https://user-images.githubusercontent.com/24869170/199150026-7e6bcf6c-bc0e-44c8-ad1d-dd7cd79cc03e.png)

**Comment by sonhv** [comment]
Rootcause: it's bug for first day of the month that generate series to display plus 1 month for all filter 60 minutes, 24h, 30d and 12 months
Solution: Do not generate series fro BE code, use timestamp from infuxdb instead which have been supported funtion createEmpty window

Bug fixed

**Comment by ntatfff** [comment]
Verified PASS on serenity (01/11/2022)
![image](https://user-images.githubusercontent.com/24869170/199182689-0f50d9fa-70ee-40fd-b517-db91590d9675.png)
![image](https://user-images.githubusercontent.com/24869170/199185278-5ea6bce5-7abd-4b51-81fb-f3df9bb668b3.png)

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (01/11/2022)
![image](https://user-images.githubusercontent.com/24869170/199186935-0868b5f7-313d-40cd-838e-7b430117dd39.png)
![image](https://user-images.githubusercontent.com/24869170/199186861-f5d4ae60-81be-4fc8-963c-9a41b4f70446.png)
