### ISSUE TITLE
[PeriodicVestingAccounts] Enhancement periodic vesting accounts

### ISSUE THREAD

**Issue by NgocAnh7278** [aura-nw/aurascan#1242]
Current: Periodic vesting accounts are only initialized at the genesis initialization.

Enhancement: Periodic vesting accounts can also be initialized from normal accounts at any time
**Step 1**: Create a JSON file with periodic vesting information:
![image](https://user-images.githubusercontent.com/40628286/199878945-c9459641-ade8-4bb2-92da-a76a1fa3ed75.png)
File: 
[vesting_periodic.txt](https://github.com/aura-nw/aurascan/files/9934770/vesting_periodic.txt)

**Step 2**: Query a normal account to be initialized as a periodic vesting account.

**Step 3**: Test CLI
Run the command line with the syntax below
![image](https://user-images.githubusercontent.com/40628286/199873170-59522709-0d3e-43eb-870f-632e89c56958.png)

**Step 4**: Query this account again to see the result.

**Step 5**: Check amount released of account

File sample cmd: 
[vesting_test.txt](https://github.com/aura-nw/aurascan/files/9934775/vesting_test.txt)

Preference: https://docs.cosmos.network/v0.46/modules/auth/05_vesting.html#periodic-vesting-accounts

**Comment by ntatfff** [comment]
Verified PASS on serenity (11/11/2022)
- **Command line:** 
aurad tx vesting create-periodic-vesting-account aura1j5q4d3435z4tz8qs64j4tk0rpzhlwhehjt8z4f vesting_periodic_se.json --from Thu --gas-prices 0.025uaura --chain-id serenity-testnet-001 --keyring-backend test --yes --node https://rpc.serenity.aura.network:443 --gas=1000000

- **Address creates vesting:** aura1gypt2w7xg5t9yr76hx6zemwd4xv72jckk03r6t

- **JSON file:** 
![image](https://user-images.githubusercontent.com/24869170/201280239-29d530f0-663f-4753-bd4b-c42dd9c83d8f.png)

- **Transaction:** 
https://serenity.aurascan.io/transaction/375BA5CC9249A5F0BE15265268ACB3A195979845B7CDCF3249C3368EA34AA9B0

- **Output after creating vesting account via command line**
![image](https://user-images.githubusercontent.com/24869170/201281266-b5434d27-1c02-40f5-9a95-cb65dc487e7b.png)

**Display on UI aurascan:**
![image](https://user-images.githubusercontent.com/24869170/201279576-c071d101-5f4a-4378-8d84-497faf64321e.png)
![image](https://user-images.githubusercontent.com/24869170/201280469-26bf7891-8776-490d-b010-98f3e52c4507.png)
![image](https://user-images.githubusercontent.com/24869170/201281356-78682ac5-23d6-4cfd-b14d-014617f4da2c.png)
![image](https://user-images.githubusercontent.com/24869170/201284417-557b8aec-2453-44c2-9b1a-97cc70c09496.png)
