### ISSUE TITLE
[Enhancement] Execute contract transaction doesn't map with contract's transaction history 

### ISSUE THREAD

**Issue by Thaonguyen541** [aura-nw/aurascan#1247]
New type of execute contract transaction --> transaction isn't be mapped and show up in contract's transaction history
Example:
https://serenity.aurascan.io/transaction/C17AC218F3FF7390B77288199052910C7F7635CD759927D6F8FCCAF7F6CE4075
https://serenity.aurascan.io/transaction/9EB031294BF820B0365B3697F8D93C63525A1B8E02D98FC80B0A0B6454D51168

**Comment by Dpthao245** [comment]
![Image](https://user-images.githubusercontent.com/72438169/200765308-4d9e5539-fe80-4dc1-8079-716d4757aaba.png)

Hiển thị thêm cột Result và Transaction Fail trong các màn hình Contract Details, Token Details, NFT Details

**Comment by Dpthao245** [comment]
PASS hiển thị cột Result trên Serenity 09/11/2022

Contract Details

![Image](https://user-images.githubusercontent.com/72438169/200765699-6f7cdc93-d73b-4ebf-a5c2-149ff5e51dd2.png)

Token Details

![Image](https://user-images.githubusercontent.com/72438169/200765917-332bc552-4815-4ce7-a342-627bdd2f20fe.png)

NFT Details

![Image](https://user-images.githubusercontent.com/72438169/200766018-621239c8-aaa0-46c1-b860-3228d7755eef.png)

**Comment by ntatfff** [comment]
Verified FAIL on serenity (18/11/2022)
**ISSUE:** Thiếu transaction FAIL ở màn hình Token details
**Expected result:** Có hiển thị transaction FAIL ở màn hình Token details
![image](https://user-images.githubusercontent.com/24869170/202677783-1f4cf3b3-9924-4e66-a86e-8298ef3e1022.png)

**Note:** có hiển thị transaction FAIL ở màn hình Contract details, Token details
![image](https://user-images.githubusercontent.com/24869170/202677521-cfee9400-25aa-4588-baad-e0e3420fe98a.png)
![image](https://user-images.githubusercontent.com/24869170/202677586-55e05e45-d22e-4da5-badd-b3d638ff48ed.png)

**Comment by ntatfff** [comment]
Verified PASS on serenity (22/11/2022)
Display transaction FAIL at

- NFT details: https://serenity.aurascan.io/tokens/token-nft/aura1zndmqswwm78ve55hqd92cs02lhk4n8hml4852hszlqymny8nvpmstvt2c6/%23ID-14Nov2022-99
![image](https://user-images.githubusercontent.com/24869170/203215216-fd901cf6-4265-49cf-b0c0-f3d6d69b1e1b.png)

- Token details: https://serenity.aurascan.io/tokens/token-nft/aura1zndmqswwm78ve55hqd92cs02lhk4n8hml4852hszlqymny8nvpmstvt2c6/%23ID-14Nov2022-99
![image](https://user-images.githubusercontent.com/24869170/203215337-c99061e9-265b-4ef5-b427-cff5a9a3f9ea.png)

- Contract details: https://serenity.aurascan.io/contracts/aura1zndmqswwm78ve55hqd92cs02lhk4n8hml4852hszlqymny8nvpmstvt2c6
![image](https://user-images.githubusercontent.com/24869170/203215394-72c191a6-020f-4b0b-bb38-1fe763ee9ba9.png)

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (27/12/2022)
- Token details, Account details
![image](https://user-images.githubusercontent.com/24869170/209652712-e7b9d7aa-2aec-4448-b3e8-3fe95628fe1d.png)
- Token details, Contract details
![image](https://user-images.githubusercontent.com/24869170/209646824-f3124096-e933-4f1d-84d5-61db65042015.png)
- Token details, NFT details
![image](https://user-images.githubusercontent.com/24869170/209652870-a747d102-39d8-4166-b8df-cfbdc398da7c.png)
