### ISSUE TITLE
[Aurascan][AccountDetail] Update API for Account Detail screen

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#1254]

**Comment by ntatfff** [comment]
Verified PASS on serenity (11/11/2022)
![image](https://user-images.githubusercontent.com/24869170/201256847-1729f511-9ffe-486d-bd40-ee11b99bd6c2.png)
![image](https://user-images.githubusercontent.com/24869170/201256990-76947171-5020-4ce5-9e96-d5d81cbb3208.png)
![image](https://user-images.githubusercontent.com/24869170/201257023-d9f06826-45a0-4637-ad89-16abc7b0ae83.png)
![image](https://user-images.githubusercontent.com/24869170/201256883-260efbb1-d9b1-43cd-aa80-e180698bea5c.png)
![image](https://user-images.githubusercontent.com/24869170/201254364-766ba3db-cf0e-47a5-8ed6-647c648bb7fd.png)
![image](https://user-images.githubusercontent.com/24869170/201254905-d075b4c5-3add-401d-a97a-cd4ea0cc50b1.png)

**Comment by ntatfff** [comment]
Verified PASS on serenity (18/11/2022)
![image](https://user-images.githubusercontent.com/24869170/202636711-1776a09c-9f3e-40ce-b4e9-f32ef0cbd3de.png)
![image](https://user-images.githubusercontent.com/24869170/202636964-b199e8d9-0d2a-405e-8c56-47924610482f.png)
![image](https://user-images.githubusercontent.com/24869170/202636998-34a71972-9191-4798-a0cd-fed7114ca481.png)
![image](https://user-images.githubusercontent.com/24869170/202637087-e5ff6e7a-c54e-4983-8137-a940fd099370.png)
![image](https://user-images.githubusercontent.com/24869170/202637680-c2640557-589c-4870-be72-77b217123da7.png)
