### ISSUE TITLE
[Aurascan][CW20][TokenDetails] Filter By Holder

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#1260]
**Link Token Details:** https://explorer.dev.aura.network/tokens/token/aura1x495m74lv8qsyf5ryf3qaqm72dzhc53slpf57s60txkmmjt39qkqcwjda6

**- [ ] ISSUE: Filter By Holder đang hiển thị sai kết quả search**

**Screenshot**
Trước khi thực hiện Filter
![image](https://user-images.githubusercontent.com/72438169/200783947-01171d19-d2a3-4775-9d5f-7ac83a35a8db.png)

Thực hiện Filter by Holdetr = "aura1xydnzs2s9pjh4cksc2ejv3t002d7pwedld2lp8"
![image](https://user-images.githubusercontent.com/72438169/200784985-a38b65ee-a537-4f7d-971c-bf69bdb4145c.png)

**Note: CW721 bị lỗi tương tự**

-----------------------------------------------------
Meeting note 02/11/2022:
+ Account detail: Tuấn cập nhật api trên indexer cho phép search theo name và address(Không search like).
+ List token CW20:
    - Holder: Tuấn bổ sung thêm api trên Indexer để tính gía trị holder thay đổi trong 24h.
    - Sẽ lưu thông tin price, volume, holder... vào db MySql. Dùng Queue để sync data từ coingecko.

**Comment by ntatfff** [comment]
Verified FAIL on serenity (18/11/2022)
Không hiển thị kết quả sau khi filter
![image](https://user-images.githubusercontent.com/24869170/202691844-c0e2b2ff-8c05-4ba3-89c4-5f579252c9b7.png)

**Comment by Dpthao245** [comment]
PASS in Serenity 22/11/2022

- Filter theo "aura1cg0pqjmq3p2pl0gyz62vrcattj0f60glzgd8s4"

![Image](https://user-images.githubusercontent.com/72438169/203212853-cb497d0f-91fa-4dc3-8ffd-a6847e90abf8.png)

![Image](https://user-images.githubusercontent.com/72438169/203213392-415f7231-a9da-476e-8ef0-716144acdf13.png)

- Filter theo "aura1h6r78trkk2ewrry7s3lclrqu9a22ca3hpmyqfu"

![Image](https://user-images.githubusercontent.com/72438169/203213614-a5127aa5-4d80-4bae-bbf2-dbf20defca70.png)

![Image](https://user-images.githubusercontent.com/72438169/203213874-07758493-3978-41c0-8f31-5c69fb6212d4.png)

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (27/12/2022)
- FILTER BY ADDRESS: [aura1trqfuz89vxe745lmn2yfedt7d4xnpcpvltc86e](https://euphoria.aurascan.io/account/aura1trqfuz89vxe745lmn2yfedt7d4xnpcpvltc86e)
![image](https://user-images.githubusercontent.com/24869170/209627294-441f8611-3fbc-4b00-a3bc-838319370ecc.png)

- FILTER BY ADDRESS: [aura1afuqcya9g59v0slx4e930gzytxvpx2c43xhvtx] (minter address)(https://euphoria.aurascan.io/account/aura1afuqcya9g59v0slx4e930gzytxvpx2c43xhvtx)
![image](https://user-images.githubusercontent.com/24869170/209627639-aeecf2b7-3b60-4112-8ec6-144fb09bc6dc.png)
