### ISSUE TITLE
[Enhancement] Chart  zoom in/zoom out, select period UX improvement

### ISSUE THREAD

**Issue by Thaonguyen541** [aura-nw/aurascan#1266]

**Comment by Dpthao245** [comment]
![Image](https://user-images.githubusercontent.com/72438169/205214937-681c316b-6829-46cc-8dd7-898ddb1929d4.png)

**Comment by thanhhao1986** [comment]
Xử lý khi user thực hiện zoom out:
- Bổ sung thêm parameter minDate cho api [.../api/v1/metrics/token?range=30d&coidId=aura-network], parameter này là optional và có kiểu dữ liệu là Date.
- Khi user thực hiện zoom out, frontend cần xác định khoản thời gian nhỏ nhất đang hiển thị trên chart là bao nhiêu, sau đó gán giá trị này vào parameter minDate và call api để lấy data.
- Nếu minDate có giá trị thì backend sẽ lấy data từ influxdb theo khoản thời gian bằng minDate về trước dựa trên các option 60m, 24h, 30d, 12mo và trả data về cho frontend. Lúc này frontend sẽ lấy data thêm vào phần data của chart và hiển thị kết quả cho user.

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (17/01/2023)
![image](https://user-images.githubusercontent.com/24869170/212869315-73dadcb2-6cec-4437-8f94-3338f34ba5c7.png)
https://user-images.githubusercontent.com/24869170/212869781-7e0396de-66ec-48c5-ab38-f0cf32b17280.mp4
[Price_17012023_170195 (3).xlsx](https://github.com/aura-nw/aurascan/files/10433761/Price_17012023_170195.3.xlsx)
[Price_17012023_170195 (2).xlsx](https://github.com/aura-nw/aurascan/files/10433762/Price_17012023_170195.2.xlsx)
[Price_17012023_170195 (1).xlsx](https://github.com/aura-nw/aurascan/files/10433763/Price_17012023_170195.1.xlsx)
[Price_17012023_170195.xlsx](https://github.com/aura-nw/aurascan/files/10433764/Price_17012023_170195.xlsx)
