### ISSUE TITLE
[Aurascan][TokenCW721] Transfers (3D) number is incorrect

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1271]
**Description bug:**
Count Transfers (3D) number is missing, current Transfer (3D) = 5
- Current time: 14:05:00 14/11/2022
- Transaction at 14:50:18 11/11/2022 is not counted (in Transfer (3D))

**Expected result:** Counting number of Transfers (3D)
- from current time:              14:05:01 11/11/2022
- to (current time + 3 days): 14:05:00 14/11/2022
- current  Transfers (3D) = 6

**Screenshot:**
https://explorer.dev.aura.network/transaction/D563C62B896978DF6DC9754DADE6EA42E0B393F904343ACA6409194161914601
![image](https://user-images.githubusercontent.com/24869170/201597282-bef6c02d-3433-4d12-99bb-b60c9f11a6df.png)
![image](https://user-images.githubusercontent.com/24869170/201597374-4bcb3f9f-adc4-4a8a-ba28-5e85bc3c7bf0.png)

**Comment by sonhv** [comment]
Hi @ntatfff, yesterday, around that time we merged new PR to remove transactions table, so that, It's maybe slow to resync latest transactions.
By query from that time in database by shift the date to your date, I got the correct results.
Please help to refer the image I attached below for more detail

![image](https://user-images.githubusercontent.com/22702954/201935183-3bcb2fed-2e01-4b3d-9405-24c6f51fb5fb.png)

![image](https://user-images.githubusercontent.com/22702954/201935057-045fad34-83df-4585-8475-1bcdd2b36651.png)

**Comment by sonhv** [comment]
BTW, could you please help me to verify it again?

**Comment by ntatfff** [comment]
Verified FAIL on serenity (17/11/2022)
Still count number of Transfer(3D) incorrectly
![image](https://user-images.githubusercontent.com/24869170/202347670-7429be05-a8e9-41d8-8f2d-462dd0ae98fb.png)

**Comment by sonhv** [comment]
Hi @fibonacci998, It's missing failed transactions for contact detail (transafer tab). please help me to fix in indexer first
thank you

**Comment by fibonacci998** [comment]
i added tx fail to tx api search with execute_contract_address condition

**Comment by ntatfff** [comment]
Verified PASS on serenity (23/11/2022)
![image](https://user-images.githubusercontent.com/24869170/203469390-b56caef6-45e3-4205-8fb3-b807f45c21d4.png)
![image](https://user-images.githubusercontent.com/24869170/203469532-f7dd4b77-b58a-49c1-98c3-5187d8c866ee.png)
![image](https://user-images.githubusercontent.com/24869170/203469900-f4143e13-71b9-45fb-a539-20fe06eabd22.png)

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (26/12/2022)
![image](https://user-images.githubusercontent.com/24869170/209533820-e2c7fd74-aa0c-483e-a6aa-5d856e6cefff.png)
![image](https://user-images.githubusercontent.com/24869170/209534104-e19fc411-136b-4174-affd-663bd236c800.png)
