### ISSUE TITLE
[Aurascan][NFT Detail] Không update địa chỉ owner khi có giao dịch Buy, Transfer

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#1273]
- [ ] Token Details - Inventory tab, NFT Detail, Account Detail - NFT Assets: Không update địa chỉ owner khi có giao dịch Buy/ Transfer NFT

Link NFT có giao dịch Buy: https://serenity.aurascan.io/tokens/token-nft/aura1uz29q6kgll6a8wpf3un789352hcr4g76eqaz4uxhzhn8l3gukc4quaetgz/1668400456044

Link NFT có giao dịch Transfer: https://serenity.aurascan.io/tokens/token-nft/aura1992q8ekk2xxkh36nxatkmsk84pes2vmxjzdttqvm42puypquux5q75c3ux/%23ID1-10:30-15%2F11%2F2022

**Screenshot**
![image](https://user-images.githubusercontent.com/72438169/201844624-f8850552-db01-40c7-afb4-8c660b1e0c1c.png)
![image](https://user-images.githubusercontent.com/72438169/201844754-49c63a3f-2bb9-4be8-8df8-e583ffd0632b.png)

**Comment by ntatfff** [comment]
Verified PASS on serenity (18/11/2022)
![image](https://user-images.githubusercontent.com/24869170/202681458-69d08e1b-325c-4ba9-a951-0aec147b1ca0.png)
![image](https://user-images.githubusercontent.com/24869170/202683405-0bb625a4-2a67-4853-8e2e-8ff472ac26b4.png)
