### ISSUE TITLE
[Aurascan][TokenDetails] Hiển thị sai thứ tự NFTs

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1274]
**Bug description:**
Inventory tab
- [ ] Hiển thị sai thứ tự NFTs
- [ ] Không xem được trang cuối cùng 

Account details: https://serenity.aurascan.io/account/aura1trqfuz89vxe745lmn2yfedt7d4xnpcpvltc86e
- [ ] Hiển thị sai thứ tự NFTs

**Steps:**
1. Go to Token details
2. Click on Inventory tab
3. Check thứ tự hiển thị NFTs
4. Click phân trang để xem last page
5. See error

**Expected result:**
- Hiển thị đúng thứ tự NFTs (sort giảm dần theo updated time)
- Xem được tất cả các trang => cập nhật ngày 25/11/2022: hiển thị tối đa 200 NFTs (10 trang)

![image](https://user-images.githubusercontent.com/24869170/201851098-6a58aa82-22a0-4929-8de4-0f0ff43e1037.png)
![image](https://user-images.githubusercontent.com/24869170/201851267-dcd05e7c-0624-49ce-bdb7-5b963970cd91.png)

**Comment by ntatfff** [comment]
Verified FAIL on serenity (25/11/2022)
Vẫn còn sai thứ tự transactions
https://serenity.aurascan.io/tokens/token-nft/aura1zndmqswwm78ve55hqd92cs02lhk4n8hml4852hszlqymny8nvpmstvt2c6
![image](https://user-images.githubusercontent.com/24869170/203921273-59c067c1-2bb7-4e63-8cc6-11528f2e7c17.png)

**Comment by fibonacci998** [comment]
NFT is sorted by updated time. Updated time is changed when there is an action that interact with token id, not only mint tx
