### ISSUE TITLE
[Enhancement] Add copy button beside Raw Data of Json raw log in Transactions Details page

### ISSUE THREAD

**Issue by Thaonguyen541** [aura-nw/aurascan#1278]
Add copy button beside Raw Data of Json raw log in Transactions Details page and Block Details page
+ Type: icon button
+ Function: Copy all

![image](https://user-images.githubusercontent.com/79354422/202120547-31d9f822-baba-4f87-928c-6562e87076d4.png)

![image](https://user-images.githubusercontent.com/79354422/202335955-c65dcaba-8c8b-4e52-82b7-86baac773fb2.png)

**Comment by Dpthao245** [comment]
PASS in Serenity 17/11/2022

![Image](https://user-images.githubusercontent.com/72438169/202352656-d4ff2ae1-f659-4e5b-97e1-83ae289e4865.png)

![Image](https://user-images.githubusercontent.com/72438169/202352814-f9837ca7-f26e-445e-83bd-2295ac3fed9f.png)

**Comment by Dpthao245** [comment]
PASS in Euphoria 26/12/2022
![image](https://user-images.githubusercontent.com/72438169/209518764-e8cd6164-e92b-449f-9d31-85790b09f4ea.png)
![image](https://user-images.githubusercontent.com/72438169/209518863-89934172-4f7a-4975-8682-1e252c2b10c8.png)
