### ISSUE TITLE
[Aurascan][CW721][TokenDetails] Holders tab lỗi phân trang khi >10 page

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#1282]
- [ ] ISSUE: Holders tab lỗi phân trang khi >10 page
Link: https://serenity.aurascan.io/tokens/token-nft/aura1992q8ekk2xxkh36nxatkmsk84pes2vmxjzdttqvm42puypquux5q75c3ux

**Screenshot**
![image](https://user-images.githubusercontent.com/72438169/202390552-e2c46b94-f5b4-4d2c-be36-1bae8ff95e36.png)

**Comment by fibonacci998** [comment]
indexer api has limit pageOffset 100 record only, so that reloading icon is invalid in this case

**Comment by Dpthao245** [comment]
PASS in Euphoria 26/12/2022
![image](https://user-images.githubusercontent.com/72438169/209536490-65dacfdd-426c-46ab-9a60-3585d2312102.png)
