### ISSUE TITLE
[Aurascan][CW-20Tokens] Not update Holders number and percent number of Holders

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1284]
**Bug description:**
- [x] ISSUE 1: CW-20 Token, not update Holders number and percent number of Holders
**Expected result:** update Holders number and percent number of Holders correctly
![image](https://user-images.githubusercontent.com/24869170/202690171-d433ded7-c408-423c-83f7-fc81d9d6b6d7.png)

- [x] ISSUE 2: Token details - Overview, not update Counting Holder number
**Expected result:** update Counting Holder number correctly
![image](https://user-images.githubusercontent.com/24869170/202690025-3cb11329-4d4d-4287-b72e-c34b098a8361.png)

- [x] ISSUE 3: Token details tab - Holders, not display/update recording of all holders
**Expected result:** display/update recording of all holders
![image](https://user-images.githubusercontent.com/24869170/202689688-95e08a3e-cb57-4df8-912c-7fc90a91124d.png)

- [x] ISSUE 4: Account details, not update/display data of tokens
**Expected result:** update/display data of tokens
![image](https://user-images.githubusercontent.com/24869170/202689908-17b204c5-8c4b-4cab-80de-20114c80fa7a.png)

**Comment by ntatfff** [comment]
Verified FAIL on serenity (07/12/2022)
**At token details screen:**
**Actual result:** update Holders number after mint/transfer transactions
**Expected result:** Update Holders number every day at 0h (UTC+7)
![image](https://user-images.githubusercontent.com/24869170/206101840-6b094852-8b31-4576-8213-7e84439e9523.png)

**Comment by ntatfff** [comment]
Verified FAIL on serenity (08/12/2022)
FAIL: Số Holders tự tăng sau mỗi lần mint
=> **expect result**: tăng sau sau 0H mỗi ngày (hoặc nhờ An cập nhật)
**Screenshot**
![image](https://user-images.githubusercontent.com/24869170/206436898-3b740316-d2ae-4ed4-82e3-02ee9587c1f7.png)
![image](https://user-images.githubusercontent.com/24869170/206437395-a5129e81-5bcb-49d9-b456-f7c06ec22055.png)

**Comment by thanhhao1986** [comment]
@mtamkg check hộ anh issue 2 nhé, api trả data về đúng.
Link aurascan: **https://explorer.dev.aura.network/tokens/token/aura1wz44hmjr9ug2fzjxsprkwpkjxzz2rlpp7xpxk7wa3fs5qud4v8rqqwwmlz**
![image](https://user-images.githubusercontent.com/6703750/206606602-f990da57-62b2-4989-9653-2f13ec56f45b.png)

**Comment by ntatfff** [comment]
New update at 10:54 09/12/2022

- [ ] Holders number: is updated real time => Need to update at CW20 tokens list
- % holders number: is updated at 0h every day => PASS: at CW20 tokens list and CW20 token details

**Comment by ntatfff** [comment]
Verified PASS on serenity (20/12/2022)
![image](https://user-images.githubusercontent.com/24869170/208623649-2e3186cf-dbd6-409f-bf24-e97126f6d24d.png)

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (27/12/2022)
![image](https://user-images.githubusercontent.com/24869170/209621299-1f80d3f6-21d5-45d2-b467-5b985b867c33.png)
![image](https://user-images.githubusercontent.com/24869170/209621439-b2f85adb-ab36-4db6-9262-bd86abcc42bb.png)

PASS: Update % holders after running summarize job (instead of waiting until 0h)
- at the 1st time: % holders = 0%
![image](https://user-images.githubusercontent.com/24869170/209639855-a2d756f4-62b1-4d89-bec2-c875ee855f31.png)

- from the 2nd time: % holders is updated correctly
![image](https://user-images.githubusercontent.com/24869170/209639782-db60a26c-e433-4531-8bec-3226dc4c1b48.png)
