### ISSUE TITLE
[Enhancement] Rename field in Token detail screen

### ISSUE THREAD

**Issue by Thaonguyen541** [aura-nw/aurascan#1303]
Rename field in Token detail screen in Aurascan
"FILTER BY TOKEN HOLDER" ==>> "FILTER BY ADDRESS"
![image_2022_11_28T03_55_24_524Z](https://user-images.githubusercontent.com/79354422/204193377-b4067f12-8efb-4561-9e8c-934fca59754a.png)

**Comment by Dpthao245** [comment]
PASS in Serenity 28/11/2022
CW20
![image](https://user-images.githubusercontent.com/72438169/204224109-721119a2-c4ce-445e-9e96-7ee19f830994.png)

CW721
![image](https://user-images.githubusercontent.com/72438169/204224255-b8366ed4-0dec-4a74-85f6-6ef15d039416.png)

**Comment by Dpthao245** [comment]
PASS in Euphoria 26/12/2022
CW721
![image](https://user-images.githubusercontent.com/72438169/209529675-49bc58e4-453f-42aa-a2cf-90ff781f0ba8.png)
