### ISSUE TITLE
[Aurascan] Chuyển API LCD sang Indexer

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1309]
**API LCD:**
1. cosmos/staking/v1beta1/validators/${address}/delegations?pagination.offset=${offset}&pagination.limit=${limit}&pagination.countTotal=true&pagination.reverse=true
2. cosmos/tx/v1beta1/txs/${txhash}
3. cosmos/tx/v1beta1/txs?events=proposal_deposit.proposal_id%3D%27${proposalId}%27&order_by=ORDER_BY_DESC
4. cosmos/tx/v1beta1//txs?events=proposal_vote.proposal_id%3D%27${proposalId}%27&events=transfer.sender%3D%27${voter}%27&pagination.offset=${offset}&pagination.limit=${limit}&order_by=ORDER_BY_DESC
5. cosmos/slashing/v1beta1/signing_infos?pagination.limit=${limit}&pagination.reverse=true
6. cosmos/slashing/v1beta1/signing_infos/${cons_address}

**API Indexer:**
- [ ] 1. API indexer chưa có
- [ ] 2.https://indexer.dev.aurascan.io/api/v1/transaction?chainid=aura-testnet-2&txHash=abc
- [x] #1400
- [x] #1404
- [x] #1407

**Comment by nhphuc2411** [comment]
Số 1 đã tạo issue bên indexer
