### ISSUE TITLE
[Aurascan] Sync contract from Indexer

### ISSUE THREAD

**Issue by nhphuc2411** [aura-nw/aurascan#1336]

**Comment by thanhhao1986** [comment]
I/ Sơ đồ sequence diagram:
![image](https://user-images.githubusercontent.com/6703750/205799732-8f36a2ac-b715-4757-8edc-0d387109e45c.png)

II/ Mô tả:
1/ Aura Explorer Sync sẽ crawl data transactions từ Aura Network(Bockchain).
2/ Kiểm tra type của transaction, nếu đúng là MsgInstantiateContract/MsgExecuteContract thì thực hiện bước 3 ngược thì bỏ qua.
3/ Aura Explorer Sync sẽ crawl data smart contract từ Indexer(Heroscope).
4/ Xử lý và insert data vào bảng  Smart contract (MySQL).

**Comment by ntatfff** [comment]
Verified PASS on serenity (21/12/2022)
- PASS flows: 1, 2, 3, 6
- Ignored flows: 4, 5 (this features are hidden)
![image](https://user-images.githubusercontent.com/24869170/208860919-f09ac0dc-9457-44d9-acb6-ff61334b0a87.png)
![image](https://user-images.githubusercontent.com/24869170/208860986-e5fe4932-de07-4c93-96a6-2514b1dccde1.png)
[2022-12-21_14h13_12.zip](https://github.com/aura-nw/aurascan/files/10276053/2022-12-21_14h13_12.zip)
[2022-12-21_13h50_57.zip](https://github.com/aura-nw/aurascan/files/10276054/2022-12-21_13h50_57.zip)
[2022-12-21_13h13_20.zip](https://github.com/aura-nw/aurascan/files/10276055/2022-12-21_13h13_20.zip)
[2022-12-21_13h42_44.zip](https://github.com/aura-nw/aurascan/files/10276058/2022-12-21_13h42_44.zip)

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (27/12/2022)
PASS flows: 1, 2, 3, 6
**refer to tickets below**
https://github.com/aura-nw/aurascan/issues/1357
https://github.com/aura-nw/aurascan/issues/1367
