### ISSUE TITLE
[Aurascan][MyGrantees][AddNewGrant] Add được grant cho địa chỉ đã có grant hết hạn

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#1337]
- [ ] ISSUE: My Grantees: add được grant cho địa chỉ đã có grant hết hạn

![image](https://user-images.githubusercontent.com/72438169/205215304-ff8ebe32-2fad-49a6-83b5-bb0b4081514c.png)

**Comment by Dpthao245** [comment]
PASS in Serenity 07/12/2022
Address có grant hết hạn: aura12yxrag2d4e7lt6s6y5x59amhvehx52f7t2frjm
![image](https://user-images.githubusercontent.com/72438169/206088222-c9947bc0-bc27-4fb7-bb21-c81d2f360561.png)

Thực hiện Add New Grant -> thành công
![image](https://user-images.githubusercontent.com/72438169/206088900-4b66c5ba-688f-4ca7-8b06-a5da11b67d96.png)
![image](https://user-images.githubusercontent.com/72438169/206088911-967594a7-17de-44de-8f0e-0c2a482459c5.png)
![image](https://user-images.githubusercontent.com/72438169/206088925-f0a2b1e4-1739-4daf-8d4c-e71fc9f9f81e.png)
![image](https://user-images.githubusercontent.com/72438169/206088935-e5a5e3ce-a3eb-4a64-8eff-068d19ede2d8.png)
![image](https://user-images.githubusercontent.com/72438169/206088948-1ca215db-c799-4c4d-8859-bdd120042f49.png)
![image](https://user-images.githubusercontent.com/72438169/206088974-d00eb4ff-cf65-4ccb-8c50-01eb5720773f.png)
![image](https://user-images.githubusercontent.com/72438169/206088983-e4168697-502b-4714-8ddf-db8c1d4fc487.png)
![image](https://user-images.githubusercontent.com/72438169/206088998-64b839f3-2b08-4fbb-b17b-d16b48a8e9c3.png)
![image](https://user-images.githubusercontent.com/72438169/206089007-9fc88479-e151-402b-ba57-0dd36f571158.png)

**Comment by ntatfff** [comment]
Hiện tại chưa có data để test

**Comment by Dpthao245** [comment]
FAIL in Euphoria 29/12/2022

- Địa chỉ có Grant hết hạn: aura1fy7v3tf37a5aqqkgjj8q5tlz2h33370x5x307u

![image](https://user-images.githubusercontent.com/72438169/209893587-938bfc08-b095-4dba-8146-8c8f870054e8.png)

- Thực hiện Add new grant
![image](https://user-images.githubusercontent.com/72438169/209893632-b35dbfb2-0201-461b-b837-9f0bb254c020.png)

> Thực hiện Revoke thành công

![image](https://user-images.githubusercontent.com/72438169/209893663-09503a5b-f171-41e7-a382-f48d243f797f.png)
![image](https://user-images.githubusercontent.com/72438169/209893689-eb4ddf81-b9f5-479b-97b7-e00d87d38b6f.png)
![image](https://user-images.githubusercontent.com/72438169/209893713-6f124b99-f623-4f11-9def-cd2806017833.png)

> Add new grant thành công -> Hiển thị thông báo
![image](https://user-images.githubusercontent.com/72438169/209893981-85b82232-a3ef-47ad-9146-08d822d9f1fa.png)

Active tab: Không hiển thị Grant đã được add
![image](https://user-images.githubusercontent.com/72438169/209899829-20a4502e-879b-4232-85ae-57c01cacb8f6.png)

**Comment by Dpthao245** [comment]
- Địa chỉ có Grant hết hạn: aura1zrsq9skzej2puclveds293khdqkmupkz4ejqwh

![image](https://user-images.githubusercontent.com/72438169/210041385-c876c133-4b7d-47f5-8cbd-e576e25b0fea.png)

- Thực hiện Add new grant cho địa chỉ trên

![image](https://user-images.githubusercontent.com/72438169/210041477-58fdd5ea-b015-43de-b382-89c3c76460ed.png)

- Thực hiện Revoke -> thành công
![image](https://user-images.githubusercontent.com/72438169/210041545-ada791f9-1124-43d7-bdf4-978ffb9bec6f.png)
![image](https://user-images.githubusercontent.com/72438169/210041571-ab368337-8f0b-40e2-9f86-3dc19c4cec8b.png)
![image](https://user-images.githubusercontent.com/72438169/210041596-96f3a8eb-fd12-4e05-a6a5-d94ae78f207c.png)

- Add new grant thành công -> hiển thị data
![image](https://user-images.githubusercontent.com/72438169/210041672-ebeca481-b7fb-414e-8b88-3d39d9e6b0b6.png)
![image](https://user-images.githubusercontent.com/72438169/210041722-fe2dfb6b-95aa-49c4-895c-2aba550c9cc5.png)
