### ISSUE TITLE
[Enhance] Remove validate stake condition with user doing action vote proposal

### ISSUE THREAD

**Issue by Thaonguyen541** [aura-nw/aurascan#1341]
User doing action vote proposal
- Before: validate stake condition, only user staked before voting period start moment can vote
- After: remove validate stake condition, all users can vote even user didn't stake before or staked after period start moment

**Comment by ntatfff** [comment]
Verified PASS on serenity (05/12/2022)
- Can vote a proposal before staking
![image](https://user-images.githubusercontent.com/24869170/205595558-c6ed2d1d-c1b9-4389-aa8a-dc77b3f94dc6.png)

- Amount is updated after staking
![image](https://user-images.githubusercontent.com/24869170/205608468-bdff8ebc-94b8-4c8d-944f-4a0ed1dd0a60.png)

**Comment by ntatfff** [comment]
Currrently, there is no data on Euphoria for checking
