### ISSUE TITLE
[Aurascan][Validators] Display data incorrectly after staking

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1359]
**Bug description:** Display data incorrectly after staking
- [x] Delegate: hiển thị dòng data mới, mất dòng data cũ
- [ ] Undelegate: hiển thị 2 dòng data giống nhau ở phần delegations
- [ ] Redelegate: hiển thị dòng data mới, mất dòng data cũ

**Expected result:** Display data correctly after staking

**Screenshot**
![image](https://user-images.githubusercontent.com/24869170/205841693-f3cf465d-1295-4476-bd66-2854baef775a.png)

**Comment by Dpthao245** [comment]
Màn hình Validators: trước khi thực hiện giao dịch

![image](https://user-images.githubusercontent.com/72438169/206084899-bef931db-923a-4d80-8851-ff0432bbe41e.png)

Thực hiện Delegate cho Validator - Vinh
![image](https://user-images.githubusercontent.com/72438169/206084964-81028f56-ab5a-44e4-adbb-74a29bcf986d.png)
![image](https://user-images.githubusercontent.com/72438169/206084981-42d58ecf-b85f-4981-b641-f51db6500ac4.png)
![image](https://user-images.githubusercontent.com/72438169/206085002-71b0163d-fe15-47d7-9e8b-8ee729549789.png)
![image](https://user-images.githubusercontent.com/72438169/206085056-97f109c1-3bd3-49c7-acf0-74aafd0ac008.png)

Thực hiện Undelegate cho Validator - thaibinh
![image](https://user-images.githubusercontent.com/72438169/206085384-30c93fac-6a53-46cf-83d1-55e103c9c168.png)
![image](https://user-images.githubusercontent.com/72438169/206085446-d7f43820-14c1-41e6-b570-2888ce03d636.png)
![image](https://user-images.githubusercontent.com/72438169/206085469-f7811ebb-d0ee-452e-9c34-d750dd2f9369.png)

Thực hiện Redelegate từ validator Vinh- hagiang
![image](https://user-images.githubusercontent.com/72438169/206086802-583a1d14-445c-44da-92e5-a4ea175ccafd.png)
![image](https://user-images.githubusercontent.com/72438169/206086842-6c17b91d-0e8b-483f-9391-33c4f95d79db.png)
![image](https://user-images.githubusercontent.com/72438169/206086898-efb58ff5-c366-442c-a18c-87e29981905e.png)
![image](https://user-images.githubusercontent.com/72438169/206086911-ae0af8e5-bf5f-410f-9ebb-48704f03deb7.png)
![image](https://user-images.githubusercontent.com/72438169/206086974-50334fdb-cf7c-4039-bace-013bd0d41ec7.png)
![image](https://user-images.githubusercontent.com/72438169/206087027-ce4d2bef-3cac-436d-aac8-5040682b2c62.png)

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (26/12/2022)
- Delegate 1 EAURA for validator AlxVoy
https://user-images.githubusercontent.com/24869170/209514559-7247cb30-5ea7-46d6-ada5-7df4b559df6d.mp4

- Undelegate max amount of validator OnBlock Ventures
https://user-images.githubusercontent.com/24869170/209514870-ce949823-2aaf-40de-8acd-26dc7a330705.mp4

- Redelegate max amount from P-OPS Team to Darvin
https://user-images.githubusercontent.com/24869170/209515210-419c42a1-0918-4e90-a5e2-80fe02e23478.mp4
