### ISSUE TITLE
[Aurascan][ContractDetails] Không hiển thị data contract đã được tạo từ Twilight

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#1363]
- [ ] ISSUE: Contract Detail không hiển thị data khi tạo contract từ Twilight

Link Contract: https://serenity.aurascan.io/contracts/aura1p57ex9ssjy9kyz8unj2273enz8kczymhf5jyctvgv7vge5lp92aqmqp6xg
Link Trans: https://serenity.aurascan.io/transaction/C2B5FBA061644EDB2C2202986D87FCB2AEAF95E8A435689C2BBD07EBFB333FF8

![image](https://user-images.githubusercontent.com/72438169/206074410-3868840a-e756-49ba-97d5-673b9421fc4e.png)

**Comment by Dpthao245** [comment]
FAIL in Serenity 19/12/2022

Link Contract: https://serenity.aurascan.io/contracts/aura19n78etsdmsa66psxfuhcwgul7ymhxhdd0hd2dp4ea8gu72jkzghsyw8xex

![Image](https://user-images.githubusercontent.com/72438169/208337495-13fcee24-30e4-4a4e-9ca5-250a3703bda3.png)

**Comment by doquockhanhan** [comment]
@Dpthao245 chị cho e xin tx của cái contract thứ 2 với ạ

**Comment by Dpthao245** [comment]
@doquockhanhan Chị gửi Tx Hash nha
https://serenity.aurascan.io/transaction/D20996615CA2FFC30F701A03D887570EE39968B2FEB7829971F18CE2243E6930

**Comment by doquockhanhan** [comment]
@Dpthao245 bug này fix xog r c nhé

**Comment by Dpthao245** [comment]
Fail in Serenity 20/12/2022

Link Contract: https://serenity.aurascan.io/contracts/aura14medy57ysu2p98u39yk3dzm8778c9aettgg76vw37lzjupzym2es9mxcn9
Link TxHash: https://serenity.aurascan.io/transaction/E7066A4E2F444EA003C751B505A3D9A6902F4B488AB41CE8C6A332B712E00B01

![Image](https://user-images.githubusercontent.com/72438169/208624839-b5745579-9b64-4ebc-89a8-9a6f616db0dd.png)

**Comment by Dpthao245** [comment]
PASS in Serenity 21/12/2022
Contract tạo từ Twilight sau 7s hiển thị data bên Aurascan

Link Contract: https://serenity.aurascan.io/contracts/aura1jhuqcezup5yxa3fm6f3zwvdjrt2y4ql57veleapzazmlhtpdc4tqey4vn0?tabId=transactions

![Image](https://user-images.githubusercontent.com/72438169/208861645-d6b1be1f-0a41-444d-933a-bfe20d99737d.png)


![Image](https://user-images.githubusercontent.com/72438169/208861532-2eac9490-76f8-4965-80bb-a077b0ffbf1a.png)

**Comment by Dpthao245** [comment]
Close ticket vì Twilight không có môi trường tương ứng Aurascan - Euphoria
