### ISSUE TITLE
[Aurascan] Update estimate gas for transactions

### ISSUE THREAD

**Issue by nhphuc2411** [aura-nw/aurascan#1369]
Validators: Delegate, Redelegate, Undelegate, Claim Reward
Votings: Vote
Feegrant: MsgGrantAllowance, MsgRevokeAllowance
Wasm: MsgExecuteContract

**Comment by Dpthao245** [comment]
**Validators**

- Delegate:

https://serenity.aurascan.io/transaction/68CB88A4A7C9A39FB0F592674992A2F1E8DF184D054EAC242ABA37494535E86A
![Image](https://user-images.githubusercontent.com/72438169/206991563-7fa033eb-f16e-4454-a88f-d5f9f67627c7.png)

- Redelegate:

https://serenity.aurascan.io/transaction/04914D985C1790743DBDC0DA21BF7BA610E4E2E0D8B87F52ABE203AF89B150FF
![Image](https://user-images.githubusercontent.com/72438169/206991770-55e43acc-f913-4c17-9ab6-f4f549704f4c.png)

- Undelegate:

https://serenity.aurascan.io/transaction/48B7903F14B69518CF7EABACC39FD797826A7E255259B2B2D03C78322661F2AF
![Image](https://user-images.githubusercontent.com/72438169/206991940-f5c3d529-a091-4b86-ad46-108eacc1a131.png)

- Claim Reward:

https://serenity.aurascan.io/transaction/25B03C1F82A4CFCB3A359661FEE6DA495B7B455B86419663C1709B5F90339A42
![Image](https://user-images.githubusercontent.com/72438169/206992109-0cbfa222-2552-4b95-a7a7-d2f545c2009a.png)

**Excute Contract**

- Mint:

https://serenity.aurascan.io/transaction/1C7B11AC1348BBBDF6FF16418211E63C05D92071A6EA0434A8B542F533C71A97
![Image](https://user-images.githubusercontent.com/72438169/206994577-41b699ec-22d3-4378-b39d-e0e90a67dc25.png)

- Burn:

https://serenity.aurascan.io/transaction/B3FE55C39F7DF0571B0A57B04D7034F7575A707FD8BB559872EE2AD816B8E7F2
![Image](https://user-images.githubusercontent.com/72438169/206994815-3b2cd8d4-26a9-4394-bfe4-0e9145084b9a.png)

- Transfer:

https://serenity.aurascan.io/transaction/DF19FDB7942803529C8DBEFE7E2336F2D4E083CFBF24C45C1D3AF70E9DBE497C
![Image](https://user-images.githubusercontent.com/72438169/206995328-359848d1-05bb-4aac-b2cb-d43451575dc3.png)

**Fee Grant**

- Add Grant

https://serenity.aurascan.io/transaction/BCFFAD652FE1144BE8A2DDCBE6C57361E3F05D6EFDB91BE5BF926225683117F7
![Image](https://user-images.githubusercontent.com/72438169/206995660-23ef1a3f-950f-4727-ac2c-e3d5706a5344.png)

- Revoke

https://serenity.aurascan.io/transaction/BC2AAAB25DC6987A5B227C1D59CB86DC970FA9FE2D5405C95288F2DBA3D6D82F
![Image](https://user-images.githubusercontent.com/72438169/206995860-c63ea1f6-33e2-4a64-931a-15532b1e6df6.png)

**Comment by Dpthao245** [comment]
**Validators**

- Delegate:
https://euphoria.aurascan.io/transaction/31FEB3FF6E4DD414AFC4EB607250A64CDAA5FBE3162DFF2E5D7C4C4CA429017E
![image](https://user-images.githubusercontent.com/72438169/209641413-23f43997-71cb-4794-b71e-2600ea7ded02.png)

- Redelegate:
https://euphoria.aurascan.io/transaction/CA17C8A1A0C5D05628320942D62AD54EBEF1D09A1FA531816DD9511521044A95
![image](https://user-images.githubusercontent.com/72438169/209641667-68d4b72a-41c1-4862-9bd5-b9d4b380144d.png)

- Undelegate:
https://euphoria.aurascan.io/transaction/64B28FD248904D30DBBE7D0DC2628177DF1B8294C6A70CAC9525892A8EE562AD
![image](https://user-images.githubusercontent.com/72438169/209641900-e0f0fc45-0953-4d45-94c8-f27f5dcdd562.png)

- Claim Reward:
https://euphoria.aurascan.io/transaction/DB07811852205B280AEAAD87E1A894004E4EE73875143BF56BA11907154D05C6
![image](https://user-images.githubusercontent.com/72438169/209642209-a1954c8c-c2ef-40bd-a013-a9a88552892a.png)

**Fee Grant**

- Add Grant:
https://euphoria.aurascan.io/transaction/ABE94E29C1C11B520BE38F5ACCDB5AABB5629375E7A74FC49E2777545740C920
![image](https://user-images.githubusercontent.com/72438169/209642533-237bddec-8d5c-48ad-bcc5-76e00a10a78d.png)

- Revoke:
https://euphoria.aurascan.io/transaction/513B6E802930C28F7823EEC4E6F9511B8331DFDE36ABAC90B2BA0B3BB917CD73
![image](https://user-images.githubusercontent.com/72438169/209642666-3217b945-ac81-4136-a1f7-1c89ae6f2c7b.png)

**Excute Contract**

- Mint:
https://euphoria.aurascan.io/transaction/A43D205C17116A9AB60015E251B4B503D5510599F922CEAC0876259466B572D2
![image](https://user-images.githubusercontent.com/72438169/209643983-9003fd9f-e630-4901-9b89-3283b90392e0.png)

- Transfer:
https://euphoria.aurascan.io/transaction/8706A1574C54F011F9AF2DA3C092C023D17ADA15091E267F319C3A1A503D98D6
![image](https://user-images.githubusercontent.com/72438169/209645034-849322ed-a954-46a2-9ac8-62a4026edda3.png)

- Burn:
https://euphoria.aurascan.io/transaction/53D417882889CE636807D54895B0059D57B2BBD49DB411997C7FCA06745ACB96
![image](https://user-images.githubusercontent.com/72438169/209645246-381f9271-ed03-4632-a816-e4a3bcea91e4.png)
