### ISSUE TITLE
[Aurascan][Contracts] Display search results incorrectly

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1376]
**Bug description:** Display search results incorrectly

Steps:
1. Go to Contracts list screen: https://serenity.aurascan.io/contracts
2. Input search value: "CW20"
3. Display contract names related to text "CW20"
4. Wait about 10-20s
5. See error

**Actual result:** Display other contracts (not related to text "CW20") after waiting time
**Expected result:** Display contracts related to inputted searching value

**Comment by Dpthao245** [comment]
PASS in Serenity 08/12/2022

Input search value: "CW20"
![image](https://user-images.githubusercontent.com/72438169/206416003-a8e09c1e-e81a-491b-9a07-2d40f38d1dfb.png)

Click Enter after 20s, display contract detail (the first contract of list search)
![image](https://user-images.githubusercontent.com/72438169/206416247-d64e512c-6cf1-4714-a020-5bbfb55c561a.png)

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (27/12/2022)
- Input search value: "CW20"
- Click Enter after 20s, display contract detail (the first contract of list search)
https://user-images.githubusercontent.com/24869170/209635713-6a296b6c-4739-4ec0-a4e8-a1e093b157ff.mp4
