### ISSUE TITLE
[Feegrant] Revise add new fee grant pop up design

### ISSUE THREAD

**Issue by Thaonguyen541** [aura-nw/aurascan#1383]
Field "Allowed Activities": bỏ option "Instantiate Contract"
Trong option "Execute Contract" của field "Allowed Activities": bỏ option "All smart contracts"
![image](https://user-images.githubusercontent.com/79354422/206952306-28984f26-a56d-4ebc-baf7-595fa75b3c9c.png)

**Comment by Dpthao245** [comment]
PASS in Serenity 12/12/2022
Add New Grant: updated UI
![image](https://user-images.githubusercontent.com/72438169/206997560-606b556f-24bd-454d-8b2a-ac618c2107a4.png)
![image](https://user-images.githubusercontent.com/72438169/206997965-a607728f-deb5-4abd-944a-73c9a29427fe.png)

**Add Grant: không check Execute contract, type Basic**

![image](https://user-images.githubusercontent.com/72438169/206998497-50df69a8-f345-42ed-8732-9a0fa240f1a8.png)
![image](https://user-images.githubusercontent.com/72438169/206998700-40914f64-ab68-4ded-af2d-36c2b2f8291f.png)
![image](https://user-images.githubusercontent.com/72438169/206998807-6087191f-e475-41f9-b0f3-9007bf40defa.png)

**Add Grant: không check Execute contract, type Period**

![image](https://user-images.githubusercontent.com/72438169/206999049-95cc3c9a-daa7-4bc6-9844-ee65510d0099.png)
![image](https://user-images.githubusercontent.com/72438169/206999100-cd396ea2-51be-4f98-8a4f-77bf88b27e64.png)
![image](https://user-images.githubusercontent.com/72438169/206999191-e3dd21eb-f8bb-41a2-8730-6fb19941c668.png)

**Add Grant: checked Execute contract, type Basic**
![image](https://user-images.githubusercontent.com/72438169/207000162-68943e0c-7d11-41db-8009-531ce06d67be.png)
![image](https://user-images.githubusercontent.com/72438169/207000230-4182bf03-9143-4132-b2ae-ce73a4e928a9.png)
![image](https://user-images.githubusercontent.com/72438169/207000295-ce2f45c4-a7c7-4180-abff-24b9f022aba4.png)

**Add Grant: checked Execute contract, type Period**

![image](https://user-images.githubusercontent.com/72438169/206999718-634374d5-500e-4362-9c07-1444630328d1.png)
![image](https://user-images.githubusercontent.com/72438169/206999781-a37cd0aa-584c-4bcc-b65a-e729a53e6d67.png)
![image](https://user-images.githubusercontent.com/72438169/206999917-77e34790-5698-455c-b22b-b93ba59ef4e4.png)

**Revoke**
![image](https://user-images.githubusercontent.com/72438169/207000490-0d716381-2007-4e3a-9932-851672804769.png)
![image](https://user-images.githubusercontent.com/72438169/207000549-20ff0b71-76c3-4a0c-b038-7f4784dbe65a.png)
![image](https://user-images.githubusercontent.com/72438169/207000575-0f407fa4-bd44-49c0-bd52-5690a10018f9.png)
![image](https://user-images.githubusercontent.com/72438169/207000629-695faee2-8158-474d-b69f-369ce9213b16.png)

**Add Grant: Address có grant hết hạn**
![image](https://user-images.githubusercontent.com/72438169/207001736-2db8170f-7447-406d-86b9-3d8674d40aa2.png)
![image](https://user-images.githubusercontent.com/72438169/207001807-0dd6301b-dc84-4fcf-af63-54cb1a715f6f.png)
![image](https://user-images.githubusercontent.com/72438169/207001883-08261891-12ec-476d-adcd-06fdb5323792.png)
![image](https://user-images.githubusercontent.com/72438169/207001966-409aa511-e478-4c8a-add9-fb824841e8f0.png)
![image](https://user-images.githubusercontent.com/72438169/207002051-be6972b3-4721-4e9c-8bc2-9d57a1db0d24.png)

**Comment by Dpthao245** [comment]
PASS in Euphoria 27/12/2022
![image](https://user-images.githubusercontent.com/72438169/209635513-f961821a-f7db-463b-a36c-a5b131c9eafb.png)
![image](https://user-images.githubusercontent.com/72438169/209635552-a9afad59-3c09-4d96-b687-ce61d980c5d2.png)
