### ISSUE TITLE
[Feature] Social share for NFT/SBT (Soulbound Token)

### ISSUE THREAD

**Issue by Thaonguyen541** [aura-nw/aurascan#1396]
Add new feature: social share button for NFT/SBT detail page. 4 available options include facebook, telegram, discord, tweeter and add more "copy link" option.
Content to share: url link of token detail (NFT/SBT)
Mock up: https://drive.google.com/file/d/16rz-k46dsFG836SSc3DK4wbPun_7bTGu/view?usp=sharing
Design: https://www.figma.com/file/xiW41QvCutlazTw9PSQC01/%5BAura%5D-Scan?node-id=6317%3A374449&t=MVSa4nldAhdbRgrz-0

Example: Share NFT from open sea: https://opensea.io/assets/ethereum/0x231d3559aa848bf10366fb9868590f01d34bf240/6456
--> facebook share link: https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fopensea.io%2Fassets%2Fethereum%2F0x231d3559aa848bf10366fb9868590f01d34bf240%2F6456%2F
![image](https://user-images.githubusercontent.com/79354422/208369261-6aa08595-c21e-4d80-8b89-524ba32b6d26.png)

---> tweeter share link: https://twitter.com/intent/tweet?text=Check%20out%20this%20item%20on%20OpenSea&url=https%3A%2F%2Fopensea.io%2Fassets%2Fethereum%2F0x231d3559aa848bf10366fb9868590f01d34bf240%2F6456%2F&via=opensea&original_referer=https://opensea.io/assets/ethereum/0x231d3559aa848bf10366fb9868590f01d34bf240/6456
![image](https://user-images.githubusercontent.com/79354422/208369147-64cd4381-0cb5-4d28-b4dc-424aa100b9ae.png)

**Comment by Dpthao245** [comment]
Discord thì chỉ cần mở discord thôi. Còn tele thì mình sẽ chọn được địa chỉ để send link qua tele

- Expect là discord thì mình sẽ mở link discord https://discord.com/app sau đó user sẽ tự copy link và paste vào channel mình muốn

![Image](https://user-images.githubusercontent.com/72438169/209598021-7a479531-4396-4196-9d2a-5dd3865178a2.png)

- Còn tele thì sẽ có share link qua tin nhắn

![Image](https://user-images.githubusercontent.com/72438169/209598092-ae7e67a9-4904-4963-8b93-0ce4376dd2b0.png)

- Khi ấn vào nút share thì sẽ chọn địa chỉ nhận

![Image](https://user-images.githubusercontent.com/72438169/209598118-e3991baa-3d71-4253-8383-c7709569784a.png)

- Sau khi chọn địa chỉ nhận thì nội dung tin nhắn sẽ auto fill link của token details

![Image](https://user-images.githubusercontent.com/72438169/209598154-855c91e1-62c9-4a3d-8b31-17dde36b3271.png)

**Comment by ntatfff** [comment]
Verified PASS on serenity (28/12/2022)
UI bug https://github.com/aura-nw/aurascan/issues/1421: PASS
![image](https://user-images.githubusercontent.com/24869170/209780584-8dae93d3-a33f-4a2d-928e-ae3a506439f5.png)

Share functions: PASS
- Desktop: 
https://user-images.githubusercontent.com/24869170/209780232-7ae2e6ee-5955-4786-92b8-578b3e4d4ce3.mp4
- Mobile: 
https://user-images.githubusercontent.com/24869170/209780394-4e0d385c-1a63-49bb-a033-5d5b58bd2bc1.mp4

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (28/12/2022)
https://user-images.githubusercontent.com/24869170/209786372-5593585c-7b86-4121-852b-fb7742db0ae8.mp4
- Telegram
![image](https://user-images.githubusercontent.com/24869170/209786613-2e673334-801d-4e1f-88b3-204b9ea7b202.png)
- Facebook
![image](https://user-images.githubusercontent.com/24869170/209786640-8b02ba46-dc82-4762-bd76-4c9ea3c06a3f.png)
- Tweeter
![image](https://user-images.githubusercontent.com/24869170/209786677-1e965be1-d536-46ef-be7e-c1451872b4be.png)
- Discord
![image](https://user-images.githubusercontent.com/24869170/209786727-e464508b-5250-4c55-8b6f-5a158133c38f.png)
