### ISSUE TITLE
[Aurascan][MyGrantees] Inactive tab không hiển thị Transaction Revoke khi Grant hết hạn

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#1397]
- [ ] ISSUE: My Grantees - Inactive tab: không hiển thị transaction Revoke khi Add New Grant với địa chỉ có Grant hết hạn

- Địa chỉ có Grant hết hạn: aura1ja249ang2pm6df08j534w4ezwqnuqh7lj44yf8

- Thực hiện Add New Grant với địa chỉ aura1ja249ang2pm6df08j534w4ezwqnuqh7lj44yf8

- Thực hiện Revoke thành công

![image](https://user-images.githubusercontent.com/72438169/208584321-d035a3c2-c367-40d6-bec0-efca84ede617.png)
![image](https://user-images.githubusercontent.com/72438169/208584390-241a107d-5ca4-4cc4-9e32-0ffdb93ebead.png)
![image](https://user-images.githubusercontent.com/72438169/208584448-69dab8e4-280b-4300-86a5-9aa37c545249.png)
![image](https://user-images.githubusercontent.com/72438169/208584477-0c106787-cc83-4f45-8695-f0d231b9d5e5.png)

- Tab Inactive không hiển thị transaction Revoke

![image](https://user-images.githubusercontent.com/72438169/208584532-36684356-4925-444a-bf93-d089984490e1.png)

**Comment by Thaonguyen541** [comment]
Cái này phải là bug chứ e nhỉ? @Dpthao245

**Comment by Dpthao245** [comment]
> Cái này phải là bug chứ e nhỉ? @Dpthao245
Task Enhancement 1399 này giải quyết được Issue 1397 thì sao là bug được chị?
https://github.com/aura-nw/aurascan/issues/1399

**Comment by Thaonguyen541** [comment]
Trong cái enhancement 1397 có đề cập đến việc phải có transaction revoke ở tab inactive rồi, giờ phải chờ issue đó xử lý xong thì mình mới test. Nếu test không đúng luồng mô tả như 1397 thì sẽ là bug.

**Comment by nhphuc2411** [comment]
trùng 1399
