### ISSUE TITLE
[Feegrant] Enhancement flow for expired allowance

### ISSUE THREAD

**Issue by Thaonguyen541** [aura-nw/aurascan#1399]
1. Allowance that is expired will be listed in "Active" tab. After revoked, the allowance will be removed from "Active" tab and move to "Inactive tab" with reason "Revoke".
2. Highlight expired allowance in "Active tab". Color #D5625E
![image](https://user-images.githubusercontent.com/79354422/208611193-f1995f92-dd58-43c1-b3b3-f3dbb44937c8.png)

**Comment by Dpthao245** [comment]
PASS in Serenity 27/12/2022
![image](https://user-images.githubusercontent.com/72438169/209599768-0b06dc14-fb6a-4088-bc2a-424613e5e5f3.png)
![image](https://user-images.githubusercontent.com/72438169/209599788-0e531d1d-1c3d-447d-92e2-6fd8938720f7.png)

Thực hiện Revoke
![image](https://user-images.githubusercontent.com/72438169/209599882-dc844752-b62b-4afb-b7de-80fc154041ec.png)
![image](https://user-images.githubusercontent.com/72438169/209599921-51da6614-a8db-4a87-b1e9-9673c85d2601.png)
![image](https://user-images.githubusercontent.com/72438169/209599970-30d1d5c3-2e98-4b38-8adc-75adc1c9238a.png)

**Comment by Dpthao245** [comment]
PASS in Euphoria 29/12/2022
![image](https://user-images.githubusercontent.com/72438169/209893279-10ebff1a-a53b-40d4-ba3e-a9910cc66329.png)

- Thực hiện Revoke từ button Revoke

![image](https://user-images.githubusercontent.com/72438169/209893354-f2778901-eb48-43b3-8430-f4fe5dde5527.png)
![image](https://user-images.githubusercontent.com/72438169/209893382-a43e3159-7b0c-45d1-8e49-de21fcc43017.png)

> Active tab: remove data

![image](https://user-images.githubusercontent.com/72438169/209893409-e73c3aa8-66bb-4cd7-b121-f032c94dc9e1.png)

> Inactive tab: dispay data with reason "Revoke"

![image](https://user-images.githubusercontent.com/72438169/209893451-cdaa5f8e-018f-4331-a654-0f9dde786664.png)

> Transaction Details - Revoke

![image](https://user-images.githubusercontent.com/72438169/209893489-ca4d189c-6ad2-401c-aa28-42f03cae343e.png)

- Thực hiện Revoke qua Add New Grant
![image](https://user-images.githubusercontent.com/72438169/209893637-610482fe-c568-40b5-9cbf-925ed1269357.png)
![image](https://user-images.githubusercontent.com/72438169/209893667-b56f8bf4-f513-4438-baf8-3ea1dae85ebc.png)
![image](https://user-images.githubusercontent.com/72438169/209893685-558eb078-6d41-4920-b4d8-9e5a59b9a9ab.png)
![image](https://user-images.githubusercontent.com/72438169/209893731-801085e3-c32f-42b4-ae95-3192a3921215.png)

> Inactive tab: dispay data with reason "Revoke"
![image](https://user-images.githubusercontent.com/72438169/209893765-6b0ca915-58cd-4207-915c-8f4ef5183896.png)

> Transaction Details - Revoke
![image](https://user-images.githubusercontent.com/72438169/209893799-b2e184be-208c-4d64-a1e4-216cdad95404.png)
