### ISSUE TITLE
[Aurascan] Depositor - change API from LCD to indexer

### ISSUE THREAD

**Issue by nhphuc2411** [aura-nw/aurascan#1400]
Depositor 
https://indexer.dev.aurascan.io/api/v1/transaction?chainid=aura-testnet-2searchType=proposal_deposit&searchKey=proposal_id&searchValue=368

**Comment by ntatfff** [comment]
Verified PASS on serenity (21/12/2022)
https://user-images.githubusercontent.com/24869170/208848102-1130e78d-54dc-465e-a490-4f4d0ee70b8b.mp4
https://user-images.githubusercontent.com/24869170/208848305-65682732-07ac-403d-b6d0-b2a6aa445b1e.mp4

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (26/12/2022)
![image](https://user-images.githubusercontent.com/24869170/209511721-a6291265-fd38-4424-b777-61407fd4bf1d.png)
