### ISSUE TITLE
[Soulbound Token] Enhance flow for soulbound token receiver

### ISSUE THREAD

**Issue by Thaonguyen541** [aura-nw/aurascan#1402]
Improve flow for soulbound token receiver: 
Flow: https://drive.google.com/file/d/1VecPQjj58nsJwtT0REERNPP1F5gCvDec/view?usp=sharing
Design: https://www.figma.com/file/xiW41QvCutlazTw9PSQC01/%5BAura%5D-Scan?node-id=6174%3A267940&t=0VMPgeRGMlksajQz-11

1. ban đầu khi user có token đầu tiên đang ở trạng thái unclaim, cần hiển thị UI giống với token unclaim ở tab unequipped (phủ mờ + marking "Unclaimed" + hiện button "Preview" khi hover đến). 

![Soulbound Token-My account (1) drawio (3)](https://user-images.githubusercontent.com/79354422/208813108-8ef4f1aa-84bd-4ccb-aa17-73477f5a6605.png)

2. User có thể equip unclaimed Token ngay trên giao diện my account detail. User click "Preview" -->  hiện pop up preview --> equip token như flow đang có. 

3. Với 5 token đầu tiên được equip sẽ tự động được pick để show trên giao diện top 5 token display. Sau khi có nhiều token hơn nếu user muốn pick token khác thì sẽ vào trang soulbound token page để unpick/pick token ở tab equiped

4. Trang my account display tối đa 5 token unclaimed đầu tiên, nếu equip nhỏ hơn 5 token --> hiển thị song song vừa token unclaimed và token equip trên top 5 display. 

![Soulbound Token-My account (1) drawio (4)](https://user-images.githubusercontent.com/79354422/208814037-dc849988-abd8-478e-bd53-be586a0171b6.png)

5. Bên trang Validator profile thì nếu equip nhỏ hơn 5 token vẫn chỉ hiện các token equipped, không hiện token unclaimed

6. Thêm điều kiện check khi user thực hiện Un-equip SBT: 
If [The total (quantity of picked SBT token
                    + quantity of unclaimed token) is less than 1
    and quantity of equipped token is equal 1?] 
--> If yes: Do not un equip the SBT token and show the message: "Currently, you don't have any picked SBT Token or Unclaimed SBT Token so you can not un-equip the last Equipped SBT token in your account"
--> If no: Unequip the SBT Token

7. Thêm điều kiện check khi user thực hiện Un-pick the picked equipped token:
If [The quantity of picked SBT token is equal 1 and quantity of unclaimed token is less than 1]
--> If yes: Do not un-pick the selected SBT and show message "Currently , you don't have any unclaimed SBT Token so you can not un-pick the last picked SBT Token in your account"
--> If no: Un-pick the selected SBT

**Comment by Dpthao245** [comment]
Update 06/01/2023
![image](https://user-images.githubusercontent.com/72438169/211706636-20e26a81-12f4-4eee-8b31-54bdbf815320.png)

- Điều kiện check khi un-pick/un-equip token: "The (quantity of picked SBT token is more than 1 or not?" nếu không pass điều kiện check thì không cho un-pick/un-equip token. 

> Show message nếu action là un-pick :"You can not un-pick the last picked SBT in your account. In order to un-pick this token, you need to pick another equipped SBT first then un-pick it later". 
> Show message nếu action là un-equip: "You can not un-equip the last picked SBT in your account. In order to un-equip this token, you need to pick another equipped SBT first then un-equip it later"

- Điều kiện show top 5 token displayed: 

> Nếu có 1-5 token unclaimed và chưa equip cái nào: show hết số token unclaimed lên top 5 displayed
> Nếu có nhiều hơn 5 token unclaimed và chưa equip cái nào: show 5 token unclaimed đầu tiên lên top 5 displayed
> Nếu user equip 1-5 token đầu tiên--> auto pick và show picked token + unlaimed token trên giao diện để tổng lượng component lên top 5 displayed =5 

- Điều kiện auto pick SBT: chỉ auto pick equipped SBT cho 5 lần equip đầu tiên không phân biệt đó là token nào

**Comment by Dpthao245** [comment]
- Message khi un-equip the last SBT

![image](https://user-images.githubusercontent.com/72438169/211707408-b0d345a2-71f9-4d63-914c-e0aa28f70aa8.png)

- Message khi un-pick the last SBT

![image](https://user-images.githubusercontent.com/72438169/211707774-d6179e8c-ff77-4a6a-bcb5-2d04304aba2e.png)

**Comment by Dpthao245** [comment]
- User có token unclaim, phủ mờ + marking "Unclaimed" + hiện button "Preview" khi hover

![image](https://user-images.githubusercontent.com/72438169/211711478-cb834f07-753c-4c91-8973-b2e1ec3cf234.png)
![image](https://user-images.githubusercontent.com/72438169/211711637-d55bdd8c-0187-4f58-a055-2992179a40a6.png)

- User equip unclaimed Token ngay trên giao diện my account detail
![image](https://user-images.githubusercontent.com/72438169/211711739-2555c780-f74a-4557-bfbd-3c10b1d1c7b9.png)
![image](https://user-images.githubusercontent.com/72438169/211711777-ffe51b20-9564-4d2f-b3d1-66038e947e80.png)

**Comment by Dpthao245** [comment]
FAIL in Serenity 11/01/2023

Điều kiện auto pick SBT: chỉ auto pick equipped SBT cho 5 lần equip đầu tiên không phân biệt đó là token nào
-> Hiện tại equip 6 SBT unclaim thì đang auto pick

**Comment by Dpthao245** [comment]
PASS in Serenity 12/01/2023
Thực hiện equip 6 SBT unclaim, trong đó un-eqiup 1 SBT thì auto pick 5 SBT unclaim đã equip
![image](https://user-images.githubusercontent.com/72438169/211998584-c933131a-e7bf-4b1e-9750-fdfa9ef3cd48.png)
