### ISSUE TITLE
[Aurascan] Voted - change API from LCD to indexer

### ISSUE THREAD

**Issue by nhphuc2411** [aura-nw/aurascan#1404]
Voted
https://indexer.dev.aurascan.io/api/v1/transaction?chainid=aura-testnet-2searchType=proposal_vote&searchKey=proposal_id&searchValue=367&queryAnd%5B%5D=transfer.sender%3Daura15f6wn3nymdnhnh5ddlqletuptjag09tryrtpq5

**Comment by ntatfff** [comment]
Verified PASS on serenity (21/12/2022)
[2022-12-21_16h45_01.zip](https://github.com/aura-nw/aurascan/files/10276567/2022-12-21_16h45_01.zip)
