### ISSUE TITLE
[Aurascan][Tokens][CW-20] Not update marketing information

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1411]
**Bug description:** Not update marketing information
- description
- marketing
- project
- logo

- Indexer link: https://indexer.staging.aurascan.io/openapi/#/Smart%20Contracts/get_v1_smart_contracts
- Contract address: aura1kzkrwzar8t6g9x3cr4f7k7esqcumvj7hzc8eeh0vuz9g75w37xss3n6rjd

**Expected result:** Update maketing information
- [x] description: at read contract tab (Token/Contract details) and Tokens CW20 list
- [x] marketing
- [x] project: at read contract tab (Token/Contract details)
- [ ] logo
![image](https://user-images.githubusercontent.com/24869170/209319870-c8888572-b0a3-4650-9a45-1d26bfa7ce90.png)

**Comment by thanhhao1986** [comment]
@ntatfff check the case again:
1/ Update data Max Total Supply of CW721.
2/ Update data Description, Image of CW20.

**Comment by ntatfff** [comment]
Wait for the ticket is fixed to verify https://github.com/aura-nw/horoscope/issues/192

**Comment by ntatfff** [comment]
Verified PASS on serenity (10/01/2023)
![image](https://user-images.githubusercontent.com/24869170/211463329-e837521a-d7e6-41bd-a73a-6e94b82bf954.png)
