### ISSUE TITLE
[Aurascan][CW721][TokenDetails] Not display text "More" in the record of Batch_mint Transactions

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1432]
**Bug description:** Not display text "More" in the record of Batch_mint Transactions ()

**Link:** https://explorer.dev.aura.network/tokens/token-nft/aura17u523tw6l2a7hn00n0fgg23upuetdcvp2tuykdjf22n5vrrleussn8ps7g

**Expected result:** Display text "More" in the record of Batch_mint Transactions
![image](https://user-images.githubusercontent.com/24869170/211266451-9c3aca73-20fe-4c32-af33-7b2f3b40901b.png)

**Comment by Dpthao245** [comment]
PASS in Serenity 13/01/2023


![Image](https://user-images.githubusercontent.com/72438169/212277201-df997fd4-4c56-4340-8ff2-0382402723ed.png)

**Comment by Dpthao245** [comment]
Box chưa có môi trường tương ứng Aurascan - Euphoria để check ticket này
