### ISSUE TITLE
[Southbound][AccountDetail][Mobile] Some issue UI

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#1454]
- [ ] ISSUE 01: "Soulbound Token (SBT)" -> 22px / 700
![image](https://user-images.githubusercontent.com/72438169/211966451-f7cb96e0-152a-4082-933d-0ecd42b971bf.png)

- [x] ISSUE 02: "X SBT" -> 22px
![image](https://user-images.githubusercontent.com/72438169/211966526-4770c958-085a-4056-8474-dc258f71e3f5.png)

- [x] ISSUE 03: "Equipped" , "Un-equipped" -> 14px
![image](https://user-images.githubusercontent.com/72438169/211966600-729bae85-3f51-4c7d-8f5d-83b2d609fd42.png)

- [x] ISSUE 04: Token Name, Token ID -> 12px
![image](https://user-images.githubusercontent.com/72438169/211966810-a568c835-773a-4b74-a1dd-66d571067983.png)

- [x] ISSUE 05: Name of SBT -> Hiển thị 1 hàng
![image](https://user-images.githubusercontent.com/72438169/211966713-a8d339f2-e8ba-42c0-8b94-e8d0c27aac93.png)

- [x] ISSUE 06: Data of Propotied -> #FFFFFF
![image](https://user-images.githubusercontent.com/72438169/211966924-9da98ec1-f375-4ca7-9fb0-7cf9628b2341.png)

- [x] ISSUE 07: Vị trí mũi tên
![image](https://user-images.githubusercontent.com/72438169/211967138-17de9c29-4322-45da-b39d-018631a5e67a.png)

**Comment by mtamkg** [comment]
Issue 1 không fix, đang đồng bộ với title của những màn hình khác

**Comment by Dpthao245** [comment]
PASS in Serenity 13/01/2023

ISSUE 02

![Image](https://user-images.githubusercontent.com/72438169/212266522-ea94fbab-14a0-46ff-8d8b-97253f34c492.png)

ISSUE 03

![Image](https://user-images.githubusercontent.com/72438169/212266668-fcb934ca-1620-4914-91cb-3a2a505135ef.png)

ISSUE 04

![Image](https://user-images.githubusercontent.com/72438169/212266882-48f01890-ad0b-4399-9162-01ce63b63d6f.png)

ISSUE 05

![Image](https://user-images.githubusercontent.com/72438169/212267495-c953e9e2-c526-43a2-8426-84c2fa165137.png)

ISSUE 06

![Image](https://user-images.githubusercontent.com/72438169/212267813-759ee5d7-6813-453a-adba-3a2c6b601bdd.png)

ISSUE 07

![Image](https://user-images.githubusercontent.com/72438169/212268142-ec2df914-cd2b-4ca3-aadc-9ab1572314c0.png)
