### ISSUE TITLE
[Southbound][SmartContractsList] Hiển thị số lượng CREATED DATA, CLAIMED QTY khi Mint SBT dưới Command line

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#1457]
- [ ] ISSUE 01: Hiển thị số lượng CREATED DATA, CLAIMED QTY khi Mint SBT dưới Command line

Transaction Detail: https://serenity.aurascan.io/transaction/73624D5466897AC82637BE6069C9D16A8F044C1257436593281C92F07FB227F2

![image](https://user-images.githubusercontent.com/72438169/212258086-8603b809-f12b-4903-b16e-337998838b60.png)
![image](https://user-images.githubusercontent.com/72438169/212258152-e6ffe950-72ee-4866-b276-bc30c765a9bc.png)
![image](https://user-images.githubusercontent.com/72438169/212258207-db291601-54db-4d27-bfb0-d5dc7d53c750.png)

- [ ] ISSUE 02: Token Detail: Click nút View SBT -> không link tới SBT Details mà hiển thị Dashboard

Link: https://serenity.aurascan.io/tokens/token-nft/aura105d4z08hdpmvryqhplh28z4xe0jajjl46xdwkfz6ggk0s99pjgjs9xg048

![image](https://user-images.githubusercontent.com/72438169/212259083-07948494-e21e-4973-a4bc-be0a9cab6620.png)
![image](https://user-images.githubusercontent.com/72438169/212259171-235acd4a-0b17-4808-a7a5-cc69d403e342.png)

**Comment by nthduc95** [comment]
Hi @Dpthao245, theo như comfirm với chị @Thaonguyen541  về việc mint SBT dưới dạng cmd line thì ticket này sẽ log lên taiga để mình enhance sau này nha.

**Comment by Dpthao245** [comment]
https://taiga.aura.network/project/aurascan-2/issue/23
