### ISSUE TITLE
[Explorer] Message content issues

### ISSUE THREAD

**Issue by hangpham23** [aura-nw/aurascan#224]
Contents of messages are not correct.

- [ ] 1. Select Reject on Keplr pop up for verify claim reward > "Error get reward" message

- [x] 2. Redelegate to a validator for more than 7 times > "You must wait 21 days in order to be able to redelegate from the 'To' validator" (wrong validator name)

- [x] 3. Double click Redelegate after selecting validator and fill up redelegate amount > "Error redelegate" (still show Keplr verify popup)

- [ ] 4. Select Reject on Keplr pop up for verify Redelegate > "Error redelegate" message 

- [ ] 5. Select Reject on Keplr pop up for verify Delegate > "Error delegate" 

- [ ] 6. Select Reject on Keplr pop up for verify Undelegate > "Error Undelegate" 

- [ ] 7. Could not sync data of validator/validator's data is error > validator does not exist/ not found

- [x] 8. Don't have notication for successful transaction

**Expected behavior**
1. Claim reward unsuccessfully!
2. You must wait 21 days in order to be able to redelegate from the selected validator.
3. Don't show error message
4. Redelegate unsuccessfully!
5. Delegate unsuccessfully!
6. Undelegate unsuccessfully!
7. Validator is temporary invalid
8. Successful transaction!

**Screenshots**
![Screen Shot 2022-04-25 at 13 51 19](https://user-images.githubusercontent.com/102220123/165050082-9ac9ffee-93da-4727-8383-151e009bdda0.png)
![Screen Shot 2022-04-25 at 13 58 13](https://user-images.githubusercontent.com/102220123/165050089-0415abbf-a1c5-469b-9345-7742e0d3c9f8.png)
![Screen Shot 2022-04-25 at 14 23 23](https://user-images.githubusercontent.com/102220123/165050092-c08c4bdc-7b25-42b1-bbed-090c22928ae8.png)
![Screen Shot 2022-04-25 at 14 23 49](https://user-images.githubusercontent.com/102220123/165050096-ff71b2d5-d17f-42d1-a9d5-aee351dd2950.png)

**Desktop (please complete the following information):**

**Comment by nhphuc2411** [comment]
Refer https://www.notion.so/aura-network/Message-error-65c69bf361b649f0ae73a0efc0194997
