### ISSUE TITLE
[Aurascan][Dashboard] Kiểm tra hiển thị số lượng Transaction trên Euphoria

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#657]
**Describe the bug**
Kiểm tra hiển thị số lượng Transaction trên biểu đồ đang thể hiện không đúng.
Số lượng transaction của DB 378,672 và influxdb 94107

**Screenshots**

![Image](https://user-images.githubusercontent.com/72438169/180128158-bccf0c1b-39b7-4a48-9bca-8d5f86d3dcf5.png)

![Image](https://user-images.githubusercontent.com/72438169/180128287-893c36ee-79ed-4c30-adfd-eeef8d20144b.png)

**Comment by Dpthao245** [comment]
PASS Dev 28/07/2022


![Image](https://user-images.githubusercontent.com/72438169/181481349-541b2764-5542-4097-9487-705768f4b8bb.png)

**Comment by tuanbass** [comment]
Các commit/PR nào đê sửa bug nay @thanhhao1986  cũng reference vào trong này luôn nhé 
(Tương tự với các bug khác )

**Comment by thanhhao1986** [comment]
@tuanbass dạ anh, em commit và squash nó luôn rồi, giờ em note các file đã thay đổi và và nội dung thay đổi được ko anh?

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (29/07/2022)
![image](https://user-images.githubusercontent.com/24869170/181732154-5a7e0717-7743-4a1f-a419-1d652034dbb8.png)
