### ISSUE TITLE
[Aurascan][C98][ConnectWallet] Có thể kết nối ví đã logout trước đó khi chưa nhập password ở ví C98

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#665]
**Describe the bug**
Có thể kết nối ví đã logout trước đó khi chưa nhập password ở ví C98

**To Reproduce**
1. Go to https://explorer.dev.aura.network/
2. Install C98 wallet -> đăng nhập ví
3. Aurascan: Login account successfully -> logout
4. Đăng xuất tài khoản trong ví C98
5. Aurascan: Click "Connect wallet" button

**Actual result:** Có thể kết nối ví đã logout trước đó khi chưa nhập password ở ví C98

**Expected behavior:** Cần đăng nhập nhập lại ví C98 thành công, trước khi login tài khoản ở Aurascan

**Screenshots**
![image](https://user-images.githubusercontent.com/24869170/179689458-ba0d852d-5a79-4b42-a903-b4d8e35a9603.png)
![image](https://user-images.githubusercontent.com/24869170/179689516-626d768b-2df3-4dea-b99d-2db18b2bf907.png)

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser: Chrome

**Comment by nttnguyen136** [comment]
Fixed

**Comment by ntatfff** [comment]
Verified PASS on dev (16/08/2022)
![image](https://user-images.githubusercontent.com/24869170/184785429-4448590b-5b61-40e0-9e4e-c8f51f5ce9a6.png)
![image](https://user-images.githubusercontent.com/24869170/184785479-c039bf46-9435-4d54-b2ef-fdb45cf49dce.png)
![image](https://user-images.githubusercontent.com/24869170/184785510-da2f68b9-c70d-42a5-96f6-61eb501e624b.png)
