### ISSUE TITLE
[Aurascan][C98][Validators] Lỗi Undelegate/ClaimReward khi sử dụng ví C98

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#674]
**Describe the bug**
Lỗi Undelegate/ClaimReward khi sử dụng ví C98

**To Reproduce**
1. Go to https://explorer.dev.aura.network/validators
2. Connected C98 wallet
3. Thực hiện transaction  Undelegate/ClaimReward
4. Để default gas value

**Actual result:** Hiển thị lỗi sau khi thực hiện transaction Undelegate/ClaimReward

**Expected behavior**
Thực hiện transaction thành công, hiển thị message chính xác

- Undelegate
![image](https://user-images.githubusercontent.com/24869170/179708833-a7c2bef5-3567-4353-8b86-c5c7719620f9.png)
![image](https://user-images.githubusercontent.com/24869170/179709070-3cb09b13-b5c1-4340-ae1f-1a626f1c4f74.png)
- Claim reward
![image](https://user-images.githubusercontent.com/24869170/179719690-05929ce1-5e06-48bb-bce5-4c843bf273b1.png)

**Comment by nttnguyen136** [comment]
Fixed, re-install coin98 wallet before verify

**Comment by ntatfff** [comment]
Verified PASS on dev (16/08/2022)
- Undelegate
![image](https://user-images.githubusercontent.com/24869170/184785940-e06c39a2-b689-4e7f-aa2c-a923623f0fdb.png)
![image](https://user-images.githubusercontent.com/24869170/184786000-3aeb08c0-74d5-45bd-b23e-0f2d681935cd.png)
![image](https://user-images.githubusercontent.com/24869170/184786013-1fef5f2c-9f5f-4a4f-8fa1-b1fc76c75a2a.png)
- Claim reward
![image](https://user-images.githubusercontent.com/24869170/184786087-a5f68b57-ac66-4f5c-9c28-9b59fe07447f.png)
![image](https://user-images.githubusercontent.com/24869170/184786123-d0212a19-11af-440c-b172-2e4062c8b1b9.png)
![image](https://user-images.githubusercontent.com/24869170/184786166-92bc1964-30d5-434d-8b4e-143422a4c0aa.png)
