### ISSUE TITLE
[Aurascan][ConnectWallet][C98] Đổi tài khoản trên ví C98 nhưng không thay đổi thông tin tài khoản phía dưới Aurascan

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#677]
**Describe the bug**
Đổi tài khoản trên ví C98 nhưng không thay đổi thông tin tài khoản phía dưới Aurascan

**To Reproduce**
1. Truy cập màn hình My account https://explorer.dev.aura.network/account/aura1trqfuz89vxe745lmn2yfedt7d4xnpcpvltc86e
2. Chuyển đổi tài khoản trên Ví C98
3. Kiểm tra thông tin hiển thị ở My account sau khi đổi account

**Expected behavior**
Cập nhật thông tin của account mới vừa đổi trên màn hình My account

**Comment by nhphuc2411** [comment]
đã tracking ở file riêng
