### ISSUE TITLE
[Aurascan][ValidatorDetails] Hiển thị uptime "Last 100 blocks" chưa đúng

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#683]
**Describe the bug**
Hiển thị uptime "Last 100 blocks" chưa đúng

**To Reproduce**
1. Truy cập màn hình Validator Details https://explorer.dev.aura.network/validators/auravaloper1edw4lwcz3esnlgzcw60ra8m38k3zygz2xtl2qh
2. Kiểm tra hiển thị "Last 100 blocks"
3. See error

**Actual result:** Hiển thị "Last 100 blocks" của 1 validator
**Expected behavior** Hiển thị "Last 100 blocks" mới nhất

**Comment by Dpthao245** [comment]
PASS Euphoria 29/07/2022
![image](https://user-images.githubusercontent.com/72438169/181682026-0f44e266-9c9a-403f-8f98-0aa2e221925f.png)
![image](https://user-images.githubusercontent.com/72438169/181682060-3814e344-7b33-4e48-9ca1-4c791dcbce9c.png)
![image](https://user-images.githubusercontent.com/72438169/181682088-9cb5bdc3-997d-4039-92ce-cd0c6bdbc876.png)
