### ISSUE TITLE
[Aurascan][Euphoria][MyAccount] Load data slowly on the Transactions table

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#730]
**Describe the bug**
Load data slowly of Transactions table: loading time up tp 9s

**To Reproduce**
1. Go to https://euphoria.aurascan.io/account/aura1trqfuz89vxe745lmn2yfedt7d4xnpcpvltc86e
2. Click on next pages of Transactions table
3. See error

**Expected behavior**
Go to next pages quickly

**Screenshots**
![image](https://user-images.githubusercontent.com/24869170/181451021-7431e5c6-fcd3-4f72-9007-71408a65f082.png)

**Comment by nhphuc2411** [comment]
Đã chuyển sang call indexer nên cancel bug này nhé @ntatfff
