### ISSUE TITLE
[NewUI] Apply new UI for aurascan

### ISSUE THREAD

**Issue by NgocAnh7278** [aura-nw/aurascan#737]
Apply new UI for aurascan
Link figma: https://www.figma.com/file/xiW41QvCutlazTw9PSQC01/AURA-Explorer?node-id=494%3A55886

**Comment by Dpthao245** [comment]
- [ ] [Desktop] Account Details
- [ ] [Mobile] Account Details
- [ ] [Desktop] Transactions
- [ ] [Deskop] Transaction Details
- [ ] [Desktop] Blocks
- [ ] [Desktop] Block Details

**Comment by nhphuc2411** [comment]
còn màn hình validator detail
