### ISSUE TITLE
[AccountDetails] Update account details: add asset NFT page

### ISSUE THREAD

**Issue by NgocAnh7278** [aura-nw/aurascan#738]
Update account details
Devide into 3 tabs: Assets (Coin & Token, NFT), Transactions and Stake
Link figma: https://www.figma.com/file/xiW41QvCutlazTw9PSQC01/AURA-Explorer?node-id=494%3A55886
Link notion specification: https://www.notion.so/aura-network/Account-Details-70ccbc49b6c44ca581d9405b5eb248e2

**Comment by nhphuc2411** [comment]
Phân trang transaction hiện tại để 5 items/page do API indexer count ko chính xác, cần update lại phân trang theo kiểu nextpage
