### ISSUE TITLE
[Aurascan][Dashboard][Transaction] Exported transaction numbers incorrectly

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#743]
**Describe the bug**
Exported transaction numbers incorrectly
- Last 24h: get with local time
- Last month: get with UTC timezone
- Last year: get with UTC timezone

**To Reproduce**
1. Go to Dashboard https://serenity.aurascan.io/dashboard
2. Download CSV file of Transactions: 24h, 30d, 12M
3. Compare number transaction of last day, last month

**Expected behavior**
Exported transaction numbers correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/24869170/182092710-7491dc60-ad68-4a24-b398-28057efa6131.png)

**Comment by ntatfff** [comment]
Verified FAIL on dev (04/08/2022)
![image](https://user-images.githubusercontent.com/24869170/182793729-b357959f-32bf-4705-9a1b-1cb30314ee7c.png)

**Comment by Dpthao245** [comment]
PASS in Dev 08/08/2022
![image](https://user-images.githubusercontent.com/72438169/183361607-f849726a-41d7-4ce6-bbf5-708e21a31c36.png)
![image](https://user-images.githubusercontent.com/72438169/183362053-29f23b2c-fc89-473c-9af8-3fcd23d2af8c.png)

**Comment by Dpthao245** [comment]
FAIL in Serenity 08/08/2022
![image](https://user-images.githubusercontent.com/72438169/183377135-59773f42-1714-4ef1-945b-e86ecad28036.png)

**Comment by ntatfff** [comment]
Verified FAIL on serenity (16/08/2022)
Not display graph at time range = 12M
![image](https://user-images.githubusercontent.com/24869170/184847917-9696f04f-7803-41b1-98bd-6872f7a61d8f.png)

**Comment by ntatfff** [comment]
Verified PASS on serenity (17/08/2022)
- Display graph
![image](https://user-images.githubusercontent.com/24869170/185283404-bb729a6d-b502-4fc2-8170-591d3c5443d3.png)
![image](https://user-images.githubusercontent.com/24869170/185283437-7bd54f09-a0ae-4a03-808c-9cc817e2f1f3.png)
![image](https://user-images.githubusercontent.com/24869170/185283458-d80c6823-f476-4b16-aa6d-2f8ff6bfecfe.png)
![image](https://user-images.githubusercontent.com/24869170/185283469-f236c834-de83-4768-ab70-e40ef32c5877.png)

- Exported transaction numbers
![image](https://user-images.githubusercontent.com/24869170/185283617-7f2a5ada-cdea-4773-8c20-6397b7585ec0.png)
![image](https://user-images.githubusercontent.com/24869170/185283632-37817d43-569b-4fde-beb7-990e78c7bb09.png)
![image](https://user-images.githubusercontent.com/24869170/185283650-3d509151-493c-4187-83e8-773ed3404f03.png)

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (24/08/2022)
- Timezone UTC-5
![image](https://user-images.githubusercontent.com/24869170/186370009-cf73901b-789b-4945-a088-2d264e069044.png)
- Timezone UTC+7
![image](https://user-images.githubusercontent.com/24869170/186370856-25e54680-29ae-44ac-bc3f-4382b386c760.png)
