### ISSUE TITLE
[AuraScan] Change API to indexer - Proposal

### ISSUE THREAD

**Issue by nhphuc2411** [aura-nw/aurascan#750]
- [x] Proposal
- API gets voted proposal by address : api/v1/proposals/{proposalId}/votes/{voter}
- API gets list depositor : api/v1/proposals/{proposalId}/deposits

**Comment by ntatfff** [comment]
Indexer đang bị lỗi => chưa check được (04/08/2022)

**Comment by ntatfff** [comment]
Verified FAIL on dev (14h 04/08/2022)
Hiển thị thiếu data initial deposit trong bảng Depositors

**Comment by ntatfff** [comment]
Verified PASS on dev (05/08/2022)
![image](https://user-images.githubusercontent.com/24869170/182999770-5fb1e384-0c2c-490c-bd21-74e9883d685d.png)
![image](https://user-images.githubusercontent.com/24869170/182999813-2394b77a-8211-4bf3-9c12-e0c9894608ac.png)
![image](https://user-images.githubusercontent.com/24869170/182999831-1bd52786-f713-43ac-b423-ad98a4565620.png)
![image](https://user-images.githubusercontent.com/24869170/182999939-9f66d2ab-64c9-44d7-9881-b758dbc1a249.png)
![image](https://user-images.githubusercontent.com/24869170/183000023-d46cdd08-3bc1-45a1-9ac5-9e93e12feaf1.png)

**Comment by ntatfff** [comment]
PASS on serenity (09/08/2022)
![image](https://user-images.githubusercontent.com/24869170/183554387-2c38078b-95e3-4728-907c-b787b8c5629a.png)
![image](https://user-images.githubusercontent.com/24869170/183554546-c1e23f47-59be-4e63-9990-e6942a80b998.png)
![image](https://user-images.githubusercontent.com/24869170/183554599-12ed225b-0369-4b93-b8ca-0fe21c2bc2c7.png)
![image](https://user-images.githubusercontent.com/24869170/183554635-9d4e0d1d-870b-43d5-97ca-ed721f077254.png)
![image](https://user-images.githubusercontent.com/24869170/183554668-a80c7205-490e-4815-aae7-6681eb034210.png)
![image](https://user-images.githubusercontent.com/24869170/183554737-492eb0f5-7db4-4919-9a9a-5191b1b05136.png)
![image](https://user-images.githubusercontent.com/24869170/183555022-5d0bd698-e1fc-4657-9062-c6d744e02f91.png)
![image](https://user-images.githubusercontent.com/24869170/183554802-1646b40f-b9db-4b0e-b1ad-a5fabb0977a1.png)
![image](https://user-images.githubusercontent.com/24869170/183554848-a9f598ee-ac64-498d-ba85-008c34e66c59.png)

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (15/09/2022)
![image](https://user-images.githubusercontent.com/24869170/190375912-e7775d83-7e75-4295-b967-a19e371a6fd0.png)
![image](https://user-images.githubusercontent.com/24869170/190375981-3da023d9-f851-4786-aaa5-dc0501ecdf08.png)
![image](https://user-images.githubusercontent.com/24869170/190376086-5acb6585-11ac-4755-9f5b-075aff90e294.png)
![image](https://user-images.githubusercontent.com/24869170/190376200-6a8a512d-944e-46c2-a3cf-b7b4095ad6ad.png)
