### ISSUE TITLE
[Aurascan] balance của ví Pysix safe hiển thị khác trên aurascan

### ISSUE THREAD

**Issue by hangpham23** [aura-nw/aurascan#752]
## Description
Chọn view safe trên aurascan> balance amount của safe hiển thị khác nhau trên Pysix và aurascan
## Environment
 - Browser: Chrome
 - Wallet: Keplr
 - Safe: aura1ru5ara0rwrh3sqccnwv8ct28e9vurajpere2mf
 - Environment: 
   - https://serenity.aurascan.io/account/aura1ru5ara0rwrh3sqccnwv8ct28e9vurajpere2mf
   - https://safe.serenity.aura.network/102:aura1ru5ara0rwrh3sqccnwv8ct28e9vurajpere2mf/balances

## Steps to reproduce
 1. Go to https://safe.serenity.aura.network/
 2. Connect wallet and select safe: 
 aura1ru5ara0rwrh3sqccnwv8ct28e9vurajpere2mf/balances
3. Select "View on serenity.aurascan.io"

## Expected result
Display safe with correct information on both Pysix safe and Aurascan
![Screen Shot 2022-08-03 at 16 29 22](https://user-images.githubusercontent.com/102220123/182576869-8f9e2ad1-84a4-4bde-be1d-2d3f9b154076.png)
![Screen Shot 2022-08-03 at 16 29 34](https://user-images.githubusercontent.com/102220123/182576883-7e1313fe-1083-4ccc-b0cf-bd536a75c006.png)

**Comment by doquockhanhan** [comment]
bug này xuất hiện khi tạo 1 transaction nhưng thiếu gas dẫn đến transaction fail nhưng vẫn mất phí tạo giao dịch
