### ISSUE TITLE
[Aurascan][VotingDetails] Add "Request Amount" field in Voting Details screen

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#764]
**Description:**
Add "Request Amount" field in Voting Details screen
- Proposal type: community-pool-spend
![image](https://user-images.githubusercontent.com/24869170/183026650-09661542-f20f-4d74-92cb-234be92c848b.png)

**Comment by ntatfff** [comment]
Verified FAIL on dev (8/8/2022)
Request amount chưa chia 10^6
![image](https://user-images.githubusercontent.com/24869170/183320549-be9cf776-e823-4184-aa12-e4aa9eb0cbf0.png)

**Comment by Dpthao245** [comment]
PASS in Serenity 08/08/2022
![image](https://user-images.githubusercontent.com/72438169/183352836-ae33cd1e-f9a1-43b5-af49-9e9196b1d997.png)

**Comment by Dpthao245** [comment]
PASS in Serenity 08/08/2022
![image](https://user-images.githubusercontent.com/72438169/183373399-aa0b8999-61e5-45cc-bc7a-be7899a55e78.png)

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (24/08/2022)
![image](https://user-images.githubusercontent.com/24869170/186354535-98bbe039-b28a-46be-9c9a-f38770444ec7.png)
