### ISSUE TITLE
[TransactionDetails] Update transaction details: Add IBC transaction details

### ISSUE THREAD

**Issue by lhts1810** [aura-nw/aurascan#770]
Add details of 4 IBC transaction types:
- IBC Transfer
- IBC Received
- IBC Acknowledgement
- IBC Update client

Link notion: https://www.notion.so/aura-network/Transactions-3f138c3a969c4f42acd5798791cfff95
Link notion about fields of 4 type IBC txn: https://www.notion.so/aura-network/IBC-txn-b03d29e3ad8e4365a17e2fca58a81e68
To developers: please help checking further to see if any cases are missing.

**Comment by mtamkg** [comment]
IBC đã lấy được những case sau:
+ IBC Transfer
+ IBC Receive
+ IBC Update Client
+ IBC Time Out
+ IBC Acknowledgement( Kiên bảo type này ver mới đã bỏ đi. nên ko cần test)

**Comment by ntatfff** [comment]
Còn thiếu transaction IBC receive (list transaction, account detail transaction)
=> chờ Tuấn xử lý tiếp

**Comment by ntatfff** [comment]
Verified FAIL on serenity (20/09/2022)
- [ ] Sai Type transaction ở địa chỉ người nhận amount: IBC Update Client => IBC Received (sửa lại lấy Type thứ 2 trong message transaction)
![image](https://user-images.githubusercontent.com/24869170/191210779-99f600c3-8dc2-49ac-9363-530499091c5e.png)
![image](https://user-images.githubusercontent.com/24869170/191210865-002deabd-98ec-4426-95ba-0a38df0a697b.png)

**Comment by ntatfff** [comment]
Verified PASS on serenity (23/09/2022)
- IBC Received
![image](https://user-images.githubusercontent.com/24869170/191938278-068a786e-c0e2-4903-a813-59bf9e02afcc.png)
![image](https://user-images.githubusercontent.com/24869170/191938726-9052d982-5afa-470c-84de-35eb8bde1214.png)
![image](https://user-images.githubusercontent.com/24869170/191938657-87d43958-4313-4b67-8c84-edec51d9c13c.png)
- IBC Transfer
![image](https://user-images.githubusercontent.com/24869170/191938855-682f77c3-f460-4b40-ae53-e474c7b429ec.png)
- IBC Acknowledgement
![image](https://user-images.githubusercontent.com/24869170/191939548-f82a4290-bb9a-486f-850f-ac206c755fd5.png)
![image](https://user-images.githubusercontent.com/24869170/191939578-be806c37-eaac-450a-bf7a-3262bdbe90fd.png)
- IBC Update Client
![image](https://user-images.githubusercontent.com/24869170/191939971-f747c984-9484-498e-84ec-cee0efe928d0.png)
![image](https://user-images.githubusercontent.com/24869170/191939991-d6977d97-aae9-4a84-a627-0ceb8a5c7bee.png)

Not check with IBC transaction type:
- IBC Timeout

**Comment by ntatfff** [comment]
Verified on Euphoria (11/10/2022)
- IBC Acknowledgement
![image](https://user-images.githubusercontent.com/24869170/194997657-5b99c415-e39d-4b4a-b1e5-a7c84d3b4600.png)
![image](https://user-images.githubusercontent.com/24869170/194997686-87791351-fddb-4d25-95d2-c7e48a6f92f2.png)
- IBC Received
![image](https://user-images.githubusercontent.com/24869170/194997961-d30c052a-819f-4e43-b2f7-ea71d5d9d64b.png)
![image](https://user-images.githubusercontent.com/24869170/194998005-5ecbe655-d146-41fa-b46e-9d8a78b40fab.png)
- IBC Transfer
![image](https://user-images.githubusercontent.com/24869170/194999237-6bbc4d7a-8215-4858-9770-3b9c6359fb25.png)
- IBC Update Client
![image](https://user-images.githubusercontent.com/24869170/194999140-0843c580-eb91-47b7-9e32-2b7b5f459625.png)
