### ISSUE TITLE
[Aurascan][Tokens][CW20][CW721] Not display tokens has duplicated contract Code ID

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#782]
**Describe the bug**
Not display tokens has duplicated contract Code ID

**Precondition:** 
- Create contracts that has duplicated code ID
- Verified contract successfully (verified)

**To Reproduce**
1. Go to Aurascan - Tokens: CW-20 Top Tokens
2. Go to Aurascan - Tokens: CW-721 Top Tokens
3. See error

**Expected behavior**

**Screenshots**
- [x] Display  all tokens that have verified successfully (with/without duplicated contract Code ID)

**Comment by Dpthao245** [comment]
PASS in Dev 10/08/2022
CW20
![Image](https://user-images.githubusercontent.com/72438169/183863565-5095ad10-8da9-4940-9552-8370eac9aec1.png)

CW721
![Image](https://user-images.githubusercontent.com/72438169/183864207-b2aa4f8f-a690-46e4-b964-c0968b3aee74.png)

**Comment by ntatfff** [comment]
Verified PASS on serenity (17/08/2022)
CW721
![image](https://user-images.githubusercontent.com/24869170/185067773-e1b947e1-d96e-48a9-b799-32dff5c88cc2.png)

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (16/09/2022)
![image](https://user-images.githubusercontent.com/24869170/190557778-c16016c1-988f-4aac-b7fd-8c7b82667fd7.png)
![image](https://user-images.githubusercontent.com/24869170/190557817-805cb710-0f0d-474d-902c-6bddd7421828.png)
