### ISSUE TITLE
[Aurascan][TokenDetail][ContractDetail] Write Contract hiển thị lỗi khi thực hiện send nft/amount

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#793]
**Describe the bug**

- [x] ISSUE 01: CW721 - Write Contract hiển thị lỗi khi thực hiện send nft
-  Token: https://explorer.dev.aura.network/tokens/token/aura1x9unynpfqrnc8w58hrhlmeeakws46mpj0s7up774k4lhckl9jphszm3wdh
- Contract: https://explorer.dev.aura.network/contracts/aura1x9unynpfqrnc8w58hrhlmeeakws46mpj0s7up774k4lhckl9jphszm3wdh?tabId=contract
- [x] ISSUE 02: CW20 - Write Contract hiển thị lỗi khi thực hiện send amount
- [x] ISSUE 03: CW20 - Write Contract hiển thị lỗi khi thực hiện send from amount
- Token: https://explorer.dev.aura.network/tokens/token/aura15v8y2u3e4yvjrnn5zjj69dkx7x9xg5fg507k2q64k8waczxzg0cqkctc69
- Contract: https://explorer.dev.aura.network/contracts/aura1xdg8d2hyhmuf90lhqjmz0tayy9qc2gfkcfhwq0qrz5h3uzrh24ys7yyls6

**To Reproduce**
1. Go to link trên
2. Input data in Send nft/amount
3. Click Write button

**Screenshots**
CW721
![image](https://user-images.githubusercontent.com/72438169/184077064-1caf3885-7eaf-4eef-a081-ec7ee515ab2b.png)
CW20
![image](https://user-images.githubusercontent.com/24869170/184108337-6c53c258-6de2-4739-b462-934559d57f6e.png)

- [ ] ISSUE 03: CW721 - Write Contract hiển thị lỗi khi nhập expires (any), thực hiện 3. approve, 5. approve_all
- Contract: https://explorer.dev.aura.network/tokens/token-nft/aura1x9unynpfqrnc8w58hrhlmeeakws46mpj0s7up774k4lhckl9jphszm3wdh

**To Reproduce**
1. Go to link trên
2. Input data in 3. approve or 5. approve_all
3. Click Write button

**Screenshots**
![Image](https://user-images.githubusercontent.com/72438169/184596029-9f6dc9d1-71e8-41de-b425-b452afe0c1a0.png)
![Image](https://user-images.githubusercontent.com/72438169/184596110-e1019832-ee97-48c5-90a1-231b5e28de87.png)

**Comment by Dpthao245** [comment]
PASS in Dev 26/08/2022
Approve
![image](https://user-images.githubusercontent.com/72438169/186881151-acb90ee7-ed26-44b9-984d-f55a651cf4c0.png)

Approve all
![image](https://user-images.githubusercontent.com/72438169/186881418-e383c3e0-f2f2-4f51-847d-12be23cc0dbe.png)

**Comment by nttnguyen136** [comment]
Đã chuyển [send_nft.msg] sang Binary. Cần biết chính xác message mới có thể thực việc việc send NFT

**Comment by Dpthao245** [comment]
PASS in Serenity 06/09/2022
3. approve
![image](https://user-images.githubusercontent.com/72438169/188580819-341a7b14-5254-4266-b18b-67c7b259bdc3.png)
5. approve all
![image](https://user-images.githubusercontent.com/72438169/188581005-1cb5a023-f0f8-40ce-8adf-fce26ee9cb66.png)

**Comment by Dpthao245** [comment]
PASS in Euphoria 16/09/2022
![image](https://user-images.githubusercontent.com/72438169/190577046-c8815134-1247-4a64-9d88-399b516f246f.png)
![image](https://user-images.githubusercontent.com/72438169/190577134-f464c170-4502-4c83-be01-afe1e5e7830e.png)
