### ISSUE TITLE
[Aurascan][Tokens][CW721] Inventory tab chưa remove NFT khi đã burn/send_nft thành công

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#795]
**Describe the bug**

- [ ] ISSUE: Inventory tab chưa remove NFT khi đã burn/ send_nft thành công

**To Reproduce**
1. Go to https://explorer.dev.aura.network/tokens/token/aura1x9unynpfqrnc8w58hrhlmeeakws46mpj0s7up774k4lhckl9jphszm3wdh?a=Token%20ID%2072102
2. Thực hiện burn NFT thành công
3. Click on Inventory tab

**Expected behavior**
Inventory tab không hiển thị thông tin NFT đã burn

**Screenshots**
![image](https://user-images.githubusercontent.com/72438169/184096298-e60c3f1f-deaf-41cb-a36d-5e3b038627f0.png)
![image](https://user-images.githubusercontent.com/72438169/184096420-a1a39058-8854-4147-96ef-0ffb495b23ab.png)
![image](https://user-images.githubusercontent.com/72438169/184096460-a94325d0-341f-415c-8aa0-57cef712cf38.png)

**Comment by thub1310577** [comment]
Token đã burn nhưng api getByContractType bên indexer vẫn trả về data, đang đợi Tuấn check lại

**Comment by Dpthao245** [comment]
PASS in Dev 16/08/2022


![Image](https://user-images.githubusercontent.com/72438169/184813370-26afa760-e7a1-49a3-a582-bc20824c8852.png)

![Image](https://user-images.githubusercontent.com/72438169/184812728-ea60b2f8-c6e0-47d9-aca1-be44f37f35a4.png)

![Image](https://user-images.githubusercontent.com/72438169/184813403-7c0d0808-9544-4ae3-9ee7-4694d7512fed.png)

**Comment by Dpthao245** [comment]
PASS in Serenity 19/08/2022

- Trước khi thực hiện Burn NFT:

![image](https://user-images.githubusercontent.com/72438169/185536135-be03f2e4-b145-4421-bc4f-bda1e7482b98.png)
![image](https://user-images.githubusercontent.com/72438169/185536149-aecb2b50-5928-4950-a58f-8e7830c6c200.png)

-  Khi thực hiện Burn NFT:

![image](https://user-images.githubusercontent.com/72438169/185536317-71e57791-3aa0-4f3a-ba5d-b6f4a07975f0.png)
![image](https://user-images.githubusercontent.com/72438169/185536390-542f2956-4d45-4014-a6eb-114f48925249.png)

**Comment by Dpthao245** [comment]
PASS in Euphoria 15/09/2022
![image](https://user-images.githubusercontent.com/72438169/190373656-d17ee3c4-83dd-4f74-81e3-8474d8da82ee.png)
![image](https://user-images.githubusercontent.com/72438169/190373676-33fa6a2f-5204-42ee-886f-383753b819d9.png)
