### ISSUE TITLE
[Aurascan][Tokens][CW20][CW721] Display data incorrectly at Holders tab

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#825]
**Describe the bug**
1. Token details CW20: Sắp xếp sai thứ tự Rank của Holders khi phân trang
2. Token details CW721: Phân trang sai, không hiển thị data trang 2

**To Reproduce**
1. Go to  Token details CW20: https://explorer.dev.aura.network/tokens/token/aura15v8y2u3e4yvjrnn5zjj69dkx7x9xg5fg507k2q64k8waczxzg0cqkctc69
2. Go to token details CW721: https://explorer.dev.aura.network/tokens/token-nft/aura169hw8mfua3wsuaf5nmky30ta69mshpegm04awp58xrmc2stze3nsu2j26a
3. See error

**Expected behavior**
- [x] 1. Token details CW20: Sắp xếp đúng thứ tự Rank của Holders, sort giảm dần của tất cả các dòng
- [x] 2. Token details CW721: Phân trang 20 rows/page

**Screenshots**
CW20
![image](https://user-images.githubusercontent.com/24869170/184822571-725516f2-0d0e-4ba6-b259-41c9fad33f9a.png)

CW721
Holder 24 -> hiển thị 20

![image](https://user-images.githubusercontent.com/72438169/184824979-26bf89b2-3dc1-4e7b-93f1-edc81ad61c06.png)
![image](https://user-images.githubusercontent.com/72438169/184825995-f57bd921-6815-4e2b-ac48-28c70cf4b2e8.png)
![image](https://user-images.githubusercontent.com/72438169/184825004-3e9ab937-165f-4cfd-8513-8be5f0975788.png)

Không hiển thị những holder, ví dụ holder này
![image](https://user-images.githubusercontent.com/72438169/184825798-db64fb27-15c2-44f7-9bde-84aba1861ba7.png)

**Comment by ntatfff** [comment]
Verified PASS on dev (17/08/2022)
![image](https://user-images.githubusercontent.com/24869170/185058810-e6bafff1-4d39-44ef-a1da-348f5c6c32d4.png)
![image](https://user-images.githubusercontent.com/24869170/185058841-15c98857-06ea-4288-b4e5-7a10e82a1fdc.png)
![image](https://user-images.githubusercontent.com/24869170/185058877-56128b7d-75e2-4f9d-8a04-94839d69f071.png)

**Comment by ntatfff** [comment]
Verified PASS on serenity (19/08/2022)
- CW20
![image](https://user-images.githubusercontent.com/24869170/185528252-d969eff1-1610-4cbf-a7a7-d3bec69fa2a5.png)
![image](https://user-images.githubusercontent.com/24869170/185528334-ab19230a-01c1-466f-84b7-bd6a761ad720.png)
![image](https://user-images.githubusercontent.com/24869170/185528311-002515d6-51c6-47aa-aa1a-f0570fcff3a9.png)
- CW721
![image](https://user-images.githubusercontent.com/24869170/185530600-211b5780-237a-41be-8eb7-fab533825c33.png)
![image](https://user-images.githubusercontent.com/24869170/185530641-f0e3797b-e5cf-422b-a221-5616d3be14b8.png)
![image](https://user-images.githubusercontent.com/24869170/185530672-48287551-683c-4ae5-9512-2e8d7428b4c4.png)

**Comment by Dpthao245** [comment]
PASS in Euphoria 16/09/2022
Token Details CW721
![image](https://user-images.githubusercontent.com/72438169/190557410-c84ebfb6-3402-4cfe-bea7-19b8de7b9213.png)
![image](https://user-images.githubusercontent.com/72438169/190557437-fafc2742-bcc7-4a74-869a-fd93727c1029.png)
![image](https://user-images.githubusercontent.com/72438169/190557463-863871f8-cabd-46ff-ba98-59f65eef0568.png)
