### ISSUE TITLE
[Aurascan][C98][Contracts][Tokens] Cannot write contract/token when using C98 address

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#826]
**Describe the bug**
Display error message "TypeError: Cannot read properties of undefined (reading 'match')"
**CW20 - Contracts and Tokens: Cannot write contract/token with methods:**
1. transfer
2. burn
3. send
4. increase_allowance
5. decrease_allowance
6. transfer_from
7. send_from
8. burn_from
9. mint
10. update_marketing

**CW721 - Contracts and Tokens: Cannot write contract/token with methods:**
1. transfer_nft
2. send_nft
3. approve
4. revoke
5. approve_all
6. revoke_all
7. mint
8. burn

**To Reproduce**
12. Click on '....'
13. Scroll down to '....'
14. See error

**Expected behavior**
Write contract/token successfully
- [ ] **CW20 - Contracts and Tokens**
1. transfer
2. burn
3. send
4. increase_allowance
5. decrease_allowance
6. transfer_from
7. send_from
8. burn_from
9. mint
10. update_marketing
- [ ] **CW721 - Contracts and Tokens:**
1. transfer_nft
2. send_nft
3. approve
4. revoke
5. approve_all
6. revoke_all
7. mint
8. burn

**Screenshots**
![image](https://user-images.githubusercontent.com/24869170/184824271-e1201dce-435a-4ebd-a704-2f6ceda0018b.png)
![image](https://user-images.githubusercontent.com/24869170/184824297-a2b35ec0-e68f-45e5-aed8-61710b54d70e.png)

**Comment by nhphuc2411** [comment]
C98 đã fix ở bản portable
