### ISSUE TITLE
[Aurascan][Tokens][CW721][CW20] Some issue của chức năng Search

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#834]
**Describe the bug**

Màn hình Danh sách token của CW721 & CW20

- [x] ISSUE: Kết quả search, hiển thị sai data và không trở về trang đầu tiên khi search ở trang thứ 2, ...

**To Reproduce**
1. Go to https://explorer.dev.aura.network/tokens
2. Click on Page 2
3. Input điều kiện search -> Nhấn Enter
4. Scroll down to paging
5. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/72438169/185074291-a98662c8-5ded-4143-ad28-b08095883646.png)
![image](https://user-images.githubusercontent.com/72438169/185074633-dd086e77-26f7-457f-9f95-a75edc131b3f.png)
![image](https://user-images.githubusercontent.com/72438169/185074463-ff46e4bf-d117-4a9c-8958-9704d28fd17b.png)

**Expected behavior**
Hiển thị kết quả search ở trang đầu tiên

**Comment by ntatfff** [comment]
Verified PASS on dev (18/08/2022)
- CW721
![image](https://user-images.githubusercontent.com/24869170/185310303-12aa8de8-bb75-4c34-b281-bd3243ffb37f.png)
![image](https://user-images.githubusercontent.com/24869170/185310385-79b0cac9-7493-4a0c-b463-c3589577fb36.png)
![image](https://user-images.githubusercontent.com/24869170/185310555-e2eeb49b-c18a-4413-9d16-bb761d1e608e.png)
![image](https://user-images.githubusercontent.com/24869170/185310624-a1e653f0-6207-41b0-b15d-8e9b3a0a6a89.png)
- CW20
![image](https://user-images.githubusercontent.com/24869170/185310780-5be389f3-24a0-472d-8d62-ef5494c1aeea.png)
![image](https://user-images.githubusercontent.com/24869170/185310955-0185b140-f7f8-4b7f-87fb-c8c3a4855a19.png)
![image](https://user-images.githubusercontent.com/24869170/185311134-6f265b84-d9ba-475a-a719-bb0f30e614b7.png)
![image](https://user-images.githubusercontent.com/24869170/185311373-4e521e56-cccd-40ce-94d9-264edc9fc5be.png)

**Comment by Dpthao245** [comment]
PASS in Serenity 19/08/2022

Token list CW721

![image](https://user-images.githubusercontent.com/72438169/185539180-c64541b6-a66d-4399-922a-e136504158af.png)
![image](https://user-images.githubusercontent.com/72438169/185539207-bd912f60-bffd-4b8a-b0ba-0dcdf49d0dec.png)
![image](https://user-images.githubusercontent.com/72438169/185539222-4a054a8d-1866-4dde-af0f-1e8b5eb10acf.png)
![image](https://user-images.githubusercontent.com/72438169/185539231-84565a40-8b36-4e23-98b7-aefdec6fa3ad.png)

Token list CW20
![image](https://user-images.githubusercontent.com/72438169/185539355-ef3df756-bc4e-4b84-9ee1-ddf3be119b36.png)
![image](https://user-images.githubusercontent.com/72438169/185539398-6c5bdf58-131b-4b4a-b78c-8c577d282798.png)
![image](https://user-images.githubusercontent.com/72438169/185539432-c54d2d25-72ae-45cc-bb65-c52ed58e8675.png)
![image](https://user-images.githubusercontent.com/72438169/185539472-717fd7dc-ffc3-44a6-b578-d3e6191c2e8f.png)

**Comment by Dpthao245** [comment]
PASS in Euphoria 16/09/2022
![image](https://user-images.githubusercontent.com/72438169/190588273-b071ddc7-5bd1-420a-8cb5-376c8c8a35e9.png)
![image](https://user-images.githubusercontent.com/72438169/190588291-739e4e71-bb1a-4f8d-b8db-1d80f37dc149.png)
![image](https://user-images.githubusercontent.com/72438169/190588324-7c672178-f0a5-4e3f-b4c0-b0a7d9a76cb6.png)
