### ISSUE TITLE
[Aurascan][TokenDetails][CW20][CW721][Holders] Sắp xếp thứ tự holders chưa đúng

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#846]
**Describe the bug**
Sắp xếp thứ tự holders chưa đúng khi các holders có amount bằng nhau
- CW20: https://explorer.dev.aura.network/tokens/token/aura15v8y2u3e4yvjrnn5zjj69dkx7x9xg5fg507k2q64k8waczxzg0cqkctc69
- CW721: https://explorer.dev.aura.network/tokens/token-nft/aura1fzv764v24wu0zjsk2tgsyrtqfn43m2mn35jznvfhkg035f3nxasqkuqyxn

**Expected behavior**
Sắp xếp thứ tự holders theo thứ tự thời gian giảm dần khi các holders có amount bằng nhau

**Screenshots**
![image](https://user-images.githubusercontent.com/24869170/185541864-00a0766d-0892-43cd-9dc6-33af226fecbb.png)
![image](https://user-images.githubusercontent.com/24869170/185542297-fb579d7d-424e-4f12-ae52-122246d736f7.png)

**Comment by Dpthao245** [comment]
PASS in Dev 05/09/2022
Token CW721
![image](https://user-images.githubusercontent.com/72438169/188373983-6d385806-b91b-4a3f-a015-2f96a804e70b.png)
![image](https://user-images.githubusercontent.com/72438169/188374107-17855068-57a4-49f7-afa3-5b9546e41b53.png)

**Comment by Dpthao245** [comment]
PASS in Serenity 05/09/2022
Token CW721
![image](https://user-images.githubusercontent.com/72438169/188420906-bb07b20c-6c8a-4155-8310-f2246be8e5eb.png)
![image](https://user-images.githubusercontent.com/72438169/188420954-15df1414-7b3a-4fbf-96c2-00460729d165.png)

**Comment by Dpthao245** [comment]
PASS in Euphoria 16/09/2022
![image](https://user-images.githubusercontent.com/72438169/190573828-c76a4315-ed02-4fc0-9e2f-620277e6ab4c.png)

![image](https://user-images.githubusercontent.com/72438169/190573746-c1777e95-dbfe-4a78-96ee-c8a41c198489.png)
