### ISSUE TITLE
[Aurascan][Contracts][Desktop] Some issues after updating new layout

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#852]
**Describe the bug**
Some UI issues after updating layout

**To Reproduce**
Contract list: https://explorer.dev.aura.network/contracts
Contract details: https://explorer.dev.aura.network/contracts/aura1s9qvl5ynrncvjez4nfcsmf6u05lkyg4qze27d2gshl3kxhqlx5fsjzmrs3?tabId=contract
1. Go to Contract details -> Contract tab
2. Click "Verify and Publish" contract -> Input incorrect github link 
3. Display error popup

**Expected behavior**
**Contract list:**
- [ ] 1. Thêm symbol ở sau tên contract, ví dụ: Aura (AURA)
![image](https://user-images.githubusercontent.com/24869170/185871954-c4ad71f7-9340-493f-92c7-6c521b10efc6.png)
- [x] 2. Text title của bảng: fonts-size 14px, color #9DA1AC
![image](https://user-images.githubusercontent.com/24869170/185877906-73dd6120-367b-4fed-bd22-48b58d3e3839.png)

**Màn hình Contract details: "Verify & Publish Contract Source Code"**
- [x] 3. Labels of input: font-weight 500, line-height 18px
- [x] 4. Text of buttons "Reset", "Verified & Publish": font-weight 600

**"Màn hình Contract details: Popup warning"**
- [x] 5. Kích thước icon warning "i": 24x24 px 
- [x] 6. Nút OK: màu viền: gradient , màu text: #FFFFFF, font-size: 14px

**Màn hình Contract details: Contract Overview**
- [x] Thay đổi icon phía trước Symbol và Token name (icon desk và mob đang sai -- đang hỏi lại designer)
- [x] Text "Symbol" và "Token name": font-weight: 600
- [x] Text Amount của Aura Value: 14px
![image](https://user-images.githubusercontent.com/24869170/185887368-08742338-bb3a-43f7-bbbd-58591ec98778.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/24869170/185827380-7a281587-3ff1-45ed-9b6c-b31a0b1095e4.png)
![image](https://user-images.githubusercontent.com/24869170/185829700-180aef3b-053a-4cb0-b498-0885ffa685ec.png)

**Comment by letrieuthien** [comment]
Text Amount của Aura Value: sẽ dùng màu gray-5

**Comment by ntatfff** [comment]
Verified PASS on dev (23/08/2022)
2. ![image](https://user-images.githubusercontent.com/24869170/186118405-9cc95521-4e67-4af4-a557-8b8eb36969cf.png)
3. ![image](https://user-images.githubusercontent.com/24869170/186118805-0f17a212-89f1-4fbd-b7ed-eadf9e984459.png)
4. ![image](https://user-images.githubusercontent.com/24869170/186129945-94624339-f208-4c14-8c39-c89481d7f090.png)
5. ![image](https://user-images.githubusercontent.com/24869170/186130238-ee4ecf09-a26f-4775-a6f0-fb1971be5d21.png)
6. ![image](https://user-images.githubusercontent.com/24869170/186130511-2960bae8-904b-476e-a954-89e9ef077eb4.png)
![image](https://user-images.githubusercontent.com/24869170/186131874-9bb957bf-fff1-4f6c-9df2-90817ab56a0a.png)
![image](https://user-images.githubusercontent.com/24869170/186131838-6b0f433c-a8f9-4721-ad64-9db0f1bc88a9.png)
