### ISSUE TITLE
[Aurascan][Euphoria][VotingDetails] Not display Depositors data after updating indexer

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#872]
**Describe the bug**
Not display Depositors data after updating indexer

**To Reproduce**
1. Go to Voting details https://euphoria.aurascan.io/votings/4
2. See error

**Expected behavior**
Display Depositors data correctly after updating indexer

**Screenshots**
![image](https://user-images.githubusercontent.com/24869170/186358232-9cb89475-1ee1-4d9a-ae4b-f1d1113fa15f.png)

**Comment by nhphuc2411** [comment]
đã change call api lcd trên dev

**Comment by ntatfff** [comment]
Verified PASS on dev (25/08/2022)
![image](https://user-images.githubusercontent.com/24869170/186630890-3c043b94-beb4-4224-94f0-1af1b9210b55.png)
![image](https://user-images.githubusercontent.com/24869170/186630979-f9945dc8-1758-4dda-bdad-88a058570fe2.png)
![image](https://user-images.githubusercontent.com/24869170/186631030-991a8f77-9eb2-4cc5-a553-baa185ae8065.png)

**Comment by ntatfff** [comment]
verified PASS on serenity (06/09/2022)
![image](https://user-images.githubusercontent.com/24869170/188567086-4474ab30-0157-4619-aad2-b246d89ac53d.png)

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (16/09/2022)
![image](https://user-images.githubusercontent.com/24869170/190551995-72baf047-d210-4071-8d26-e37821358438.png)
