### ISSUE TITLE
Acount bount Token (Soulbound Token)

### ISSUE THREAD

**Issue by Thaonguyen541** [aura-nw/aurascan#885]
**Link FRS**: https://www.notion.so/aura-network/5edc1a7dbc5d4e45b5b5c4aad5a7d844?v=1dd35b8b4ddc400892977b28e527833e&p=d3c25a050fda4607a7d5162cbdda4efa&pm=s

**Link Mockup**: https://app.diagrams.net/#G1xdA7PbMYNFN2gB4WCt2pN35H1P3ItN5w

**Link Design**: https://www.figma.com/file/xiW41QvCutlazTw9PSQC01/%5BAura%5D-Scan?node-id=4064%3A179595&t=oIYX5CcNhH2NKaVV-0

**Comment by nthduc95** [comment]
Sequence diagram:
Flow1: Display list of Soulbound smart contracts.
- Request a list of Soulbound smart contracts which can interact to mint Soulbound Tokens.
- Query list of Soulbound smart contract with condition minterAddress and contractAddress.
- Response data for UI display list of Soulbound smart contract.

![Image](https://user-images.githubusercontent.com/119287881/206332986-6d2f7265-02c8-4329-a214-777de5cf439b.png)
