### ISSUE TITLE
Add Statistics in Aurascan

### ISSUE THREAD

**Issue by Thaonguyen541** [aura-nw/aurascan#886]
Link FRS: https://www.notion.so/aura-network/5edc1a7dbc5d4e45b5b5c4aad5a7d844?v=1dd35b8b4ddc400892977b28e527833e&p=d32580a4ec224bf1b639c6f0a2db9577&pm=s

**Comment by nhphuc2411** [comment]
https://taiga.aura.network/project/aurascan-2/us/10?milestone=13
