### ISSUE TITLE
[Aurascan][Tokens][CW721] Giá trị Price của Token Detail CW721

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#909]
Price: View the lowest last sale price for NFTs in this token contract
Currency: $

![image](https://user-images.githubusercontent.com/72438169/186881814-d566dcfc-a4f5-4811-9ea4-762bb49caf14.png)

**Comment by nhphuc2411** [comment]
![image](https://user-images.githubusercontent.com/101378686/202640398-761c998b-65cd-4c8f-9ac5-3ed4b1ccd584.png)
