### ISSUE TITLE
Change way to get avatar of validator

### ISSUE THREAD

**Issue by NgocAnh7278** [aura-nw/aurascan#939]
In the database, the validator table has a field "identity" - 16 characters.
![image](https://user-images.githubusercontent.com/40628286/187406582-0ddd9399-e1a4-4e4c-bc7a-2d8ac9faec3d.png)
When accessing the link 
https://keybase.io/_/api/1.0/user/lookup.json?key_suffix=<identity>&fields=pictures
and replace <identity> on the link with the identity field value in the database.
![image](https://user-images.githubusercontent.com/40628286/187406544-cc2d9841-1582-48fe-bc21-36aac5ecd479.png)
=> Avatar of the validator with this identity value is the value of the field "url"
![image](https://user-images.githubusercontent.com/40628286/187407292-47fa3319-e835-408a-88fd-1d8d1a78a67c.png)

**Comment by kienvc** [comment]
Try to use identity field to get the logo first.
If validator doesn't have identity field, get the image from s3 as the current way.

**Comment by ntatfff** [comment]
Verified FAIL on serenity (20/09/2022)
Not display image at Validators list: Delegating, Undelegating and Redelegations tab at Account details 
![image](https://user-images.githubusercontent.com/24869170/191220729-938c09e3-d4bd-4aac-b1e0-860640ee251b.png)
![image](https://user-images.githubusercontent.com/24869170/191220754-184d1afd-901a-4a67-be77-08641b53409a.png)

**Comment by ntatfff** [comment]
Verified FAIL on serenity (21/09/2022)
Not display image or display incorrect image at 
- [ ] Validators list: Delegating, Undelegating
- [ ] Account details: Redelegations tab
- [ ] Voting details: Validators Votes table (mobile)
![image](https://user-images.githubusercontent.com/24869170/191653072-fa6ac982-a6fc-47be-9ac6-b71ca60e9ac0.png)
![image](https://user-images.githubusercontent.com/24869170/191653085-742c77c7-52ad-4f37-93f7-16e8ddef2942.png)
![image](https://user-images.githubusercontent.com/24869170/191653096-39dab74c-5ef1-4e1c-b0a1-bbd86b8bf77e.png)

**Comment by ntatfff** [comment]
Verified PASS on serenity (22/09/2022)
- Validator list
![image](https://user-images.githubusercontent.com/24869170/191715925-7b7c27cd-3325-422a-8cd5-42e91a5f9a32.png)
![image](https://user-images.githubusercontent.com/24869170/191716002-c32f9597-4dbb-4788-9808-d1986ff1eb29.png)
![image](https://user-images.githubusercontent.com/24869170/191716069-a1910360-7689-46e1-98be-901b308ff3a7.png)
![image](https://user-images.githubusercontent.com/24869170/191716115-cf1fb060-ee58-4e16-bb0f-cf44e9e665a0.png)
![image](https://user-images.githubusercontent.com/24869170/191717212-cf71122b-d93b-4bd5-8eb9-fa0ef0be5fed.png)

- Voting details
![image](https://user-images.githubusercontent.com/24869170/191716274-b1f55017-b9b0-41e9-af2d-fb881fde7437.png)
![image](https://user-images.githubusercontent.com/24869170/191716293-9f84b216-8a59-462f-a7e5-8cdbf1672d11.png)
- Account details
![image](https://user-images.githubusercontent.com/24869170/191716574-35cf5928-638c-4640-8123-e7ad578d1b48.png)
![image](https://user-images.githubusercontent.com/24869170/191716611-3be7f62a-b880-4175-858d-6c9be63a8c9e.png)
![image](https://user-images.githubusercontent.com/24869170/191716642-9254b2d1-6eae-47fc-84e5-5560e5993e5f.png)
![image](https://user-images.githubusercontent.com/24869170/191716976-8a65865e-1d40-4114-9473-b489d6176871.png)
![image](https://user-images.githubusercontent.com/24869170/191717062-2dae4256-e707-4c61-87f0-75649af1dfab.png)
![image](https://user-images.githubusercontent.com/24869170/191717103-7a1bbcdb-c020-4847-a65a-606decebb126.png)

**Comment by ntatfff** [comment]
Verified FAIL on Euphoria (11/10/2022)
- At Validator list - Undelegating
![image](https://user-images.githubusercontent.com/24869170/194992148-1842fa1c-79af-4ff7-96d7-758e231f05f2.png)

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (11/10/2022)
![image](https://user-images.githubusercontent.com/24869170/195070149-0b26d4dd-8091-4be9-b199-715507a7dfde.png)
![image](https://user-images.githubusercontent.com/24869170/195070185-590bb3b2-00c9-45ce-bd7b-569848cb1660.png)
![image](https://user-images.githubusercontent.com/24869170/195070207-4d8b2c5d-e216-48b8-ba82-c3ab19708a95.png)
![image](https://user-images.githubusercontent.com/24869170/195070229-d0906223-5809-4264-88bc-4ebac77e697c.png)
![image](https://user-images.githubusercontent.com/24869170/195070273-10dbf72e-65b5-45a4-b949-2dd87d58b0d7.png)
![image](https://user-images.githubusercontent.com/24869170/195070338-14f0d8cf-52af-462e-be50-5a4c3c5e222e.png)
![image](https://user-images.githubusercontent.com/24869170/195070470-e088d792-28a7-44dd-867f-52947868d435.png)
