### ISSUE TITLE
[Aurascan][Account Details] Redelegate tab, not display transactions when redelegate Jailed validator

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#991]
- [ ] ISSUE: Redelegate tab, not display transactions when redelegate Jailed validator

Transaction: https://serenity.aurascan.io/transaction/4FBA1FB58A71EBA9030BDAD4F86DC0750B5B23A23960848253283553D45B6BCA
![image](https://user-images.githubusercontent.com/72438169/189810488-8398094b-773d-41f6-ae44-89d7b880b14b.png)

Account Detail: https://serenity.aurascan.io/account/aura1xydnzs2s9pjh4cksc2ejv3t002d7pwedld2lp8
![image](https://user-images.githubusercontent.com/72438169/189810388-ba5f38cf-7732-440a-b916-fc73530df2f9.png)
![image](https://user-images.githubusercontent.com/72438169/189810429-87fe6e70-9fc5-46c3-8ef4-9a01343ba71d.png)

**Comment by doquockhanhan** [comment]
Hiện tại em check thì thông tin redelegate ở trong DB và ở trên network đag là y hệt nhau, vậy nên em nghĩ đây không phải là lỗi ở phía em mà là config sẵn của network không hiển thị. Mọi người hỏi anh Kiên cho rõ ạ.

**Comment by kienvc** [comment]
không phải issue nha, cái này cosmos sdk không hiển thị
