### ISSUE TITLE
[Aurascan][Tokens][TokenCW721Detail] Filter by token txn hash, token holder hiển thị sai kết quả Transfer, Inventory tab

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#998]
**Describe the bug**

- [x] ISSUE 01:  Filter by token txn hash hiển thị sai kết quả Transfers, Inventory tab

**To Reproduce**
1. Go to https://serenity.aurascan.io/tokens/token-nft/aura160nrpx8kvd72kctmvlraeumv9du5qetkqd79w96gya449ke2a2ds2lf6ag
2. Input "AEF14C9001A5A2D6DB7A28931277FCD77E183F712C7CE38EF26831422B724DD1" on textbox search
3. Click Transfers tab, Inventory tab

**Screenshots**
![image](https://user-images.githubusercontent.com/72438169/190114252-0e776d55-0b77-47a6-8852-1f120e049d4b.png)
![image](https://user-images.githubusercontent.com/72438169/190114059-91412d2f-8df7-4f36-b4c6-14fa6c0435b4.png)
![image](https://user-images.githubusercontent.com/72438169/190114083-6e1d4ae5-9807-4b7c-b705-c793798621bc.png)

- [x]  ISSUE 02: Filter by token holder hiển thị sai kết quả Transfers tab

Không hiển thị các transaction của Approve, Approve All, Revoke, Revoke All

**Screenshots**
![Image](https://user-images.githubusercontent.com/72438169/190116432-148a6405-3d36-401a-8a4d-8156aca06529.png)
![Image](https://user-images.githubusercontent.com/72438169/190121456-80157ff5-e044-4080-b82c-49d916bb0aed.png)

- [x] ISSUE 03: Inventory tab, Token ID không hiển thị theo update time giảm dần

![Image](https://user-images.githubusercontent.com/72438169/190124274-4412818c-7722-4d73-9086-c38b194e5ccf.png)
![Image](https://user-images.githubusercontent.com/72438169/190124399-19f67577-9332-4737-9bab-79b7768bedc6.png)

**Comment by fibonacci998** [comment]
Issue 1: Indexer return tx, but not shown in Frontend
Issue 2; Currently Indexer only support find tx smart contract with function mint or transfer. Address in approve, revoke,... is not supported to search

**Comment by fibonacci998** [comment]
Issue 1: transaction hash is not linked to an asset in inventory
Issue 2: Indexer now support search address approve, revoke, ... in smart contract transaction

**Comment by Dpthao245** [comment]
PASS in Serenity 22/11/2022

Filter by TxHash

![Image](https://user-images.githubusercontent.com/72438169/203280585-5f7e231e-9f94-4e69-aa49-500a9f5e5186.png)

![Image](https://user-images.githubusercontent.com/72438169/203280681-6519a6c8-a5f6-4d44-8d73-dbe487c21081.png)

Filter by Token Holder

![Image](https://user-images.githubusercontent.com/72438169/203282051-dab1d3cc-15eb-457c-8ee9-a5559b09821e.png)

![Image](https://user-images.githubusercontent.com/72438169/203282271-48f569c5-c3df-4fee-9197-89fbbf538d4b.png)

Filter by Token ID

![Image](https://user-images.githubusercontent.com/72438169/203282394-50f6dade-745b-4371-af29-bbd71221db15.png)

![Image](https://user-images.githubusercontent.com/72438169/203282439-154cbac2-5caf-4d24-89fb-f23092a6aad9.png)

**Comment by Dpthao245** [comment]
PASS in Euphoria 26/12/2022

- Filter by Token ID
![image](https://user-images.githubusercontent.com/72438169/209531368-2deeba2e-4a50-45ff-8117-25259fc7aace.png)
![image](https://user-images.githubusercontent.com/72438169/209531401-5546a711-45e9-43df-bc26-a5c91d3dcee1.png)

- Filter by TxHash
![image](https://user-images.githubusercontent.com/72438169/209531490-6cfc9fd8-11db-47d6-9e03-ff4ac0c60c17.png)
![image](https://user-images.githubusercontent.com/72438169/209531541-fb190097-ff4e-43ce-bcf5-663b8239ddb5.png)

- Filter by Address
![image](https://user-images.githubusercontent.com/72438169/209531730-2dbbcbb6-2ef1-4250-bd70-3aa7c45d83f4.png)
![image](https://user-images.githubusercontent.com/72438169/209531757-f49ccca6-9889-43a9-ba48-5b74f08ef4af.png)
